// interaction.proto
//
// 职责：Interaction 服务内部 gRPC 接口定义。
// 服务范围：点赞/收藏、互动计数、用户互动状态、用户互动列表。
// 主要接口：LikeFeed, UnlikeFeed, CollectFeed, UncollectFeed,
//          GetFeedStats, BatchGetFeedStats,
//          GetUserInteractionStatus, BatchGetUserInteractionStatus,
//          GetUserLikedFeeds, GetUserCollectedFeeds。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: api/proto/interaction/interaction.proto

package interaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FeedStats 帖子互动计数
type FeedStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedId        int64                  `protobuf:"varint,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`                   // 帖子 ID
	LikeCount     int64                  `protobuf:"varint,2,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`          // 点赞数
	CollectCount  int64                  `protobuf:"varint,3,opt,name=collect_count,json=collectCount,proto3" json:"collect_count,omitempty"` // 收藏数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedStats) Reset() {
	*x = FeedStats{}
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedStats) ProtoMessage() {}

func (x *FeedStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedStats.ProtoReflect.Descriptor instead.
func (*FeedStats) Descriptor() ([]byte, []int) {
	return file_api_proto_interaction_interaction_proto_rawDescGZIP(), []int{0}
}

func (x *FeedStats) GetFeedId() int64 {
	if x != nil {
		return x.FeedId
	}
	return 0
}

func (x *FeedStats) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *FeedStats) GetCollectCount() int64 {
	if x != nil {
		return x.CollectCount
	}
	return 0
}

// UserInteractionStatus 用户对单条帖子的互动状态
type UserInteractionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedId        int64                  `protobuf:"varint,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`                // 帖子 ID
	IsLiked       bool                   `protobuf:"varint,2,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`             // 是否已点赞
	IsCollected   bool                   `protobuf:"varint,3,opt,name=is_collected,json=isCollected,proto3" json:"is_collected,omitempty"` // 是否已收藏
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInteractionStatus) Reset() {
	*x = UserInteractionStatus{}
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInteractionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInteractionStatus) ProtoMessage() {}

func (x *UserInteractionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInteractionStatus.ProtoReflect.Descriptor instead.
func (*UserInteractionStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_interaction_interaction_proto_rawDescGZIP(), []int{1}
}

func (x *UserInteractionStatus) GetFeedId() int64 {
	if x != nil {
		return x.FeedId
	}
	return 0
}

func (x *UserInteractionStatus) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

func (x *UserInteractionStatus) GetIsCollected() bool {
	if x != nil {
		return x.IsCollected
	}
	return false
}

// 点赞帖子
type LikeFeedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 发起点赞的用户 ID
	FeedId        int64                  `protobuf:"varint,2,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"` // 被点赞的帖子 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeFeedReq) Reset() {
	*x = LikeFeedReq{}
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeFeedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeFeedReq) ProtoMessage() {}

func (x *LikeFeedReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeFeedReq.ProtoReflect.Descriptor instead.
func (*LikeFeedReq) Descriptor() ([]byte, []int) {
	return file_api_proto_interaction_interaction_proto_rawDescGZIP(), []int{2}
}

func (x *LikeFeedReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeFeedReq) GetFeedId() int64 {
	if x != nil {
		return x.FeedId
	}
	return 0
}

type LikeFeedResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeFeedResp) Reset() {
	*x = LikeFeedResp{}
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeFeedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeFeedResp) ProtoMessage() {}

func (x *LikeFeedResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeFeedResp.ProtoReflect.Descriptor instead.
func (*LikeFeedResp) Descriptor() ([]byte, []int) {
	return file_api_proto_interaction_interaction_proto_rawDescGZIP(), []int{3}
}

// 取消点赞
type UnlikeFeedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FeedId        int64                  `protobuf:"varint,2,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeFeedReq) Reset() {
	*x = UnlikeFeedReq{}
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeFeedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeFeedReq) ProtoMessage() {}

func (x *UnlikeFeedReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeFeedReq.ProtoReflect.Descriptor instead.
func (*UnlikeFeedReq) Descriptor() ([]byte, []int) {
	return file_api_proto_interaction_interaction_proto_rawDescGZIP(), []int{4}
}

func (x *UnlikeFeedReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnlikeFeedReq) GetFeedId() int64 {
	if x != nil {
		return x.FeedId
	}
	return 0
}

type UnlikeFeedResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeFeedResp) Reset() {
	*x = UnlikeFeedResp{}
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeFeedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeFeedResp) ProtoMessage() {}

func (x *UnlikeFeedResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeFeedResp.ProtoReflect.Descriptor instead.
func (*UnlikeFeedResp) Descriptor() ([]byte, []int) {
	return file_api_proto_interaction_interaction_proto_rawDescGZIP(), []int{5}
}

// 收藏帖子
type CollectFeedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FeedId        int64                  `protobuf:"varint,2,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectFeedReq) Reset() {
	*x = CollectFeedReq{}
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectFeedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectFeedReq) ProtoMessage() {}

func (x *CollectFeedReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectFeedReq.ProtoReflect.Descriptor instead.
func (*CollectFeedReq) Descriptor() ([]byte, []int) {
	return file_api_proto_interaction_interaction_proto_rawDescGZIP(), []int{6}
}

func (x *CollectFeedReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CollectFeedReq) GetFeedId() int64 {
	if x != nil {
		return x.FeedId
	}
	return 0
}

type CollectFeedResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectFeedResp) Reset() {
	*x = CollectFeedResp{}
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectFeedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectFeedResp) ProtoMessage() {}

func (x *CollectFeedResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectFeedResp.ProtoReflect.Descriptor instead.
func (*CollectFeedResp) Descriptor() ([]byte, []int) {
	return file_api_proto_interaction_interaction_proto_rawDescGZIP(), []int{7}
}

// 取消收藏
type UncollectFeedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FeedId        int64                  `protobuf:"varint,2,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UncollectFeedReq) Reset() {
	*x = UncollectFeedReq{}
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UncollectFeedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UncollectFeedReq) ProtoMessage() {}

func (x *UncollectFeedReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UncollectFeedReq.ProtoReflect.Descriptor instead.
func (*UncollectFeedReq) Descriptor() ([]byte, []int) {
	return file_api_proto_interaction_interaction_proto_rawDescGZIP(), []int{8}
}

func (x *UncollectFeedReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UncollectFeedReq) GetFeedId() int64 {
	if x != nil {
		return x.FeedId
	}
	return 0
}

type UncollectFeedResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UncollectFeedResp) Reset() {
	*x = UncollectFeedResp{}
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UncollectFeedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UncollectFeedResp) ProtoMessage() {}

func (x *UncollectFeedResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UncollectFeedResp.ProtoReflect.Descriptor instead.
func (*UncollectFeedResp) Descriptor() ([]byte, []int) {
	return file_api_proto_interaction_interaction_proto_rawDescGZIP(), []int{9}
}

// 单条帖子互动计数
type GetFeedStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedId        int64                  `protobuf:"varint,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedStatsReq) Reset() {
	*x = GetFeedStatsReq{}
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedStatsReq) ProtoMessage() {}

func (x *GetFeedStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedStatsReq.ProtoReflect.Descriptor instead.
func (*GetFeedStatsReq) Descriptor() ([]byte, []int) {
	return file_api_proto_interaction_interaction_proto_rawDescGZIP(), []int{10}
}

func (x *GetFeedStatsReq) GetFeedId() int64 {
	if x != nil {
		return x.FeedId
	}
	return 0
}

type GetFeedStatsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *FeedStats             `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedStatsResp) Reset() {
	*x = GetFeedStatsResp{}
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedStatsResp) ProtoMessage() {}

func (x *GetFeedStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedStatsResp.ProtoReflect.Descriptor instead.
func (*GetFeedStatsResp) Descriptor() ([]byte, []int) {
	return file_api_proto_interaction_interaction_proto_rawDescGZIP(), []int{11}
}

func (x *GetFeedStatsResp) GetStats() *FeedStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// 批量帖子互动计数
type BatchGetFeedStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedIds       []int64                `protobuf:"varint,1,rep,packed,name=feed_ids,json=feedIds,proto3" json:"feed_ids,omitempty"` // 帖子 ID 列表，建议单次不超过 100 个
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetFeedStatsReq) Reset() {
	*x = BatchGetFeedStatsReq{}
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetFeedStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetFeedStatsReq) ProtoMessage() {}

func (x *BatchGetFeedStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetFeedStatsReq.ProtoReflect.Descriptor instead.
func (*BatchGetFeedStatsReq) Descriptor() ([]byte, []int) {
	return file_api_proto_interaction_interaction_proto_rawDescGZIP(), []int{12}
}

func (x *BatchGetFeedStatsReq) GetFeedIds() []int64 {
	if x != nil {
		return x.FeedIds
	}
	return nil
}

type BatchGetFeedStatsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatsList     []*FeedStats           `protobuf:"bytes,1,rep,name=stats_list,json=statsList,proto3" json:"stats_list,omitempty"` // 与请求顺序保持一致
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetFeedStatsResp) Reset() {
	*x = BatchGetFeedStatsResp{}
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetFeedStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetFeedStatsResp) ProtoMessage() {}

func (x *BatchGetFeedStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetFeedStatsResp.ProtoReflect.Descriptor instead.
func (*BatchGetFeedStatsResp) Descriptor() ([]byte, []int) {
	return file_api_proto_interaction_interaction_proto_rawDescGZIP(), []int{13}
}

func (x *BatchGetFeedStatsResp) GetStatsList() []*FeedStats {
	if x != nil {
		return x.StatsList
	}
	return nil
}

// 单条帖子当前用户互动状态
type GetUserInteractionStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 当前查看者
	FeedId        int64                  `protobuf:"varint,2,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInteractionStatusReq) Reset() {
	*x = GetUserInteractionStatusReq{}
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInteractionStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInteractionStatusReq) ProtoMessage() {}

func (x *GetUserInteractionStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInteractionStatusReq.ProtoReflect.Descriptor instead.
func (*GetUserInteractionStatusReq) Descriptor() ([]byte, []int) {
	return file_api_proto_interaction_interaction_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserInteractionStatusReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserInteractionStatusReq) GetFeedId() int64 {
	if x != nil {
		return x.FeedId
	}
	return 0
}

type GetUserInteractionStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *UserInteractionStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInteractionStatusResp) Reset() {
	*x = GetUserInteractionStatusResp{}
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInteractionStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInteractionStatusResp) ProtoMessage() {}

func (x *GetUserInteractionStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInteractionStatusResp.ProtoReflect.Descriptor instead.
func (*GetUserInteractionStatusResp) Descriptor() ([]byte, []int) {
	return file_api_proto_interaction_interaction_proto_rawDescGZIP(), []int{15}
}

func (x *GetUserInteractionStatusResp) GetStatus() *UserInteractionStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// 批量帖子当前用户互动状态
type BatchGetUserInteractionStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FeedIds       []int64                `protobuf:"varint,2,rep,packed,name=feed_ids,json=feedIds,proto3" json:"feed_ids,omitempty"` // 建议单次不超过 100 个
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUserInteractionStatusReq) Reset() {
	*x = BatchGetUserInteractionStatusReq{}
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUserInteractionStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUserInteractionStatusReq) ProtoMessage() {}

func (x *BatchGetUserInteractionStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUserInteractionStatusReq.ProtoReflect.Descriptor instead.
func (*BatchGetUserInteractionStatusReq) Descriptor() ([]byte, []int) {
	return file_api_proto_interaction_interaction_proto_rawDescGZIP(), []int{16}
}

func (x *BatchGetUserInteractionStatusReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BatchGetUserInteractionStatusReq) GetFeedIds() []int64 {
	if x != nil {
		return x.FeedIds
	}
	return nil
}

type BatchGetUserInteractionStatusResp struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	StatusList    []*UserInteractionStatus `protobuf:"bytes,1,rep,name=status_list,json=statusList,proto3" json:"status_list,omitempty"` // 与请求顺序保持一致
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUserInteractionStatusResp) Reset() {
	*x = BatchGetUserInteractionStatusResp{}
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUserInteractionStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUserInteractionStatusResp) ProtoMessage() {}

func (x *BatchGetUserInteractionStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUserInteractionStatusResp.ProtoReflect.Descriptor instead.
func (*BatchGetUserInteractionStatusResp) Descriptor() ([]byte, []int) {
	return file_api_proto_interaction_interaction_proto_rawDescGZIP(), []int{17}
}

func (x *BatchGetUserInteractionStatusResp) GetStatusList() []*UserInteractionStatus {
	if x != nil {
		return x.StatusList
	}
	return nil
}

// 用户点赞过的帖子列表
type GetUserLikedFeedsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 要查询的用户 ID
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页条数，默认 20
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`                      // 游标，首页为空；由 score:feed_id base64 编码组成
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserLikedFeedsReq) Reset() {
	*x = GetUserLikedFeedsReq{}
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLikedFeedsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLikedFeedsReq) ProtoMessage() {}

func (x *GetUserLikedFeedsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLikedFeedsReq.ProtoReflect.Descriptor instead.
func (*GetUserLikedFeedsReq) Descriptor() ([]byte, []int) {
	return file_api_proto_interaction_interaction_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserLikedFeedsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserLikedFeedsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetUserLikedFeedsReq) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type GetUserLikedFeedsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedIds       []int64                `protobuf:"varint,1,rep,packed,name=feed_ids,json=feedIds,proto3" json:"feed_ids,omitempty"`  // 帖子 ID 列表，按点赞时间倒序
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"` // 下一页游标，为空表示没有更多
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`                            // 当前有效点赞总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserLikedFeedsResp) Reset() {
	*x = GetUserLikedFeedsResp{}
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLikedFeedsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLikedFeedsResp) ProtoMessage() {}

func (x *GetUserLikedFeedsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLikedFeedsResp.ProtoReflect.Descriptor instead.
func (*GetUserLikedFeedsResp) Descriptor() ([]byte, []int) {
	return file_api_proto_interaction_interaction_proto_rawDescGZIP(), []int{19}
}

func (x *GetUserLikedFeedsResp) GetFeedIds() []int64 {
	if x != nil {
		return x.FeedIds
	}
	return nil
}

func (x *GetUserLikedFeedsResp) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *GetUserLikedFeedsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 用户收藏过的帖子列表
type GetUserCollectedFeedsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCollectedFeedsReq) Reset() {
	*x = GetUserCollectedFeedsReq{}
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCollectedFeedsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCollectedFeedsReq) ProtoMessage() {}

func (x *GetUserCollectedFeedsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCollectedFeedsReq.ProtoReflect.Descriptor instead.
func (*GetUserCollectedFeedsReq) Descriptor() ([]byte, []int) {
	return file_api_proto_interaction_interaction_proto_rawDescGZIP(), []int{20}
}

func (x *GetUserCollectedFeedsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserCollectedFeedsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetUserCollectedFeedsReq) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type GetUserCollectedFeedsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedIds       []int64                `protobuf:"varint,1,rep,packed,name=feed_ids,json=feedIds,proto3" json:"feed_ids,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCollectedFeedsResp) Reset() {
	*x = GetUserCollectedFeedsResp{}
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCollectedFeedsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCollectedFeedsResp) ProtoMessage() {}

func (x *GetUserCollectedFeedsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_interaction_interaction_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCollectedFeedsResp.ProtoReflect.Descriptor instead.
func (*GetUserCollectedFeedsResp) Descriptor() ([]byte, []int) {
	return file_api_proto_interaction_interaction_proto_rawDescGZIP(), []int{21}
}

func (x *GetUserCollectedFeedsResp) GetFeedIds() []int64 {
	if x != nil {
		return x.FeedIds
	}
	return nil
}

func (x *GetUserCollectedFeedsResp) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *GetUserCollectedFeedsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_api_proto_interaction_interaction_proto protoreflect.FileDescriptor

const file_api_proto_interaction_interaction_proto_rawDesc = "" +
	"\n" +
	"'api/proto/interaction/interaction.proto\x12\vinteraction\"h\n" +
	"\tFeedStats\x12\x17\n" +
	"\afeed_id\x18\x01 \x01(\x03R\x06feedId\x12\x1d\n" +
	"\n" +
	"like_count\x18\x02 \x01(\x03R\tlikeCount\x12#\n" +
	"\rcollect_count\x18\x03 \x01(\x03R\fcollectCount\"n\n" +
	"\x15UserInteractionStatus\x12\x17\n" +
	"\afeed_id\x18\x01 \x01(\x03R\x06feedId\x12\x19\n" +
	"\bis_liked\x18\x02 \x01(\bR\aisLiked\x12!\n" +
	"\fis_collected\x18\x03 \x01(\bR\visCollected\"?\n" +
	"\vLikeFeedReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\afeed_id\x18\x02 \x01(\x03R\x06feedId\"\x0e\n" +
	"\fLikeFeedResp\"A\n" +
	"\rUnlikeFeedReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\afeed_id\x18\x02 \x01(\x03R\x06feedId\"\x10\n" +
	"\x0eUnlikeFeedResp\"B\n" +
	"\x0eCollectFeedReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\afeed_id\x18\x02 \x01(\x03R\x06feedId\"\x11\n" +
	"\x0fCollectFeedResp\"D\n" +
	"\x10UncollectFeedReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\afeed_id\x18\x02 \x01(\x03R\x06feedId\"\x13\n" +
	"\x11UncollectFeedResp\"*\n" +
	"\x0fGetFeedStatsReq\x12\x17\n" +
	"\afeed_id\x18\x01 \x01(\x03R\x06feedId\"@\n" +
	"\x10GetFeedStatsResp\x12,\n" +
	"\x05stats\x18\x01 \x01(\v2\x16.interaction.FeedStatsR\x05stats\"1\n" +
	"\x14BatchGetFeedStatsReq\x12\x19\n" +
	"\bfeed_ids\x18\x01 \x03(\x03R\afeedIds\"N\n" +
	"\x15BatchGetFeedStatsResp\x125\n" +
	"\n" +
	"stats_list\x18\x01 \x03(\v2\x16.interaction.FeedStatsR\tstatsList\"O\n" +
	"\x1bGetUserInteractionStatusReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\afeed_id\x18\x02 \x01(\x03R\x06feedId\"Z\n" +
	"\x1cGetUserInteractionStatusResp\x12:\n" +
	"\x06status\x18\x01 \x01(\v2\".interaction.UserInteractionStatusR\x06status\"V\n" +
	" BatchGetUserInteractionStatusReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bfeed_ids\x18\x02 \x03(\x03R\afeedIds\"h\n" +
	"!BatchGetUserInteractionStatusResp\x12C\n" +
	"\vstatus_list\x18\x01 \x03(\v2\".interaction.UserInteractionStatusR\n" +
	"statusList\"d\n" +
	"\x14GetUserLikedFeedsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"i\n" +
	"\x15GetUserLikedFeedsResp\x12\x19\n" +
	"\bfeed_ids\x18\x01 \x03(\x03R\afeedIds\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"h\n" +
	"\x18GetUserCollectedFeedsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"m\n" +
	"\x19GetUserCollectedFeedsResp\x12\x19\n" +
	"\bfeed_ids\x18\x01 \x03(\x03R\afeedIds\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total2\x8d\a\n" +
	"\vInteraction\x12?\n" +
	"\bLikeFeed\x12\x18.interaction.LikeFeedReq\x1a\x19.interaction.LikeFeedResp\x12E\n" +
	"\n" +
	"UnlikeFeed\x12\x1a.interaction.UnlikeFeedReq\x1a\x1b.interaction.UnlikeFeedResp\x12H\n" +
	"\vCollectFeed\x12\x1b.interaction.CollectFeedReq\x1a\x1c.interaction.CollectFeedResp\x12N\n" +
	"\rUncollectFeed\x12\x1d.interaction.UncollectFeedReq\x1a\x1e.interaction.UncollectFeedResp\x12K\n" +
	"\fGetFeedStats\x12\x1c.interaction.GetFeedStatsReq\x1a\x1d.interaction.GetFeedStatsResp\x12Z\n" +
	"\x11BatchGetFeedStats\x12!.interaction.BatchGetFeedStatsReq\x1a\".interaction.BatchGetFeedStatsResp\x12o\n" +
	"\x18GetUserInteractionStatus\x12(.interaction.GetUserInteractionStatusReq\x1a).interaction.GetUserInteractionStatusResp\x12~\n" +
	"\x1dBatchGetUserInteractionStatus\x12-.interaction.BatchGetUserInteractionStatusReq\x1a..interaction.BatchGetUserInteractionStatusResp\x12Z\n" +
	"\x11GetUserLikedFeeds\x12!.interaction.GetUserLikedFeedsReq\x1a\".interaction.GetUserLikedFeedsResp\x12f\n" +
	"\x15GetUserCollectedFeeds\x12%.interaction.GetUserCollectedFeedsReq\x1a&.interaction.GetUserCollectedFeedsRespB\x0fZ\r./interactionb\x06proto3"

var (
	file_api_proto_interaction_interaction_proto_rawDescOnce sync.Once
	file_api_proto_interaction_interaction_proto_rawDescData []byte
)

func file_api_proto_interaction_interaction_proto_rawDescGZIP() []byte {
	file_api_proto_interaction_interaction_proto_rawDescOnce.Do(func() {
		file_api_proto_interaction_interaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_interaction_interaction_proto_rawDesc), len(file_api_proto_interaction_interaction_proto_rawDesc)))
	})
	return file_api_proto_interaction_interaction_proto_rawDescData
}

var file_api_proto_interaction_interaction_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_api_proto_interaction_interaction_proto_goTypes = []any{
	(*FeedStats)(nil),                         // 0: interaction.FeedStats
	(*UserInteractionStatus)(nil),             // 1: interaction.UserInteractionStatus
	(*LikeFeedReq)(nil),                       // 2: interaction.LikeFeedReq
	(*LikeFeedResp)(nil),                      // 3: interaction.LikeFeedResp
	(*UnlikeFeedReq)(nil),                     // 4: interaction.UnlikeFeedReq
	(*UnlikeFeedResp)(nil),                    // 5: interaction.UnlikeFeedResp
	(*CollectFeedReq)(nil),                    // 6: interaction.CollectFeedReq
	(*CollectFeedResp)(nil),                   // 7: interaction.CollectFeedResp
	(*UncollectFeedReq)(nil),                  // 8: interaction.UncollectFeedReq
	(*UncollectFeedResp)(nil),                 // 9: interaction.UncollectFeedResp
	(*GetFeedStatsReq)(nil),                   // 10: interaction.GetFeedStatsReq
	(*GetFeedStatsResp)(nil),                  // 11: interaction.GetFeedStatsResp
	(*BatchGetFeedStatsReq)(nil),              // 12: interaction.BatchGetFeedStatsReq
	(*BatchGetFeedStatsResp)(nil),             // 13: interaction.BatchGetFeedStatsResp
	(*GetUserInteractionStatusReq)(nil),       // 14: interaction.GetUserInteractionStatusReq
	(*GetUserInteractionStatusResp)(nil),      // 15: interaction.GetUserInteractionStatusResp
	(*BatchGetUserInteractionStatusReq)(nil),  // 16: interaction.BatchGetUserInteractionStatusReq
	(*BatchGetUserInteractionStatusResp)(nil), // 17: interaction.BatchGetUserInteractionStatusResp
	(*GetUserLikedFeedsReq)(nil),              // 18: interaction.GetUserLikedFeedsReq
	(*GetUserLikedFeedsResp)(nil),             // 19: interaction.GetUserLikedFeedsResp
	(*GetUserCollectedFeedsReq)(nil),          // 20: interaction.GetUserCollectedFeedsReq
	(*GetUserCollectedFeedsResp)(nil),         // 21: interaction.GetUserCollectedFeedsResp
}
var file_api_proto_interaction_interaction_proto_depIdxs = []int32{
	0,  // 0: interaction.GetFeedStatsResp.stats:type_name -> interaction.FeedStats
	0,  // 1: interaction.BatchGetFeedStatsResp.stats_list:type_name -> interaction.FeedStats
	1,  // 2: interaction.GetUserInteractionStatusResp.status:type_name -> interaction.UserInteractionStatus
	1,  // 3: interaction.BatchGetUserInteractionStatusResp.status_list:type_name -> interaction.UserInteractionStatus
	2,  // 4: interaction.Interaction.LikeFeed:input_type -> interaction.LikeFeedReq
	4,  // 5: interaction.Interaction.UnlikeFeed:input_type -> interaction.UnlikeFeedReq
	6,  // 6: interaction.Interaction.CollectFeed:input_type -> interaction.CollectFeedReq
	8,  // 7: interaction.Interaction.UncollectFeed:input_type -> interaction.UncollectFeedReq
	10, // 8: interaction.Interaction.GetFeedStats:input_type -> interaction.GetFeedStatsReq
	12, // 9: interaction.Interaction.BatchGetFeedStats:input_type -> interaction.BatchGetFeedStatsReq
	14, // 10: interaction.Interaction.GetUserInteractionStatus:input_type -> interaction.GetUserInteractionStatusReq
	16, // 11: interaction.Interaction.BatchGetUserInteractionStatus:input_type -> interaction.BatchGetUserInteractionStatusReq
	18, // 12: interaction.Interaction.GetUserLikedFeeds:input_type -> interaction.GetUserLikedFeedsReq
	20, // 13: interaction.Interaction.GetUserCollectedFeeds:input_type -> interaction.GetUserCollectedFeedsReq
	3,  // 14: interaction.Interaction.LikeFeed:output_type -> interaction.LikeFeedResp
	5,  // 15: interaction.Interaction.UnlikeFeed:output_type -> interaction.UnlikeFeedResp
	7,  // 16: interaction.Interaction.CollectFeed:output_type -> interaction.CollectFeedResp
	9,  // 17: interaction.Interaction.UncollectFeed:output_type -> interaction.UncollectFeedResp
	11, // 18: interaction.Interaction.GetFeedStats:output_type -> interaction.GetFeedStatsResp
	13, // 19: interaction.Interaction.BatchGetFeedStats:output_type -> interaction.BatchGetFeedStatsResp
	15, // 20: interaction.Interaction.GetUserInteractionStatus:output_type -> interaction.GetUserInteractionStatusResp
	17, // 21: interaction.Interaction.BatchGetUserInteractionStatus:output_type -> interaction.BatchGetUserInteractionStatusResp
	19, // 22: interaction.Interaction.GetUserLikedFeeds:output_type -> interaction.GetUserLikedFeedsResp
	21, // 23: interaction.Interaction.GetUserCollectedFeeds:output_type -> interaction.GetUserCollectedFeedsResp
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_interaction_interaction_proto_init() }
func file_api_proto_interaction_interaction_proto_init() {
	if File_api_proto_interaction_interaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_interaction_interaction_proto_rawDesc), len(file_api_proto_interaction_interaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_interaction_interaction_proto_goTypes,
		DependencyIndexes: file_api_proto_interaction_interaction_proto_depIdxs,
		MessageInfos:      file_api_proto_interaction_interaction_proto_msgTypes,
	}.Build()
	File_api_proto_interaction_interaction_proto = out.File
	file_api_proto_interaction_interaction_proto_goTypes = nil
	file_api_proto_interaction_interaction_proto_depIdxs = nil
}
