// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: relation.proto

package server

import (
	"context"

	"github.com/sponge-dad/feed/app/relation/rpc/internal/logic"
	"github.com/sponge-dad/feed/app/relation/rpc/internal/svc"
	"github.com/sponge-dad/feed/app/relation/rpc/relation"
)

type RelationServer struct {
	svcCtx *svc.ServiceContext
	relation.UnimplementedRelationServer
}

func NewRelationServer(svcCtx *svc.ServiceContext) *RelationServer {
	return &RelationServer{
		svcCtx: svcCtx,
	}
}

func (s *RelationServer) Follow(ctx context.Context, in *relation.FollowReq) (*relation.FollowResp, error) {
	l := logic.NewFollowLogic(ctx, s.svcCtx)
	return l.Follow(in)
}

func (s *RelationServer) Unfollow(ctx context.Context, in *relation.UnfollowReq) (*relation.UnfollowResp, error) {
	l := logic.NewUnfollowLogic(ctx, s.svcCtx)
	return l.Unfollow(in)
}

func (s *RelationServer) GetFollows(ctx context.Context, in *relation.GetFollowsReq) (*relation.GetFollowsResp, error) {
	l := logic.NewGetFollowsLogic(ctx, s.svcCtx)
	return l.GetFollows(in)
}

func (s *RelationServer) GetFans(ctx context.Context, in *relation.GetFansReq) (*relation.GetFansResp, error) {
	l := logic.NewGetFansLogic(ctx, s.svcCtx)
	return l.GetFans(in)
}

func (s *RelationServer) IsFollow(ctx context.Context, in *relation.IsFollowReq) (*relation.IsFollowResp, error) {
	l := logic.NewIsFollowLogic(ctx, s.svcCtx)
	return l.IsFollow(in)
}

func (s *RelationServer) IsVip(ctx context.Context, in *relation.IsVipReq) (*relation.IsVipResp, error) {
	l := logic.NewIsVipLogic(ctx, s.svcCtx)
	return l.IsVip(in)
}
