// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: feed.proto

package server

import (
	"context"

	"github.com/sponge-dad/feed/app/feed/rpc/feed"
	"github.com/sponge-dad/feed/app/feed/rpc/internal/logic"
	"github.com/sponge-dad/feed/app/feed/rpc/internal/svc"
)

type FeedServer struct {
	svcCtx *svc.ServiceContext
	feed.UnimplementedFeedServer
}

func NewFeedServer(svcCtx *svc.ServiceContext) *FeedServer {
	return &FeedServer{
		svcCtx: svcCtx,
	}
}

// 创建帖子
func (s *FeedServer) CreateFeed(ctx context.Context, in *feed.CreateFeedReq) (*feed.CreateFeedResp, error) {
	l := logic.NewCreateFeedLogic(ctx, s.svcCtx)
	return l.CreateFeed(in)
}

// 删除帖子（软删除）
func (s *FeedServer) DeleteFeed(ctx context.Context, in *feed.DeleteFeedReq) (*feed.DeleteFeedResp, error) {
	l := logic.NewDeleteFeedLogic(ctx, s.svcCtx)
	return l.DeleteFeed(in)
}

// 获取帖子详情
func (s *FeedServer) GetFeed(ctx context.Context, in *feed.GetFeedReq) (*feed.GetFeedResp, error) {
	l := logic.NewGetFeedLogic(ctx, s.svcCtx)
	return l.GetFeed(in)
}

// 批量获取帖子详情
func (s *FeedServer) BatchGetFeeds(ctx context.Context, in *feed.BatchGetFeedsReq) (*feed.BatchGetFeedsResp, error) {
	l := logic.NewBatchGetFeedsLogic(ctx, s.svcCtx)
	return l.BatchGetFeeds(in)
}

// 推荐流
func (s *FeedServer) GetRecommendTimeline(ctx context.Context, in *feed.GetRecommendTimelineReq) (*feed.GetRecommendTimelineResp, error) {
	l := logic.NewGetRecommendTimelineLogic(ctx, s.svcCtx)
	return l.GetRecommendTimeline(in)
}

// 关注流
func (s *FeedServer) GetFollowTimeline(ctx context.Context, in *feed.GetFollowTimelineReq) (*feed.GetFollowTimelineResp, error) {
	l := logic.NewGetFollowTimelineLogic(ctx, s.svcCtx)
	return l.GetFollowTimeline(in)
}

// 同城流
func (s *FeedServer) GetCityTimeline(ctx context.Context, in *feed.GetCityTimelineReq) (*feed.GetCityTimelineResp, error) {
	l := logic.NewGetCityTimelineLogic(ctx, s.svcCtx)
	return l.GetCityTimeline(in)
}

// 个人主页帖子列表
func (s *FeedServer) GetUserFeeds(ctx context.Context, in *feed.GetUserFeedsReq) (*feed.GetUserFeedsResp, error) {
	l := logic.NewGetUserFeedsLogic(ctx, s.svcCtx)
	return l.GetUserFeeds(in)
}

// 查询某次请求中某条 feed 的来源（见 02-request-trace §6.3）
func (s *FeedServer) GetFeedSource(ctx context.Context, in *feed.GetFeedSourceReq) (*feed.GetFeedSourceResp, error) {
	l := logic.NewGetFeedSourceLogic(ctx, s.svcCtx)
	return l.GetFeedSource(in)
}

// 查询一次请求的完整 Trace（仅内部用户可调用，见 02-request-trace §6.3）
func (s *FeedServer) GetFeedRequestTrace(ctx context.Context, in *feed.GetFeedRequestTraceReq) (*feed.GetFeedRequestTraceResp, error) {
	l := logic.NewGetFeedRequestTraceLogic(ctx, s.svcCtx)
	return l.GetFeedRequestTrace(in)
}
