// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: content.proto

package contentClient

import (
	"context"

	"github.com/sponge-dad/feed/app/content/rpc/content"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetContentProfileReq  = content.BatchGetContentProfileReq
	BatchGetContentProfileResp = content.BatchGetContentProfileResp
	ContentProfile             = content.ContentProfile
	GetContentProfileReq       = content.GetContentProfileReq
	GetContentProfileResp      = content.GetContentProfileResp
	MatchReason                = content.MatchReason
	RetryContentAnalysisReq    = content.RetryContentAnalysisReq
	RetryContentAnalysisResp   = content.RetryContentAnalysisResp
	SearchContentReq           = content.SearchContentReq
	SearchContentResp          = content.SearchContentResp
	SearchResultItem           = content.SearchResultItem
	SubmitProfileFeedbackReq   = content.SubmitProfileFeedbackReq
	SubmitProfileFeedbackResp  = content.SubmitProfileFeedbackResp

	Content interface {
		GetContentProfile(ctx context.Context, in *GetContentProfileReq, opts ...grpc.CallOption) (*GetContentProfileResp, error)
		BatchGetContentProfile(ctx context.Context, in *BatchGetContentProfileReq, opts ...grpc.CallOption) (*BatchGetContentProfileResp, error)
		SearchContent(ctx context.Context, in *SearchContentReq, opts ...grpc.CallOption) (*SearchContentResp, error)
		RetryContentAnalysis(ctx context.Context, in *RetryContentAnalysisReq, opts ...grpc.CallOption) (*RetryContentAnalysisResp, error)
		SubmitProfileFeedback(ctx context.Context, in *SubmitProfileFeedbackReq, opts ...grpc.CallOption) (*SubmitProfileFeedbackResp, error)
	}

	defaultContent struct {
		cli zrpc.Client
	}
)

func NewContent(cli zrpc.Client) Content {
	return &defaultContent{
		cli: cli,
	}
}

func (m *defaultContent) GetContentProfile(ctx context.Context, in *GetContentProfileReq, opts ...grpc.CallOption) (*GetContentProfileResp, error) {
	client := content.NewContentClient(m.cli.Conn())
	return client.GetContentProfile(ctx, in, opts...)
}

func (m *defaultContent) BatchGetContentProfile(ctx context.Context, in *BatchGetContentProfileReq, opts ...grpc.CallOption) (*BatchGetContentProfileResp, error) {
	client := content.NewContentClient(m.cli.Conn())
	return client.BatchGetContentProfile(ctx, in, opts...)
}

func (m *defaultContent) SearchContent(ctx context.Context, in *SearchContentReq, opts ...grpc.CallOption) (*SearchContentResp, error) {
	client := content.NewContentClient(m.cli.Conn())
	return client.SearchContent(ctx, in, opts...)
}

func (m *defaultContent) RetryContentAnalysis(ctx context.Context, in *RetryContentAnalysisReq, opts ...grpc.CallOption) (*RetryContentAnalysisResp, error) {
	client := content.NewContentClient(m.cli.Conn())
	return client.RetryContentAnalysis(ctx, in, opts...)
}

func (m *defaultContent) SubmitProfileFeedback(ctx context.Context, in *SubmitProfileFeedbackReq, opts ...grpc.CallOption) (*SubmitProfileFeedbackResp, error) {
	client := content.NewContentClient(m.cli.Conn())
	return client.SubmitProfileFeedback(ctx, in, opts...)
}
