// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	relationsFieldNames          = builder.RawFieldNames(&Relations{})
	relationsRows                = strings.Join(relationsFieldNames, ",")
	relationsRowsExpectAutoSet   = strings.Join(stringx.Remove(relationsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	relationsRowsWithPlaceHolder = strings.Join(stringx.Remove(relationsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRelationsIdPrefix                   = "cache:relations:id:"
	cacheRelationsFollowerIdFolloweeIdPrefix = "cache:relations:followerId:followeeId:"
)

type (
	relationsModel interface {
		Insert(ctx context.Context, data *Relations) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Relations, error)
		FindOneByFollowerIdFolloweeId(ctx context.Context, followerId uint64, followeeId uint64) (*Relations, error)
		Update(ctx context.Context, data *Relations) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultRelationsModel struct {
		sqlc.CachedConn
		table string
	}

	Relations struct {
		Id         uint64 `db:"id"`          // Snowflake ID，应用层生成
		FollowerId uint64 `db:"follower_id"` // 发起关注的用户ID
		FolloweeId uint64 `db:"followee_id"` // 被关注的用户ID
		CreatedAt  int64  `db:"created_at"`  // 关注时间（Unix时间戳秒）
	}
)

func newRelationsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultRelationsModel {
	return &defaultRelationsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`relations`",
	}
}

func (m *defaultRelationsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	relationsFollowerIdFolloweeIdKey := fmt.Sprintf("%s%v:%v", cacheRelationsFollowerIdFolloweeIdPrefix, data.FollowerId, data.FolloweeId)
	relationsIdKey := fmt.Sprintf("%s%v", cacheRelationsIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, relationsFollowerIdFolloweeIdKey, relationsIdKey)
	return err
}

func (m *defaultRelationsModel) FindOne(ctx context.Context, id uint64) (*Relations, error) {
	relationsIdKey := fmt.Sprintf("%s%v", cacheRelationsIdPrefix, id)
	var resp Relations
	err := m.QueryRowCtx(ctx, &resp, relationsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", relationsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRelationsModel) FindOneByFollowerIdFolloweeId(ctx context.Context, followerId uint64, followeeId uint64) (*Relations, error) {
	relationsFollowerIdFolloweeIdKey := fmt.Sprintf("%s%v:%v", cacheRelationsFollowerIdFolloweeIdPrefix, followerId, followeeId)
	var resp Relations
	err := m.QueryRowIndexCtx(ctx, &resp, relationsFollowerIdFolloweeIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `follower_id` = ? and `followee_id` = ? limit 1", relationsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, followerId, followeeId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRelationsModel) Insert(ctx context.Context, data *Relations) (sql.Result, error) {
	relationsFollowerIdFolloweeIdKey := fmt.Sprintf("%s%v:%v", cacheRelationsFollowerIdFolloweeIdPrefix, data.FollowerId, data.FolloweeId)
	relationsIdKey := fmt.Sprintf("%s%v", cacheRelationsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, relationsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.FollowerId, data.FolloweeId)
	}, relationsFollowerIdFolloweeIdKey, relationsIdKey)
	return ret, err
}

func (m *defaultRelationsModel) Update(ctx context.Context, newData *Relations) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	relationsFollowerIdFolloweeIdKey := fmt.Sprintf("%s%v:%v", cacheRelationsFollowerIdFolloweeIdPrefix, data.FollowerId, data.FolloweeId)
	relationsIdKey := fmt.Sprintf("%s%v", cacheRelationsIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, relationsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.FollowerId, newData.FolloweeId, newData.Id)
	}, relationsFollowerIdFolloweeIdKey, relationsIdKey)
	return err
}

func (m *defaultRelationsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRelationsIdPrefix, primary)
}

func (m *defaultRelationsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", relationsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultRelationsModel) tableName() string {
	return m.table
}
