// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	likesFieldNames          = builder.RawFieldNames(&Likes{})
	likesRows                = strings.Join(likesFieldNames, ",")
	likesRowsExpectAutoSet   = strings.Join(stringx.Remove(likesFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	likesRowsWithPlaceHolder = strings.Join(stringx.Remove(likesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheLikesIdPrefix           = "cache:likes:id:"
	cacheLikesUserIdFeedIdPrefix = "cache:likes:userId:feedId:"
)

type (
	likesModel interface {
		Insert(ctx context.Context, data *Likes) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Likes, error)
		FindOneByUserIdFeedId(ctx context.Context, userId uint64, feedId uint64) (*Likes, error)
		Update(ctx context.Context, data *Likes) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultLikesModel struct {
		sqlc.CachedConn
		table string
	}

	Likes struct {
		Id        uint64    `db:"id"`         // Snowflake ID，应用层生成
		UserId    uint64    `db:"user_id"`    // 点赞用户 ID
		FeedId    uint64    `db:"feed_id"`    // 被点赞帖子 ID
		Status    int64     `db:"status"`     // 1:已点赞 2:已取消
		CreatedAt time.Time `db:"created_at"` // 点赞时间
		UpdatedAt time.Time `db:"updated_at"` // 状态更新时间
	}
)

func newLikesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultLikesModel {
	return &defaultLikesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`likes`",
	}
}

func (m *defaultLikesModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	likesIdKey := fmt.Sprintf("%s%v", cacheLikesIdPrefix, id)
	likesUserIdFeedIdKey := fmt.Sprintf("%s%v:%v", cacheLikesUserIdFeedIdPrefix, data.UserId, data.FeedId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, likesIdKey, likesUserIdFeedIdKey)
	return err
}

func (m *defaultLikesModel) FindOne(ctx context.Context, id uint64) (*Likes, error) {
	likesIdKey := fmt.Sprintf("%s%v", cacheLikesIdPrefix, id)
	var resp Likes
	err := m.QueryRowCtx(ctx, &resp, likesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", likesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLikesModel) FindOneByUserIdFeedId(ctx context.Context, userId uint64, feedId uint64) (*Likes, error) {
	likesUserIdFeedIdKey := fmt.Sprintf("%s%v:%v", cacheLikesUserIdFeedIdPrefix, userId, feedId)
	var resp Likes
	err := m.QueryRowIndexCtx(ctx, &resp, likesUserIdFeedIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `feed_id` = ? limit 1", likesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, feedId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLikesModel) Insert(ctx context.Context, data *Likes) (sql.Result, error) {
	likesIdKey := fmt.Sprintf("%s%v", cacheLikesIdPrefix, data.Id)
	likesUserIdFeedIdKey := fmt.Sprintf("%s%v:%v", cacheLikesUserIdFeedIdPrefix, data.UserId, data.FeedId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, likesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.UserId, data.FeedId, data.Status)
	}, likesIdKey, likesUserIdFeedIdKey)
	return ret, err
}

func (m *defaultLikesModel) Update(ctx context.Context, newData *Likes) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	likesIdKey := fmt.Sprintf("%s%v", cacheLikesIdPrefix, data.Id)
	likesUserIdFeedIdKey := fmt.Sprintf("%s%v:%v", cacheLikesUserIdFeedIdPrefix, data.UserId, data.FeedId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, likesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.FeedId, newData.Status, newData.Id)
	}, likesIdKey, likesUserIdFeedIdKey)
	return err
}

func (m *defaultLikesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheLikesIdPrefix, primary)
}

func (m *defaultLikesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", likesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultLikesModel) tableName() string {
	return m.table
}
