// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: relation.proto

package relationclient

import (
	"context"

	"github.com/sponge-dad/feed/app/relation/rpc/relation"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FollowReq      = relation.FollowReq
	FollowResp     = relation.FollowResp
	GetFansReq     = relation.GetFansReq
	GetFansResp    = relation.GetFansResp
	GetFollowsReq  = relation.GetFollowsReq
	GetFollowsResp = relation.GetFollowsResp
	IsFollowReq    = relation.IsFollowReq
	IsFollowResp   = relation.IsFollowResp
	IsVipReq       = relation.IsVipReq
	IsVipResp      = relation.IsVipResp
	UnfollowReq    = relation.UnfollowReq
	UnfollowResp   = relation.UnfollowResp

	Relation interface {
		Follow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error)
		Unfollow(ctx context.Context, in *UnfollowReq, opts ...grpc.CallOption) (*UnfollowResp, error)
		GetFollows(ctx context.Context, in *GetFollowsReq, opts ...grpc.CallOption) (*GetFollowsResp, error)
		GetFans(ctx context.Context, in *GetFansReq, opts ...grpc.CallOption) (*GetFansResp, error)
		IsFollow(ctx context.Context, in *IsFollowReq, opts ...grpc.CallOption) (*IsFollowResp, error)
		IsVip(ctx context.Context, in *IsVipReq, opts ...grpc.CallOption) (*IsVipResp, error)
	}

	defaultRelation struct {
		cli zrpc.Client
	}
)

func NewRelation(cli zrpc.Client) Relation {
	return &defaultRelation{
		cli: cli,
	}
}

func (m *defaultRelation) Follow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.Follow(ctx, in, opts...)
}

func (m *defaultRelation) Unfollow(ctx context.Context, in *UnfollowReq, opts ...grpc.CallOption) (*UnfollowResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.Unfollow(ctx, in, opts...)
}

func (m *defaultRelation) GetFollows(ctx context.Context, in *GetFollowsReq, opts ...grpc.CallOption) (*GetFollowsResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.GetFollows(ctx, in, opts...)
}

func (m *defaultRelation) GetFans(ctx context.Context, in *GetFansReq, opts ...grpc.CallOption) (*GetFansResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.GetFans(ctx, in, opts...)
}

func (m *defaultRelation) IsFollow(ctx context.Context, in *IsFollowReq, opts ...grpc.CallOption) (*IsFollowResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.IsFollow(ctx, in, opts...)
}

func (m *defaultRelation) IsVip(ctx context.Context, in *IsVipReq, opts ...grpc.CallOption) (*IsVipResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.IsVip(ctx, in, opts...)
}
