// content.proto
//
// 职责：Content 服务内部 gRPC 接口定义（FeedMind Agent 阶段二/三）。
// 服务范围：内容画像查询（分级返回）、批量画像、语义检索、重试分析、创作者纠错反馈。
// 端口：9007；Prometheus metrics：9110。
// 契约见 specs/001-feedmind-agent/contracts/grpc-services.md §1。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: api/proto/content/content.proto

package content

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 画像分析状态（与 feed_content_profiles.analysis_status 一一对应）
type AnalysisStatus int32

const (
	AnalysisStatus_ANALYSIS_UNKNOWN AnalysisStatus = 0  // 默认值，语义安全
	AnalysisStatus_PENDING          AnalysisStatus = 1  // 任务已创建，等待调度
	AnalysisStatus_DOWNLOADING      AnalysisStatus = 2  // 下载媒体
	AnalysisStatus_EXTRACTING       AnalysisStatus = 3  // FFmpeg 提取音频 + 抽关键帧
	AnalysisStatus_ASR_RUNNING      AnalysisStatus = 4  // 语音识别
	AnalysisStatus_OCR_RUNNING      AnalysisStatus = 5  // 画面文字识别
	AnalysisStatus_VISION_RUNNING   AnalysisStatus = 6  // 多模态摘要与标签
	AnalysisStatus_INDEXING         AnalysisStatus = 7  // 写检索索引
	AnalysisStatus_COMPLETED        AnalysisStatus = 8  // 全部完成
	AnalysisStatus_FAILED           AnalysisStatus = 9  // 整单失败
	AnalysisStatus_DISABLED         AnalysisStatus = 10 // 非视频 / 已删除，不分析
)

// Enum value maps for AnalysisStatus.
var (
	AnalysisStatus_name = map[int32]string{
		0:  "ANALYSIS_UNKNOWN",
		1:  "PENDING",
		2:  "DOWNLOADING",
		3:  "EXTRACTING",
		4:  "ASR_RUNNING",
		5:  "OCR_RUNNING",
		6:  "VISION_RUNNING",
		7:  "INDEXING",
		8:  "COMPLETED",
		9:  "FAILED",
		10: "DISABLED",
	}
	AnalysisStatus_value = map[string]int32{
		"ANALYSIS_UNKNOWN": 0,
		"PENDING":          1,
		"DOWNLOADING":      2,
		"EXTRACTING":       3,
		"ASR_RUNNING":      4,
		"OCR_RUNNING":      5,
		"VISION_RUNNING":   6,
		"INDEXING":         7,
		"COMPLETED":        8,
		"FAILED":           9,
		"DISABLED":         10,
	}
)

func (x AnalysisStatus) Enum() *AnalysisStatus {
	p := new(AnalysisStatus)
	*p = x
	return p
}

func (x AnalysisStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnalysisStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_content_content_proto_enumTypes[0].Descriptor()
}

func (AnalysisStatus) Type() protoreflect.EnumType {
	return &file_api_proto_content_content_proto_enumTypes[0]
}

func (x AnalysisStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnalysisStatus.Descriptor instead.
func (AnalysisStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_content_content_proto_rawDescGZIP(), []int{0}
}

// ContentProfile 内容画像（字幕/OCR 全文仅作者本人或内部可见，其他调用方只拿到公开字段）
type ContentProfile struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FeedId          int64                  `protobuf:"varint,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`                                                      // 帖子 ID
	AuthorId        int64                  `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`                                                // 作者 ID（权限校验用）
	Category        string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`                                                                 // 内容类别（白名单）
	Summary         string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`                                                                   // 内容摘要
	Topics          []string               `protobuf:"bytes,5,rep,name=topics,proto3" json:"topics,omitempty"`                                                                     // 主题标签
	Objects         []string               `protobuf:"bytes,6,rep,name=objects,proto3" json:"objects,omitempty"`                                                                   // 画面实体
	Scenes          []string               `protobuf:"bytes,7,rep,name=scenes,proto3" json:"scenes,omitempty"`                                                                     // 场景标签
	Styles          []string               `protobuf:"bytes,8,rep,name=styles,proto3" json:"styles,omitempty"`                                                                     // 内容形式标签
	Transcript      string                 `protobuf:"bytes,9,opt,name=transcript,proto3" json:"transcript,omitempty"`                                                             // 语音字幕全文（分级字段）
	OcrText         string                 `protobuf:"bytes,10,opt,name=ocr_text,json=ocrText,proto3" json:"ocr_text,omitempty"`                                                   // 关键帧文字（分级字段）
	Language        string                 `protobuf:"bytes,11,opt,name=language,proto3" json:"language,omitempty"`                                                                // 语言
	MediaDurationMs int64                  `protobuf:"varint,12,opt,name=media_duration_ms,json=mediaDurationMs,proto3" json:"media_duration_ms,omitempty"`                        // ffprobe 探测的真实时长
	KeyFrameCount   int32                  `protobuf:"varint,13,opt,name=key_frame_count,json=keyFrameCount,proto3" json:"key_frame_count,omitempty"`                              // 关键帧数量
	AnalysisStatus  AnalysisStatus         `protobuf:"varint,14,opt,name=analysis_status,json=analysisStatus,proto3,enum=content.AnalysisStatus" json:"analysis_status,omitempty"` // 分析状态
	Degraded        bool                   `protobuf:"varint,15,opt,name=degraded,proto3" json:"degraded,omitempty"`                                                               // 1=部分阶段失败但结果可用
	ModelVersion    string                 `protobuf:"bytes,16,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`                                    // 模型版本
	ErrorMessage    string                 `protobuf:"bytes,17,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                                    // 失败原因（仅内部可见）
	AnalyzedAt      int64                  `protobuf:"varint,18,opt,name=analyzed_at,json=analyzedAt,proto3" json:"analyzed_at,omitempty"`                                         // 分析完成时间（unix ms，0 表示未完成）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContentProfile) Reset() {
	*x = ContentProfile{}
	mi := &file_api_proto_content_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentProfile) ProtoMessage() {}

func (x *ContentProfile) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentProfile.ProtoReflect.Descriptor instead.
func (*ContentProfile) Descriptor() ([]byte, []int) {
	return file_api_proto_content_content_proto_rawDescGZIP(), []int{0}
}

func (x *ContentProfile) GetFeedId() int64 {
	if x != nil {
		return x.FeedId
	}
	return 0
}

func (x *ContentProfile) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *ContentProfile) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ContentProfile) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ContentProfile) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *ContentProfile) GetObjects() []string {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *ContentProfile) GetScenes() []string {
	if x != nil {
		return x.Scenes
	}
	return nil
}

func (x *ContentProfile) GetStyles() []string {
	if x != nil {
		return x.Styles
	}
	return nil
}

func (x *ContentProfile) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

func (x *ContentProfile) GetOcrText() string {
	if x != nil {
		return x.OcrText
	}
	return ""
}

func (x *ContentProfile) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ContentProfile) GetMediaDurationMs() int64 {
	if x != nil {
		return x.MediaDurationMs
	}
	return 0
}

func (x *ContentProfile) GetKeyFrameCount() int32 {
	if x != nil {
		return x.KeyFrameCount
	}
	return 0
}

func (x *ContentProfile) GetAnalysisStatus() AnalysisStatus {
	if x != nil {
		return x.AnalysisStatus
	}
	return AnalysisStatus_ANALYSIS_UNKNOWN
}

func (x *ContentProfile) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

func (x *ContentProfile) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *ContentProfile) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ContentProfile) GetAnalyzedAt() int64 {
	if x != nil {
		return x.AnalyzedAt
	}
	return 0
}

// 命中原因（后端生成，模型只负责转述）
type MatchReason struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`     // 如 TOPIC_MATCH / TRANSCRIPT_HIT / TITLE_HIT
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"` // 命中片段/说明（字幕片段 ≤80 字）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchReason) Reset() {
	*x = MatchReason{}
	mi := &file_api_proto_content_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchReason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchReason) ProtoMessage() {}

func (x *MatchReason) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchReason.ProtoReflect.Descriptor instead.
func (*MatchReason) Descriptor() ([]byte, []int) {
	return file_api_proto_content_content_proto_rawDescGZIP(), []int{1}
}

func (x *MatchReason) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MatchReason) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// 检索结果项
type SearchResultItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FeedId          int64                  `protobuf:"varint,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CoverUrl        string                 `protobuf:"bytes,3,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Category        string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	MatchedTopics   []string               `protobuf:"bytes,5,rep,name=matched_topics,json=matchedTopics,proto3" json:"matched_topics,omitempty"`
	MatchReasons    []*MatchReason         `protobuf:"bytes,6,rep,name=match_reasons,json=matchReasons,proto3" json:"match_reasons,omitempty"`
	MediaDurationMs int64                  `protobuf:"varint,7,opt,name=media_duration_ms,json=mediaDurationMs,proto3" json:"media_duration_ms,omitempty"`
	PublishedAt     int64                  `protobuf:"varint,8,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"` // unix ms
	Score           float64                `protobuf:"fixed64,9,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchResultItem) Reset() {
	*x = SearchResultItem{}
	mi := &file_api_proto_content_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResultItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResultItem) ProtoMessage() {}

func (x *SearchResultItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResultItem.ProtoReflect.Descriptor instead.
func (*SearchResultItem) Descriptor() ([]byte, []int) {
	return file_api_proto_content_content_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResultItem) GetFeedId() int64 {
	if x != nil {
		return x.FeedId
	}
	return 0
}

func (x *SearchResultItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchResultItem) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *SearchResultItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SearchResultItem) GetMatchedTopics() []string {
	if x != nil {
		return x.MatchedTopics
	}
	return nil
}

func (x *SearchResultItem) GetMatchReasons() []*MatchReason {
	if x != nil {
		return x.MatchReasons
	}
	return nil
}

func (x *SearchResultItem) GetMediaDurationMs() int64 {
	if x != nil {
		return x.MediaDurationMs
	}
	return 0
}

func (x *SearchResultItem) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

func (x *SearchResultItem) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

// 查询单条内容画像（分级返回）
type GetContentProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedId        int64                  `protobuf:"varint,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	ViewerId      int64                  `protobuf:"varint,2,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"` // 当前查看者，Gateway 从 JWT 注入
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentProfileReq) Reset() {
	*x = GetContentProfileReq{}
	mi := &file_api_proto_content_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentProfileReq) ProtoMessage() {}

func (x *GetContentProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentProfileReq.ProtoReflect.Descriptor instead.
func (*GetContentProfileReq) Descriptor() ([]byte, []int) {
	return file_api_proto_content_content_proto_rawDescGZIP(), []int{3}
}

func (x *GetContentProfileReq) GetFeedId() int64 {
	if x != nil {
		return x.FeedId
	}
	return 0
}

func (x *GetContentProfileReq) GetViewerId() int64 {
	if x != nil {
		return x.ViewerId
	}
	return 0
}

type GetContentProfileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *ContentProfile        `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentProfileResp) Reset() {
	*x = GetContentProfileResp{}
	mi := &file_api_proto_content_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentProfileResp) ProtoMessage() {}

func (x *GetContentProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentProfileResp.ProtoReflect.Descriptor instead.
func (*GetContentProfileResp) Descriptor() ([]byte, []int) {
	return file_api_proto_content_content_proto_rawDescGZIP(), []int{4}
}

func (x *GetContentProfileResp) GetProfile() *ContentProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// 批量查询内容画像（≤50，仅公开字段，供兴趣画像与推荐解释使用）
type BatchGetContentProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedIds       []int64                `protobuf:"varint,1,rep,packed,name=feed_ids,json=feedIds,proto3" json:"feed_ids,omitempty"` // 单次不超过 50 个，结果按请求顺序，缺失项跳过
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetContentProfileReq) Reset() {
	*x = BatchGetContentProfileReq{}
	mi := &file_api_proto_content_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetContentProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetContentProfileReq) ProtoMessage() {}

func (x *BatchGetContentProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetContentProfileReq.ProtoReflect.Descriptor instead.
func (*BatchGetContentProfileReq) Descriptor() ([]byte, []int) {
	return file_api_proto_content_content_proto_rawDescGZIP(), []int{5}
}

func (x *BatchGetContentProfileReq) GetFeedIds() []int64 {
	if x != nil {
		return x.FeedIds
	}
	return nil
}

type BatchGetContentProfileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*ContentProfile      `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetContentProfileResp) Reset() {
	*x = BatchGetContentProfileResp{}
	mi := &file_api_proto_content_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetContentProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetContentProfileResp) ProtoMessage() {}

func (x *BatchGetContentProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetContentProfileResp.ProtoReflect.Descriptor instead.
func (*BatchGetContentProfileResp) Descriptor() ([]byte, []int) {
	return file_api_proto_content_content_proto_rawDescGZIP(), []int{6}
}

func (x *BatchGetContentProfileResp) GetProfiles() []*ContentProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

// 结构化内容检索（入参为结构化条件，见 05-content-search.md §4）
type SearchContentReq struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Keywords            []string               `protobuf:"bytes,1,rep,name=keywords,proto3" json:"keywords,omitempty"`                                                     // ≤5 个，单个 1~20 字符
	Category            string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`                                                     // 类目白名单，非法置空降级
	Topics              []string               `protobuf:"bytes,3,rep,name=topics,proto3" json:"topics,omitempty"`                                                         // ≤5 个
	CityName            string                 `protobuf:"bytes,4,opt,name=city_name,json=cityName,proto3" json:"city_name,omitempty"`                                     // 城市名，映射失败作为普通关键词
	FeedType            int32                  `protobuf:"varint,5,opt,name=feed_type,json=feedType,proto3" json:"feed_type,omitempty"`                                    // 仅 1/2，其他置 0（不限）
	Sort                string                 `protobuf:"bytes,6,opt,name=sort,proto3" json:"sort,omitempty"`                                                             // relevance / latest / hot，默认 relevance
	Limit               int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`                                                          // 1~20
	PublishedWithinDays int32                  `protobuf:"varint,8,opt,name=published_within_days,json=publishedWithinDays,proto3" json:"published_within_days,omitempty"` // 1~365，收敛到边界
	ViewerId            int64                  `protobuf:"varint,9,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SearchContentReq) Reset() {
	*x = SearchContentReq{}
	mi := &file_api_proto_content_content_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchContentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchContentReq) ProtoMessage() {}

func (x *SearchContentReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_content_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchContentReq.ProtoReflect.Descriptor instead.
func (*SearchContentReq) Descriptor() ([]byte, []int) {
	return file_api_proto_content_content_proto_rawDescGZIP(), []int{7}
}

func (x *SearchContentReq) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *SearchContentReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SearchContentReq) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *SearchContentReq) GetCityName() string {
	if x != nil {
		return x.CityName
	}
	return ""
}

func (x *SearchContentReq) GetFeedType() int32 {
	if x != nil {
		return x.FeedType
	}
	return 0
}

func (x *SearchContentReq) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *SearchContentReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchContentReq) GetPublishedWithinDays() int32 {
	if x != nil {
		return x.PublishedWithinDays
	}
	return 0
}

func (x *SearchContentReq) GetViewerId() int64 {
	if x != nil {
		return x.ViewerId
	}
	return 0
}

type SearchContentResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalCandidates int32                  `protobuf:"varint,1,opt,name=total_candidates,json=totalCandidates,proto3" json:"total_candidates,omitempty"` // 融合后候选数（过滤前）
	Items           []*SearchResultItem    `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	NoMatchCode     string                 `protobuf:"bytes,3,opt,name=no_match_code,json=noMatchCode,proto3" json:"no_match_code,omitempty"` // 无结果原因：NO_MATCH / FILTERED_OUT，空串表示有结果
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchContentResp) Reset() {
	*x = SearchContentResp{}
	mi := &file_api_proto_content_content_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchContentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchContentResp) ProtoMessage() {}

func (x *SearchContentResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_content_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchContentResp.ProtoReflect.Descriptor instead.
func (*SearchContentResp) Descriptor() ([]byte, []int) {
	return file_api_proto_content_content_proto_rawDescGZIP(), []int{8}
}

func (x *SearchContentResp) GetTotalCandidates() int32 {
	if x != nil {
		return x.TotalCandidates
	}
	return 0
}

func (x *SearchContentResp) GetItems() []*SearchResultItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchContentResp) GetNoMatchCode() string {
	if x != nil {
		return x.NoMatchCode
	}
	return ""
}

// 内部重试分析（重置状态并重新入队）
type RetryContentAnalysisReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedId        int64                  `protobuf:"varint,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`                             // true 时忽略幂等（模型升级重跑）
	OperatorId    int64                  `protobuf:"varint,3,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"` // 内部用户 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryContentAnalysisReq) Reset() {
	*x = RetryContentAnalysisReq{}
	mi := &file_api_proto_content_content_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryContentAnalysisReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryContentAnalysisReq) ProtoMessage() {}

func (x *RetryContentAnalysisReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_content_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryContentAnalysisReq.ProtoReflect.Descriptor instead.
func (*RetryContentAnalysisReq) Descriptor() ([]byte, []int) {
	return file_api_proto_content_content_proto_rawDescGZIP(), []int{9}
}

func (x *RetryContentAnalysisReq) GetFeedId() int64 {
	if x != nil {
		return x.FeedId
	}
	return 0
}

func (x *RetryContentAnalysisReq) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *RetryContentAnalysisReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

type RetryContentAnalysisResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryContentAnalysisResp) Reset() {
	*x = RetryContentAnalysisResp{}
	mi := &file_api_proto_content_content_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryContentAnalysisResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryContentAnalysisResp) ProtoMessage() {}

func (x *RetryContentAnalysisResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_content_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryContentAnalysisResp.ProtoReflect.Descriptor instead.
func (*RetryContentAnalysisResp) Descriptor() ([]byte, []int) {
	return file_api_proto_content_content_proto_rawDescGZIP(), []int{10}
}

// 创作者纠错反馈（只记录，不改画像）
type SubmitProfileFeedbackReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedId        int64                  `protobuf:"varint,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 仅作者本人
	Field         string                 `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`                  // 纠错字段：category/summary/topics/...
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`              // 纠错说明
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitProfileFeedbackReq) Reset() {
	*x = SubmitProfileFeedbackReq{}
	mi := &file_api_proto_content_content_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitProfileFeedbackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitProfileFeedbackReq) ProtoMessage() {}

func (x *SubmitProfileFeedbackReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_content_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitProfileFeedbackReq.ProtoReflect.Descriptor instead.
func (*SubmitProfileFeedbackReq) Descriptor() ([]byte, []int) {
	return file_api_proto_content_content_proto_rawDescGZIP(), []int{11}
}

func (x *SubmitProfileFeedbackReq) GetFeedId() int64 {
	if x != nil {
		return x.FeedId
	}
	return 0
}

func (x *SubmitProfileFeedbackReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubmitProfileFeedbackReq) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SubmitProfileFeedbackReq) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type SubmitProfileFeedbackResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitProfileFeedbackResp) Reset() {
	*x = SubmitProfileFeedbackResp{}
	mi := &file_api_proto_content_content_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitProfileFeedbackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitProfileFeedbackResp) ProtoMessage() {}

func (x *SubmitProfileFeedbackResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_content_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitProfileFeedbackResp.ProtoReflect.Descriptor instead.
func (*SubmitProfileFeedbackResp) Descriptor() ([]byte, []int) {
	return file_api_proto_content_content_proto_rawDescGZIP(), []int{12}
}

var File_api_proto_content_content_proto protoreflect.FileDescriptor

const file_api_proto_content_content_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/content/content.proto\x12\acontent\"\xd2\x04\n" +
	"\x0eContentProfile\x12\x17\n" +
	"\afeed_id\x18\x01 \x01(\x03R\x06feedId\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\x03R\bauthorId\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x16\n" +
	"\x06topics\x18\x05 \x03(\tR\x06topics\x12\x18\n" +
	"\aobjects\x18\x06 \x03(\tR\aobjects\x12\x16\n" +
	"\x06scenes\x18\a \x03(\tR\x06scenes\x12\x16\n" +
	"\x06styles\x18\b \x03(\tR\x06styles\x12\x1e\n" +
	"\n" +
	"transcript\x18\t \x01(\tR\n" +
	"transcript\x12\x19\n" +
	"\bocr_text\x18\n" +
	" \x01(\tR\aocrText\x12\x1a\n" +
	"\blanguage\x18\v \x01(\tR\blanguage\x12*\n" +
	"\x11media_duration_ms\x18\f \x01(\x03R\x0fmediaDurationMs\x12&\n" +
	"\x0fkey_frame_count\x18\r \x01(\x05R\rkeyFrameCount\x12@\n" +
	"\x0fanalysis_status\x18\x0e \x01(\x0e2\x17.content.AnalysisStatusR\x0eanalysisStatus\x12\x1a\n" +
	"\bdegraded\x18\x0f \x01(\bR\bdegraded\x12#\n" +
	"\rmodel_version\x18\x10 \x01(\tR\fmodelVersion\x12#\n" +
	"\rerror_message\x18\x11 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vanalyzed_at\x18\x12 \x01(\x03R\n" +
	"analyzedAt\"9\n" +
	"\vMatchReason\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"\xc1\x02\n" +
	"\x10SearchResultItem\x12\x17\n" +
	"\afeed_id\x18\x01 \x01(\x03R\x06feedId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tcover_url\x18\x03 \x01(\tR\bcoverUrl\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12%\n" +
	"\x0ematched_topics\x18\x05 \x03(\tR\rmatchedTopics\x129\n" +
	"\rmatch_reasons\x18\x06 \x03(\v2\x14.content.MatchReasonR\fmatchReasons\x12*\n" +
	"\x11media_duration_ms\x18\a \x01(\x03R\x0fmediaDurationMs\x12!\n" +
	"\fpublished_at\x18\b \x01(\x03R\vpublishedAt\x12\x14\n" +
	"\x05score\x18\t \x01(\x01R\x05score\"L\n" +
	"\x14GetContentProfileReq\x12\x17\n" +
	"\afeed_id\x18\x01 \x01(\x03R\x06feedId\x12\x1b\n" +
	"\tviewer_id\x18\x02 \x01(\x03R\bviewerId\"J\n" +
	"\x15GetContentProfileResp\x121\n" +
	"\aprofile\x18\x01 \x01(\v2\x17.content.ContentProfileR\aprofile\"6\n" +
	"\x19BatchGetContentProfileReq\x12\x19\n" +
	"\bfeed_ids\x18\x01 \x03(\x03R\afeedIds\"Q\n" +
	"\x1aBatchGetContentProfileResp\x123\n" +
	"\bprofiles\x18\x01 \x03(\v2\x17.content.ContentProfileR\bprofiles\"\x97\x02\n" +
	"\x10SearchContentReq\x12\x1a\n" +
	"\bkeywords\x18\x01 \x03(\tR\bkeywords\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x16\n" +
	"\x06topics\x18\x03 \x03(\tR\x06topics\x12\x1b\n" +
	"\tcity_name\x18\x04 \x01(\tR\bcityName\x12\x1b\n" +
	"\tfeed_type\x18\x05 \x01(\x05R\bfeedType\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\tR\x04sort\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\x122\n" +
	"\x15published_within_days\x18\b \x01(\x05R\x13publishedWithinDays\x12\x1b\n" +
	"\tviewer_id\x18\t \x01(\x03R\bviewerId\"\x93\x01\n" +
	"\x11SearchContentResp\x12)\n" +
	"\x10total_candidates\x18\x01 \x01(\x05R\x0ftotalCandidates\x12/\n" +
	"\x05items\x18\x02 \x03(\v2\x19.content.SearchResultItemR\x05items\x12\"\n" +
	"\rno_match_code\x18\x03 \x01(\tR\vnoMatchCode\"i\n" +
	"\x17RetryContentAnalysisReq\x12\x17\n" +
	"\afeed_id\x18\x01 \x01(\x03R\x06feedId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\x12\x1f\n" +
	"\voperator_id\x18\x03 \x01(\x03R\n" +
	"operatorId\"\x1a\n" +
	"\x18RetryContentAnalysisResp\"|\n" +
	"\x18SubmitProfileFeedbackReq\x12\x17\n" +
	"\afeed_id\x18\x01 \x01(\x03R\x06feedId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05field\x18\x03 \x01(\tR\x05field\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\"\x1b\n" +
	"\x19SubmitProfileFeedbackResp*\xc1\x01\n" +
	"\x0eAnalysisStatus\x12\x14\n" +
	"\x10ANALYSIS_UNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\x0f\n" +
	"\vDOWNLOADING\x10\x02\x12\x0e\n" +
	"\n" +
	"EXTRACTING\x10\x03\x12\x0f\n" +
	"\vASR_RUNNING\x10\x04\x12\x0f\n" +
	"\vOCR_RUNNING\x10\x05\x12\x12\n" +
	"\x0eVISION_RUNNING\x10\x06\x12\f\n" +
	"\bINDEXING\x10\a\x12\r\n" +
	"\tCOMPLETED\x10\b\x12\n" +
	"\n" +
	"\x06FAILED\x10\t\x12\f\n" +
	"\bDISABLED\x10\n" +
	"2\xc5\x03\n" +
	"\aContent\x12R\n" +
	"\x11GetContentProfile\x12\x1d.content.GetContentProfileReq\x1a\x1e.content.GetContentProfileResp\x12a\n" +
	"\x16BatchGetContentProfile\x12\".content.BatchGetContentProfileReq\x1a#.content.BatchGetContentProfileResp\x12F\n" +
	"\rSearchContent\x12\x19.content.SearchContentReq\x1a\x1a.content.SearchContentResp\x12[\n" +
	"\x14RetryContentAnalysis\x12 .content.RetryContentAnalysisReq\x1a!.content.RetryContentAnalysisResp\x12^\n" +
	"\x15SubmitProfileFeedback\x12!.content.SubmitProfileFeedbackReq\x1a\".content.SubmitProfileFeedbackRespB\vZ\t./contentb\x06proto3"

var (
	file_api_proto_content_content_proto_rawDescOnce sync.Once
	file_api_proto_content_content_proto_rawDescData []byte
)

func file_api_proto_content_content_proto_rawDescGZIP() []byte {
	file_api_proto_content_content_proto_rawDescOnce.Do(func() {
		file_api_proto_content_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_content_content_proto_rawDesc), len(file_api_proto_content_content_proto_rawDesc)))
	})
	return file_api_proto_content_content_proto_rawDescData
}

var file_api_proto_content_content_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_content_content_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_proto_content_content_proto_goTypes = []any{
	(AnalysisStatus)(0),                // 0: content.AnalysisStatus
	(*ContentProfile)(nil),             // 1: content.ContentProfile
	(*MatchReason)(nil),                // 2: content.MatchReason
	(*SearchResultItem)(nil),           // 3: content.SearchResultItem
	(*GetContentProfileReq)(nil),       // 4: content.GetContentProfileReq
	(*GetContentProfileResp)(nil),      // 5: content.GetContentProfileResp
	(*BatchGetContentProfileReq)(nil),  // 6: content.BatchGetContentProfileReq
	(*BatchGetContentProfileResp)(nil), // 7: content.BatchGetContentProfileResp
	(*SearchContentReq)(nil),           // 8: content.SearchContentReq
	(*SearchContentResp)(nil),          // 9: content.SearchContentResp
	(*RetryContentAnalysisReq)(nil),    // 10: content.RetryContentAnalysisReq
	(*RetryContentAnalysisResp)(nil),   // 11: content.RetryContentAnalysisResp
	(*SubmitProfileFeedbackReq)(nil),   // 12: content.SubmitProfileFeedbackReq
	(*SubmitProfileFeedbackResp)(nil),  // 13: content.SubmitProfileFeedbackResp
}
var file_api_proto_content_content_proto_depIdxs = []int32{
	0,  // 0: content.ContentProfile.analysis_status:type_name -> content.AnalysisStatus
	2,  // 1: content.SearchResultItem.match_reasons:type_name -> content.MatchReason
	1,  // 2: content.GetContentProfileResp.profile:type_name -> content.ContentProfile
	1,  // 3: content.BatchGetContentProfileResp.profiles:type_name -> content.ContentProfile
	3,  // 4: content.SearchContentResp.items:type_name -> content.SearchResultItem
	4,  // 5: content.Content.GetContentProfile:input_type -> content.GetContentProfileReq
	6,  // 6: content.Content.BatchGetContentProfile:input_type -> content.BatchGetContentProfileReq
	8,  // 7: content.Content.SearchContent:input_type -> content.SearchContentReq
	10, // 8: content.Content.RetryContentAnalysis:input_type -> content.RetryContentAnalysisReq
	12, // 9: content.Content.SubmitProfileFeedback:input_type -> content.SubmitProfileFeedbackReq
	5,  // 10: content.Content.GetContentProfile:output_type -> content.GetContentProfileResp
	7,  // 11: content.Content.BatchGetContentProfile:output_type -> content.BatchGetContentProfileResp
	9,  // 12: content.Content.SearchContent:output_type -> content.SearchContentResp
	11, // 13: content.Content.RetryContentAnalysis:output_type -> content.RetryContentAnalysisResp
	13, // 14: content.Content.SubmitProfileFeedback:output_type -> content.SubmitProfileFeedbackResp
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_content_content_proto_init() }
func file_api_proto_content_content_proto_init() {
	if File_api_proto_content_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_content_content_proto_rawDesc), len(file_api_proto_content_content_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_content_content_proto_goTypes,
		DependencyIndexes: file_api_proto_content_content_proto_depIdxs,
		EnumInfos:         file_api_proto_content_content_proto_enumTypes,
		MessageInfos:      file_api_proto_content_content_proto_msgTypes,
	}.Build()
	File_api_proto_content_content_proto = out.File
	file_api_proto_content_content_proto_goTypes = nil
	file_api_proto_content_content_proto_depIdxs = nil
}
