// content.proto
//
// 职责：Content 服务内部 gRPC 接口定义（FeedMind Agent 阶段二/三）。
// 服务范围：内容画像查询（分级返回）、批量画像、语义检索、重试分析、创作者纠错反馈。
// 端口：9007；Prometheus metrics：9110。
// 契约见 specs/001-feedmind-agent/contracts/grpc-services.md §1。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: api/proto/content/content.proto

package content

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Content_GetContentProfile_FullMethodName      = "/content.Content/GetContentProfile"
	Content_BatchGetContentProfile_FullMethodName = "/content.Content/BatchGetContentProfile"
	Content_SearchContent_FullMethodName          = "/content.Content/SearchContent"
	Content_RetryContentAnalysis_FullMethodName   = "/content.Content/RetryContentAnalysis"
	Content_SubmitProfileFeedback_FullMethodName  = "/content.Content/SubmitProfileFeedback"
)

// ContentClient is the client API for Content service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== 服务定义 ====================
type ContentClient interface {
	GetContentProfile(ctx context.Context, in *GetContentProfileReq, opts ...grpc.CallOption) (*GetContentProfileResp, error)
	BatchGetContentProfile(ctx context.Context, in *BatchGetContentProfileReq, opts ...grpc.CallOption) (*BatchGetContentProfileResp, error)
	SearchContent(ctx context.Context, in *SearchContentReq, opts ...grpc.CallOption) (*SearchContentResp, error)
	RetryContentAnalysis(ctx context.Context, in *RetryContentAnalysisReq, opts ...grpc.CallOption) (*RetryContentAnalysisResp, error)
	SubmitProfileFeedback(ctx context.Context, in *SubmitProfileFeedbackReq, opts ...grpc.CallOption) (*SubmitProfileFeedbackResp, error)
}

type contentClient struct {
	cc grpc.ClientConnInterface
}

func NewContentClient(cc grpc.ClientConnInterface) ContentClient {
	return &contentClient{cc}
}

func (c *contentClient) GetContentProfile(ctx context.Context, in *GetContentProfileReq, opts ...grpc.CallOption) (*GetContentProfileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContentProfileResp)
	err := c.cc.Invoke(ctx, Content_GetContentProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) BatchGetContentProfile(ctx context.Context, in *BatchGetContentProfileReq, opts ...grpc.CallOption) (*BatchGetContentProfileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetContentProfileResp)
	err := c.cc.Invoke(ctx, Content_BatchGetContentProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) SearchContent(ctx context.Context, in *SearchContentReq, opts ...grpc.CallOption) (*SearchContentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchContentResp)
	err := c.cc.Invoke(ctx, Content_SearchContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) RetryContentAnalysis(ctx context.Context, in *RetryContentAnalysisReq, opts ...grpc.CallOption) (*RetryContentAnalysisResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryContentAnalysisResp)
	err := c.cc.Invoke(ctx, Content_RetryContentAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) SubmitProfileFeedback(ctx context.Context, in *SubmitProfileFeedbackReq, opts ...grpc.CallOption) (*SubmitProfileFeedbackResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitProfileFeedbackResp)
	err := c.cc.Invoke(ctx, Content_SubmitProfileFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentServer is the server API for Content service.
// All implementations must embed UnimplementedContentServer
// for forward compatibility.
//
// ==================== 服务定义 ====================
type ContentServer interface {
	GetContentProfile(context.Context, *GetContentProfileReq) (*GetContentProfileResp, error)
	BatchGetContentProfile(context.Context, *BatchGetContentProfileReq) (*BatchGetContentProfileResp, error)
	SearchContent(context.Context, *SearchContentReq) (*SearchContentResp, error)
	RetryContentAnalysis(context.Context, *RetryContentAnalysisReq) (*RetryContentAnalysisResp, error)
	SubmitProfileFeedback(context.Context, *SubmitProfileFeedbackReq) (*SubmitProfileFeedbackResp, error)
	mustEmbedUnimplementedContentServer()
}

// UnimplementedContentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContentServer struct{}

func (UnimplementedContentServer) GetContentProfile(context.Context, *GetContentProfileReq) (*GetContentProfileResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContentProfile not implemented")
}
func (UnimplementedContentServer) BatchGetContentProfile(context.Context, *BatchGetContentProfileReq) (*BatchGetContentProfileResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetContentProfile not implemented")
}
func (UnimplementedContentServer) SearchContent(context.Context, *SearchContentReq) (*SearchContentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchContent not implemented")
}
func (UnimplementedContentServer) RetryContentAnalysis(context.Context, *RetryContentAnalysisReq) (*RetryContentAnalysisResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryContentAnalysis not implemented")
}
func (UnimplementedContentServer) SubmitProfileFeedback(context.Context, *SubmitProfileFeedbackReq) (*SubmitProfileFeedbackResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitProfileFeedback not implemented")
}
func (UnimplementedContentServer) mustEmbedUnimplementedContentServer() {}
func (UnimplementedContentServer) testEmbeddedByValue()                 {}

// UnsafeContentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContentServer will
// result in compilation errors.
type UnsafeContentServer interface {
	mustEmbedUnimplementedContentServer()
}

func RegisterContentServer(s grpc.ServiceRegistrar, srv ContentServer) {
	// If the following call panics, it indicates UnimplementedContentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Content_ServiceDesc, srv)
}

func _Content_GetContentProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).GetContentProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_GetContentProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).GetContentProfile(ctx, req.(*GetContentProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_BatchGetContentProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetContentProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).BatchGetContentProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_BatchGetContentProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).BatchGetContentProfile(ctx, req.(*BatchGetContentProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_SearchContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchContentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).SearchContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_SearchContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).SearchContent(ctx, req.(*SearchContentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_RetryContentAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryContentAnalysisReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).RetryContentAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_RetryContentAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).RetryContentAnalysis(ctx, req.(*RetryContentAnalysisReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_SubmitProfileFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitProfileFeedbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).SubmitProfileFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_SubmitProfileFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).SubmitProfileFeedback(ctx, req.(*SubmitProfileFeedbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Content_ServiceDesc is the grpc.ServiceDesc for Content service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Content_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "content.Content",
	HandlerType: (*ContentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContentProfile",
			Handler:    _Content_GetContentProfile_Handler,
		},
		{
			MethodName: "BatchGetContentProfile",
			Handler:    _Content_BatchGetContentProfile_Handler,
		},
		{
			MethodName: "SearchContent",
			Handler:    _Content_SearchContent_Handler,
		},
		{
			MethodName: "RetryContentAnalysis",
			Handler:    _Content_RetryContentAnalysis_Handler,
		},
		{
			MethodName: "SubmitProfileFeedback",
			Handler:    _Content_SubmitProfileFeedback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/content/content.proto",
}
