// comment.proto
//
// 职责：Comment 服务内部 gRPC 接口定义。
// 服务范围：发表评论/回复（楼中楼两层平铺）、删除评论（软删除）、
//          一级评论分页（含子回复预览）、楼内回复分页、评论计数（单帖/批量）。
// 主要接口：CreateComment, DeleteComment, ListComments, ListReplies,
//          GetCommentCount, BatchGetCommentCount。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: api/proto/comment/comment.proto

package comment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Comment_CreateComment_FullMethodName        = "/comment.Comment/CreateComment"
	Comment_DeleteComment_FullMethodName        = "/comment.Comment/DeleteComment"
	Comment_ListComments_FullMethodName         = "/comment.Comment/ListComments"
	Comment_ListReplies_FullMethodName          = "/comment.Comment/ListReplies"
	Comment_GetCommentCount_FullMethodName      = "/comment.Comment/GetCommentCount"
	Comment_BatchGetCommentCount_FullMethodName = "/comment.Comment/BatchGetCommentCount"
	Comment_GetHotComments_FullMethodName       = "/comment.Comment/GetHotComments"
)

// CommentClient is the client API for Comment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommentClient interface {
	// 发表评论 / 回复评论（楼中楼）
	CreateComment(ctx context.Context, in *CreateCommentReq, opts ...grpc.CallOption) (*CreateCommentResp, error)
	// 删除评论（软删除，仅作者可删，幂等）
	DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error)
	// 一级评论分页，每楼附前 N 条子回复预览
	ListComments(ctx context.Context, in *ListCommentsReq, opts ...grpc.CallOption) (*ListCommentsResp, error)
	// 某根评论下全部子回复分页（查看全部回复）
	ListReplies(ctx context.Context, in *ListRepliesReq, opts ...grpc.CallOption) (*ListRepliesResp, error)
	// 单帖评论总数
	GetCommentCount(ctx context.Context, in *GetCommentCountReq, opts ...grpc.CallOption) (*GetCommentCountResp, error)
	// 批量评论总数（供 Feed 列表聚合，避免 N+1）
	BatchGetCommentCount(ctx context.Context, in *BatchGetCommentCountReq, opts ...grpc.CallOption) (*BatchGetCommentCountResp, error)
	// 帖子热门评论，按 like_count 降序 Top-K（仅一级评论，来自 comment_hot）
	GetHotComments(ctx context.Context, in *GetHotCommentsReq, opts ...grpc.CallOption) (*GetHotCommentsResp, error)
}

type commentClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentClient(cc grpc.ClientConnInterface) CommentClient {
	return &commentClient{cc}
}

func (c *commentClient) CreateComment(ctx context.Context, in *CreateCommentReq, opts ...grpc.CallOption) (*CreateCommentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCommentResp)
	err := c.cc.Invoke(ctx, Comment_CreateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCommentResp)
	err := c.cc.Invoke(ctx, Comment_DeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) ListComments(ctx context.Context, in *ListCommentsReq, opts ...grpc.CallOption) (*ListCommentsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommentsResp)
	err := c.cc.Invoke(ctx, Comment_ListComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) ListReplies(ctx context.Context, in *ListRepliesReq, opts ...grpc.CallOption) (*ListRepliesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRepliesResp)
	err := c.cc.Invoke(ctx, Comment_ListReplies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) GetCommentCount(ctx context.Context, in *GetCommentCountReq, opts ...grpc.CallOption) (*GetCommentCountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommentCountResp)
	err := c.cc.Invoke(ctx, Comment_GetCommentCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) BatchGetCommentCount(ctx context.Context, in *BatchGetCommentCountReq, opts ...grpc.CallOption) (*BatchGetCommentCountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetCommentCountResp)
	err := c.cc.Invoke(ctx, Comment_BatchGetCommentCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) GetHotComments(ctx context.Context, in *GetHotCommentsReq, opts ...grpc.CallOption) (*GetHotCommentsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHotCommentsResp)
	err := c.cc.Invoke(ctx, Comment_GetHotComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentServer is the server API for Comment service.
// All implementations must embed UnimplementedCommentServer
// for forward compatibility.
type CommentServer interface {
	// 发表评论 / 回复评论（楼中楼）
	CreateComment(context.Context, *CreateCommentReq) (*CreateCommentResp, error)
	// 删除评论（软删除，仅作者可删，幂等）
	DeleteComment(context.Context, *DeleteCommentReq) (*DeleteCommentResp, error)
	// 一级评论分页，每楼附前 N 条子回复预览
	ListComments(context.Context, *ListCommentsReq) (*ListCommentsResp, error)
	// 某根评论下全部子回复分页（查看全部回复）
	ListReplies(context.Context, *ListRepliesReq) (*ListRepliesResp, error)
	// 单帖评论总数
	GetCommentCount(context.Context, *GetCommentCountReq) (*GetCommentCountResp, error)
	// 批量评论总数（供 Feed 列表聚合，避免 N+1）
	BatchGetCommentCount(context.Context, *BatchGetCommentCountReq) (*BatchGetCommentCountResp, error)
	// 帖子热门评论，按 like_count 降序 Top-K（仅一级评论，来自 comment_hot）
	GetHotComments(context.Context, *GetHotCommentsReq) (*GetHotCommentsResp, error)
	mustEmbedUnimplementedCommentServer()
}

// UnimplementedCommentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommentServer struct{}

func (UnimplementedCommentServer) CreateComment(context.Context, *CreateCommentReq) (*CreateCommentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedCommentServer) DeleteComment(context.Context, *DeleteCommentReq) (*DeleteCommentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedCommentServer) ListComments(context.Context, *ListCommentsReq) (*ListCommentsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListComments not implemented")
}
func (UnimplementedCommentServer) ListReplies(context.Context, *ListRepliesReq) (*ListRepliesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListReplies not implemented")
}
func (UnimplementedCommentServer) GetCommentCount(context.Context, *GetCommentCountReq) (*GetCommentCountResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommentCount not implemented")
}
func (UnimplementedCommentServer) BatchGetCommentCount(context.Context, *BatchGetCommentCountReq) (*BatchGetCommentCountResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetCommentCount not implemented")
}
func (UnimplementedCommentServer) GetHotComments(context.Context, *GetHotCommentsReq) (*GetHotCommentsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHotComments not implemented")
}
func (UnimplementedCommentServer) mustEmbedUnimplementedCommentServer() {}
func (UnimplementedCommentServer) testEmbeddedByValue()                 {}

// UnsafeCommentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentServer will
// result in compilation errors.
type UnsafeCommentServer interface {
	mustEmbedUnimplementedCommentServer()
}

func RegisterCommentServer(s grpc.ServiceRegistrar, srv CommentServer) {
	// If the following call panics, it indicates UnimplementedCommentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Comment_ServiceDesc, srv)
}

func _Comment_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comment_CreateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).CreateComment(ctx, req.(*CreateCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comment_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).DeleteComment(ctx, req.(*DeleteCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_ListComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).ListComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comment_ListComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).ListComments(ctx, req.(*ListCommentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_ListReplies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRepliesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).ListReplies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comment_ListReplies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).ListReplies(ctx, req.(*ListRepliesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_GetCommentCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).GetCommentCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comment_GetCommentCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).GetCommentCount(ctx, req.(*GetCommentCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_BatchGetCommentCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetCommentCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).BatchGetCommentCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comment_BatchGetCommentCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).BatchGetCommentCount(ctx, req.(*BatchGetCommentCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_GetHotComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHotCommentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).GetHotComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comment_GetHotComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).GetHotComments(ctx, req.(*GetHotCommentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Comment_ServiceDesc is the grpc.ServiceDesc for Comment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Comment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "comment.Comment",
	HandlerType: (*CommentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateComment",
			Handler:    _Comment_CreateComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _Comment_DeleteComment_Handler,
		},
		{
			MethodName: "ListComments",
			Handler:    _Comment_ListComments_Handler,
		},
		{
			MethodName: "ListReplies",
			Handler:    _Comment_ListReplies_Handler,
		},
		{
			MethodName: "GetCommentCount",
			Handler:    _Comment_GetCommentCount_Handler,
		},
		{
			MethodName: "BatchGetCommentCount",
			Handler:    _Comment_BatchGetCommentCount_Handler,
		},
		{
			MethodName: "GetHotComments",
			Handler:    _Comment_GetHotComments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/comment/comment.proto",
}
