// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: feed.proto

package feedclient

import (
	"context"

	"github.com/sponge-dad/feed/app/feed/rpc/feed"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetFeedsReq         = feed.BatchGetFeedsReq
	BatchGetFeedsResp        = feed.BatchGetFeedsResp
	CreateFeedReq            = feed.CreateFeedReq
	CreateFeedResp           = feed.CreateFeedResp
	DeleteFeedReq            = feed.DeleteFeedReq
	DeleteFeedResp           = feed.DeleteFeedResp
	FeedBrief                = feed.FeedBrief
	FeedInfo                 = feed.FeedInfo
	FeedRequestTrace         = feed.FeedRequestTrace
	GetCityTimelineReq       = feed.GetCityTimelineReq
	GetCityTimelineResp      = feed.GetCityTimelineResp
	GetFeedReq               = feed.GetFeedReq
	GetFeedRequestTraceReq   = feed.GetFeedRequestTraceReq
	GetFeedRequestTraceResp  = feed.GetFeedRequestTraceResp
	GetFeedResp              = feed.GetFeedResp
	GetFeedSourceReq         = feed.GetFeedSourceReq
	GetFeedSourceResp        = feed.GetFeedSourceResp
	GetFollowTimelineReq     = feed.GetFollowTimelineReq
	GetFollowTimelineResp    = feed.GetFollowTimelineResp
	GetRecommendTimelineReq  = feed.GetRecommendTimelineReq
	GetRecommendTimelineResp = feed.GetRecommendTimelineResp
	GetUserFeedsReq          = feed.GetUserFeedsReq
	GetUserFeedsResp         = feed.GetUserFeedsResp
	PageInfo                 = feed.PageInfo
	SourceStat               = feed.SourceStat
	TraceItem                = feed.TraceItem

	Feed interface {
		// 创建帖子
		CreateFeed(ctx context.Context, in *CreateFeedReq, opts ...grpc.CallOption) (*CreateFeedResp, error)
		// 删除帖子（软删除）
		DeleteFeed(ctx context.Context, in *DeleteFeedReq, opts ...grpc.CallOption) (*DeleteFeedResp, error)
		// 获取帖子详情
		GetFeed(ctx context.Context, in *GetFeedReq, opts ...grpc.CallOption) (*GetFeedResp, error)
		// 批量获取帖子详情
		BatchGetFeeds(ctx context.Context, in *BatchGetFeedsReq, opts ...grpc.CallOption) (*BatchGetFeedsResp, error)
		// 推荐流
		GetRecommendTimeline(ctx context.Context, in *GetRecommendTimelineReq, opts ...grpc.CallOption) (*GetRecommendTimelineResp, error)
		// 关注流
		GetFollowTimeline(ctx context.Context, in *GetFollowTimelineReq, opts ...grpc.CallOption) (*GetFollowTimelineResp, error)
		// 同城流
		GetCityTimeline(ctx context.Context, in *GetCityTimelineReq, opts ...grpc.CallOption) (*GetCityTimelineResp, error)
		// 个人主页帖子列表
		GetUserFeeds(ctx context.Context, in *GetUserFeedsReq, opts ...grpc.CallOption) (*GetUserFeedsResp, error)
		// 查询某次请求中某条 feed 的来源（见 02-request-trace §6.3）
		GetFeedSource(ctx context.Context, in *GetFeedSourceReq, opts ...grpc.CallOption) (*GetFeedSourceResp, error)
		// 查询一次请求的完整 Trace（仅内部用户可调用，见 02-request-trace §6.3）
		GetFeedRequestTrace(ctx context.Context, in *GetFeedRequestTraceReq, opts ...grpc.CallOption) (*GetFeedRequestTraceResp, error)
	}

	defaultFeed struct {
		cli zrpc.Client
	}
)

func NewFeed(cli zrpc.Client) Feed {
	return &defaultFeed{
		cli: cli,
	}
}

// 创建帖子
func (m *defaultFeed) CreateFeed(ctx context.Context, in *CreateFeedReq, opts ...grpc.CallOption) (*CreateFeedResp, error) {
	client := feed.NewFeedClient(m.cli.Conn())
	return client.CreateFeed(ctx, in, opts...)
}

// 删除帖子（软删除）
func (m *defaultFeed) DeleteFeed(ctx context.Context, in *DeleteFeedReq, opts ...grpc.CallOption) (*DeleteFeedResp, error) {
	client := feed.NewFeedClient(m.cli.Conn())
	return client.DeleteFeed(ctx, in, opts...)
}

// 获取帖子详情
func (m *defaultFeed) GetFeed(ctx context.Context, in *GetFeedReq, opts ...grpc.CallOption) (*GetFeedResp, error) {
	client := feed.NewFeedClient(m.cli.Conn())
	return client.GetFeed(ctx, in, opts...)
}

// 批量获取帖子详情
func (m *defaultFeed) BatchGetFeeds(ctx context.Context, in *BatchGetFeedsReq, opts ...grpc.CallOption) (*BatchGetFeedsResp, error) {
	client := feed.NewFeedClient(m.cli.Conn())
	return client.BatchGetFeeds(ctx, in, opts...)
}

// 推荐流
func (m *defaultFeed) GetRecommendTimeline(ctx context.Context, in *GetRecommendTimelineReq, opts ...grpc.CallOption) (*GetRecommendTimelineResp, error) {
	client := feed.NewFeedClient(m.cli.Conn())
	return client.GetRecommendTimeline(ctx, in, opts...)
}

// 关注流
func (m *defaultFeed) GetFollowTimeline(ctx context.Context, in *GetFollowTimelineReq, opts ...grpc.CallOption) (*GetFollowTimelineResp, error) {
	client := feed.NewFeedClient(m.cli.Conn())
	return client.GetFollowTimeline(ctx, in, opts...)
}

// 同城流
func (m *defaultFeed) GetCityTimeline(ctx context.Context, in *GetCityTimelineReq, opts ...grpc.CallOption) (*GetCityTimelineResp, error) {
	client := feed.NewFeedClient(m.cli.Conn())
	return client.GetCityTimeline(ctx, in, opts...)
}

// 个人主页帖子列表
func (m *defaultFeed) GetUserFeeds(ctx context.Context, in *GetUserFeedsReq, opts ...grpc.CallOption) (*GetUserFeedsResp, error) {
	client := feed.NewFeedClient(m.cli.Conn())
	return client.GetUserFeeds(ctx, in, opts...)
}

// 查询某次请求中某条 feed 的来源（见 02-request-trace §6.3）
func (m *defaultFeed) GetFeedSource(ctx context.Context, in *GetFeedSourceReq, opts ...grpc.CallOption) (*GetFeedSourceResp, error) {
	client := feed.NewFeedClient(m.cli.Conn())
	return client.GetFeedSource(ctx, in, opts...)
}

// 查询一次请求的完整 Trace（仅内部用户可调用，见 02-request-trace §6.3）
func (m *defaultFeed) GetFeedRequestTrace(ctx context.Context, in *GetFeedRequestTraceReq, opts ...grpc.CallOption) (*GetFeedRequestTraceResp, error) {
	client := feed.NewFeedClient(m.cli.Conn())
	return client.GetFeedRequestTrace(ctx, in, opts...)
}
