// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	collectionsFieldNames          = builder.RawFieldNames(&Collections{})
	collectionsRows                = strings.Join(collectionsFieldNames, ",")
	collectionsRowsExpectAutoSet   = strings.Join(stringx.Remove(collectionsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	collectionsRowsWithPlaceHolder = strings.Join(stringx.Remove(collectionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCollectionsIdPrefix           = "cache:collections:id:"
	cacheCollectionsUserIdFeedIdPrefix = "cache:collections:userId:feedId:"
)

type (
	collectionsModel interface {
		Insert(ctx context.Context, data *Collections) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Collections, error)
		FindOneByUserIdFeedId(ctx context.Context, userId uint64, feedId uint64) (*Collections, error)
		Update(ctx context.Context, data *Collections) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCollectionsModel struct {
		sqlc.CachedConn
		table string
	}

	Collections struct {
		Id        uint64    `db:"id"`         // Snowflake ID，应用层生成
		UserId    uint64    `db:"user_id"`    // 收藏用户 ID
		FeedId    uint64    `db:"feed_id"`    // 被收藏帖子 ID
		Status    int64     `db:"status"`     // 1:已收藏 2:已取消
		CreatedAt time.Time `db:"created_at"` // 收藏时间
		UpdatedAt time.Time `db:"updated_at"` // 状态更新时间
	}
)

func newCollectionsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCollectionsModel {
	return &defaultCollectionsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`collections`",
	}
}

func (m *defaultCollectionsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	collectionsIdKey := fmt.Sprintf("%s%v", cacheCollectionsIdPrefix, id)
	collectionsUserIdFeedIdKey := fmt.Sprintf("%s%v:%v", cacheCollectionsUserIdFeedIdPrefix, data.UserId, data.FeedId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, collectionsIdKey, collectionsUserIdFeedIdKey)
	return err
}

func (m *defaultCollectionsModel) FindOne(ctx context.Context, id uint64) (*Collections, error) {
	collectionsIdKey := fmt.Sprintf("%s%v", cacheCollectionsIdPrefix, id)
	var resp Collections
	err := m.QueryRowCtx(ctx, &resp, collectionsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", collectionsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCollectionsModel) FindOneByUserIdFeedId(ctx context.Context, userId uint64, feedId uint64) (*Collections, error) {
	collectionsUserIdFeedIdKey := fmt.Sprintf("%s%v:%v", cacheCollectionsUserIdFeedIdPrefix, userId, feedId)
	var resp Collections
	err := m.QueryRowIndexCtx(ctx, &resp, collectionsUserIdFeedIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `feed_id` = ? limit 1", collectionsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, feedId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCollectionsModel) Insert(ctx context.Context, data *Collections) (sql.Result, error) {
	collectionsIdKey := fmt.Sprintf("%s%v", cacheCollectionsIdPrefix, data.Id)
	collectionsUserIdFeedIdKey := fmt.Sprintf("%s%v:%v", cacheCollectionsUserIdFeedIdPrefix, data.UserId, data.FeedId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, collectionsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.UserId, data.FeedId, data.Status)
	}, collectionsIdKey, collectionsUserIdFeedIdKey)
	return ret, err
}

func (m *defaultCollectionsModel) Update(ctx context.Context, newData *Collections) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	collectionsIdKey := fmt.Sprintf("%s%v", cacheCollectionsIdPrefix, data.Id)
	collectionsUserIdFeedIdKey := fmt.Sprintf("%s%v:%v", cacheCollectionsUserIdFeedIdPrefix, data.UserId, data.FeedId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, collectionsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.FeedId, newData.Status, newData.Id)
	}, collectionsIdKey, collectionsUserIdFeedIdKey)
	return err
}

func (m *defaultCollectionsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCollectionsIdPrefix, primary)
}

func (m *defaultCollectionsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", collectionsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCollectionsModel) tableName() string {
	return m.table
}
