// Code generated by goctl. DO NOT EDIT.
// 帖子小时级指标表模型（feed_metrics_hourly）。见 docs/design/agent/03-behavior-event.md。

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	feedMetricsHourlyFieldNames        = builder.RawFieldNames(&FeedMetricsHourly{})
	feedMetricsHourlyRows              = strings.Join(feedMetricsHourlyFieldNames, ",")
	feedMetricsHourlyRowsExpectAutoSet = strings.Join(stringx.Remove(feedMetricsHourlyFieldNames, "`id`", "`updated_at`"), ",")
)

type (
	feedMetricsHourlyModel interface {
		Insert(ctx context.Context, data *FeedMetricsHourly) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*FeedMetricsHourly, error)
	}

	defaultFeedMetricsHourlyModel struct {
		sqlc.CachedConn
		table string
	}

	FeedMetricsHourly struct {
		Id                 uint64    `db:"id"`
		FeedId             uint64    `db:"feed_id"`
		AuthorId           uint64    `db:"author_id"`
		StatHour           time.Time `db:"stat_hour"`
		ExposeCount        int64     `db:"expose_count"`
		PlayCount          int64     `db:"play_count"`
		EffectivePlayCount int64     `db:"effective_play_count"`
		FinishCount        int64     `db:"finish_count"`
		SkipCount          int64     `db:"skip_count"`
		ShareCount         int64     `db:"share_count"`
		LikeCount          int64     `db:"like_count"`
		CollectCount       int64     `db:"collect_count"`
		CommentCount       int64     `db:"comment_count"`
		WatchDurationMs    int64     `db:"watch_duration_ms"`
		UpdatedAt          time.Time `db:"updated_at"`
	}
)

func newFeedMetricsHourlyModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFeedMetricsHourlyModel {
	return &defaultFeedMetricsHourlyModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`feed_metrics_hourly`",
	}
}

func (m *defaultFeedMetricsHourlyModel) Insert(ctx context.Context, data *FeedMetricsHourly) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (%s)", m.table, feedMetricsHourlyRowsExpectAutoSet,
		strings.TrimSuffix(strings.Repeat("?, ", strings.Count(feedMetricsHourlyRowsExpectAutoSet, ",")+1), ", "))
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		return conn.ExecCtx(ctx, query, data.FeedId, data.AuthorId, data.StatHour, data.ExposeCount,
			data.PlayCount, data.EffectivePlayCount, data.FinishCount, data.SkipCount, data.ShareCount,
			data.LikeCount, data.CollectCount, data.CommentCount, data.WatchDurationMs)
	})
}

func (m *defaultFeedMetricsHourlyModel) FindOne(ctx context.Context, id uint64) (*FeedMetricsHourly, error) {
	var resp FeedMetricsHourly
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", feedMetricsHourlyRows, m.table)
	err := m.QueryRowNoCacheCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
