// Code generated by goctl. DO NOT EDIT.
// 帖子小时级指标表模型（feed_metrics_hourly）自定义扩展：Upsert 写绝对值。

package model

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
)

var _ FeedMetricsHourlyModel = (*customFeedMetricsHourlyModel)(nil)

type (
	FeedMetricsHourlyModel interface {
		feedMetricsHourlyModel
		// Upsert 按 (feed_id, stat_hour) 写入指标。
		// 关键：冲突时写【绝对值】(= VALUES(x))，而非增量累加，
		// 从而保证 flush 重复执行不会造成指标翻倍（见 03-behavior-event.md §6.2）。
		Upsert(ctx context.Context, data *FeedMetricsHourly) error
	}

	customFeedMetricsHourlyModel struct {
		*defaultFeedMetricsHourlyModel
	}
)

func NewFeedMetricsHourlyModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) FeedMetricsHourlyModel {
	return &customFeedMetricsHourlyModel{
		defaultFeedMetricsHourlyModel: newFeedMetricsHourlyModel(conn, c, opts...),
	}
}

// Upsert 把 Redis 累加的小时指标绝对值刷入 MySQL。
//
// 写绝对值而非增量：即使 flush 重复执行、或事件被重复消费（已被 event_id 幂等拦截），
// 小时表也不会重复累加——这是「行为事件重复消费不导致指标重复累加」的双重保证。
func (m *customFeedMetricsHourlyModel) Upsert(ctx context.Context, data *FeedMetricsHourly) error {
	query := fmt.Sprintf(`insert into %s
		(feed_id, author_id, stat_hour, expose_count, play_count, effective_play_count,
		 finish_count, skip_count, share_count, like_count, collect_count, comment_count,
		 watch_duration_ms, updated_at)
		values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, now())
		on duplicate key update
			-- 互动/评论事件不携带 author_id，传 0 时保留已有值，避免被覆盖成 0
			author_id = if(values(author_id) > 0, values(author_id), author_id),
			expose_count = values(expose_count),
			play_count = values(play_count),
			effective_play_count = values(effective_play_count),
			finish_count = values(finish_count),
			skip_count = values(skip_count),
			share_count = values(share_count),
			like_count = values(like_count),
			collect_count = values(collect_count),
			comment_count = values(comment_count),
			watch_duration_ms = values(watch_duration_ms),
			updated_at = now()`, m.table)

	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return conn.ExecCtx(ctx, query,
			data.FeedId, data.AuthorId, data.StatHour, data.ExposeCount, data.PlayCount,
			data.EffectivePlayCount, data.FinishCount, data.SkipCount, data.ShareCount,
			data.LikeCount, data.CollectCount, data.CommentCount, data.WatchDurationMs)
	})
	return err
}
