// Code generated by goctl. DO NOT EDIT.
// 帖子小时级指标表模型（feed_metrics_hourly）自定义扩展：Upsert 累加。

package model

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
)

var _ FeedMetricsHourlyModel = (*customFeedMetricsHourlyModel)(nil)

type (
	FeedMetricsHourlyModel interface {
		feedMetricsHourlyModel
		// Upsert 按 (feed_id, hour_bucket) 累加指标；冲突时叠加。
		Upsert(ctx context.Context, data *FeedMetricsHourly) error
	}

	customFeedMetricsHourlyModel struct {
		*defaultFeedMetricsHourlyModel
	}
)

func NewFeedMetricsHourlyModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) FeedMetricsHourlyModel {
	return &customFeedMetricsHourlyModel{
		defaultFeedMetricsHourlyModel: newFeedMetricsHourlyModel(conn, c, opts...),
	}
}

// Upsert 把 Redis 累加的小时指标刷入 MySQL，按 (feed_id, hour_bucket) 叠加。
func (m *customFeedMetricsHourlyModel) Upsert(ctx context.Context, data *FeedMetricsHourly) error {
	query := fmt.Sprintf(`insert into %s
		(feed_id, hour_bucket, pv, expose, `+"`like`"+`, collect, comment, share, duration_ms, updated_at)
		values (?, ?, ?, ?, ?, ?, ?, ?, ?, now())
		on duplicate key update
			pv = pv + values(pv),
			expose = expose + values(expose),
			`+"`like`"+` = `+"`like`"+` + values(`+"`like`"+`),
			collect = collect + values(collect),
			comment = comment + values(comment),
			share = share + values(share),
			duration_ms = duration_ms + values(duration_ms),
			updated_at = now()`, m.table)

	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return conn.ExecCtx(ctx, query,
			data.FeedId, data.HourBucket, data.Pv, data.Expose, data.Like,
			data.Collect, data.Comment, data.Share, data.DurationMs)
	})
	return err
}
