// Code generated by goctl. DO NOT EDIT.
// 行为明细表模型（feed_behavior_events）。见 docs/design/agent/03-behavior-event.md。

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	feedBehaviorEventsFieldNames        = builder.RawFieldNames(&FeedBehaviorEvents{})
	feedBehaviorEventsRows              = strings.Join(feedBehaviorEventsFieldNames, ",")
	feedBehaviorEventsRowsExpectAutoSet = strings.Join(stringx.Remove(feedBehaviorEventsFieldNames, "`created_at`"), ",")
)

type (
	feedBehaviorEventsModel interface {
		Insert(ctx context.Context, data *FeedBehaviorEvents) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*FeedBehaviorEvents, error)
		FindOneByEventId(ctx context.Context, eventId string) (*FeedBehaviorEvents, error)
	}

	defaultFeedBehaviorEventsModel struct {
		sqlc.CachedConn
		table string
	}

	FeedBehaviorEvents struct {
		Id        uint64    `db:"id"`
		EventId   string    `db:"event_id"`
		UserId    uint64    `db:"user_id"`
		FeedId    uint64    `db:"feed_id"`
		Action    string    `db:"action"`
		TargetId  uint64    `db:"target_id"`
		ClientIp  string    `db:"client_ip"`
		UserAgent string    `db:"user_agent"`
		ReqId     string    `db:"req_id"`
		CreatedAt time.Time `db:"created_at"`
	}
)

func newFeedBehaviorEventsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFeedBehaviorEventsModel {
	return &defaultFeedBehaviorEventsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`feed_behavior_events`",
	}
}

func (m *defaultFeedBehaviorEventsModel) Insert(ctx context.Context, data *FeedBehaviorEvents) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (%s)", m.table, feedBehaviorEventsRowsExpectAutoSet,
		strings.TrimSuffix(strings.Repeat("?, ", strings.Count(feedBehaviorEventsRowsExpectAutoSet, ",")+1), ", "))
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		return conn.ExecCtx(ctx, query, data.Id, data.EventId, data.UserId, data.FeedId, data.Action, data.TargetId, data.ClientIp, data.UserAgent, data.ReqId)
	})
}

func (m *defaultFeedBehaviorEventsModel) FindOne(ctx context.Context, id uint64) (*FeedBehaviorEvents, error) {
	var resp FeedBehaviorEvents
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", feedBehaviorEventsRows, m.table)
	err := m.QueryRowNoCacheCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFeedBehaviorEventsModel) FindOneByEventId(ctx context.Context, eventId string) (*FeedBehaviorEvents, error) {
	var resp FeedBehaviorEvents
	query := fmt.Sprintf("select %s from %s where `event_id` = ? limit 1", feedBehaviorEventsRows, m.table)
	err := m.QueryRowNoCacheCtx(ctx, &resp, query, eventId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
