// Code generated by goctl. DO NOT EDIT.
// 用户兴趣画像快照表模型（user_interest_profiles）。见 docs/design/agent/06-user-interest.md。

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userInterestProfilesFieldNames        = builder.RawFieldNames(&UserInterestProfiles{})
	userInterestProfilesRows              = strings.Join(userInterestProfilesFieldNames, ",")
	userInterestProfilesRowsExpectAutoSet = strings.Join(stringx.Remove(userInterestProfilesFieldNames, "`id`", "`created_at`", "`updated_at`"), ",")
)

type (
	userInterestProfilesModel interface {
		Insert(ctx context.Context, data *UserInterestProfiles) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserInterestProfiles, error)
		FindOneByUserId(ctx context.Context, userId int64) (*UserInterestProfiles, error)
		Update(ctx context.Context, data *UserInterestProfiles) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserInterestProfilesModel struct {
		sqlc.CachedConn
		table string
	}

	UserInterestProfiles struct {
		Id            uint64    `db:"id"`
		UserId        int64     `db:"user_id"`
		InterestJson  string    `db:"interest_json"`
		Version       int64     `db:"version"`
		CalculatedAt  time.Time `db:"calculated_at"`
		CreatedAt     time.Time `db:"created_at"`
		UpdatedAt     time.Time `db:"updated_at"`
	}
)

func newUserInterestProfilesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserInterestProfilesModel {
	return &defaultUserInterestProfilesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_interest_profiles`",
	}
}

func (m *defaultUserInterestProfilesModel) Insert(ctx context.Context, data *UserInterestProfiles) (sql.Result, error) {
	userInterestProfilesUserIdKey := fmt.Sprintf("%s%v", cacheUserInterestProfilesUserIdPrefix, data.UserId)
	query := fmt.Sprintf("insert into %s (%s) values (%s)", m.table, userInterestProfilesRowsExpectAutoSet,
		strings.TrimSuffix(strings.Repeat("?, ", strings.Count(userInterestProfilesRowsExpectAutoSet, ",")+1), ", "))
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		return conn.ExecCtx(ctx, query, data.UserId, data.InterestJson, data.Version, data.CalculatedAt)
	}, userInterestProfilesUserIdKey)
}

func (m *defaultUserInterestProfilesModel) FindOne(ctx context.Context, id uint64) (*UserInterestProfiles, error) {
	userInterestProfilesIdKey := fmt.Sprintf("%s%v", cacheUserInterestProfilesIdPrefix, id)
	var resp UserInterestProfiles
	err := m.QueryRowCtx(ctx, &resp, userInterestProfilesIdKey,
		func(ctx context.Context, conn sqlx.SqlConn, v any) error {
			query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userInterestProfilesRows, m.table)
			return conn.QueryRowCtx(ctx, v, query, id)
		})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserInterestProfilesModel) FindOneByUserId(ctx context.Context, userId int64) (*UserInterestProfiles, error) {
	userInterestProfilesUserIdKey := fmt.Sprintf("%s%v", cacheUserInterestProfilesUserIdPrefix, userId)
	var resp UserInterestProfiles
	err := m.QueryRowIndexCtx(ctx, &resp, userInterestProfilesUserIdKey,
		m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (any, error) {
			query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", userInterestProfilesRows, m.table)
			if err := conn.QueryRowCtx(ctx, &resp, query, userId); err != nil {
				return nil, err
			}
			return resp.Id, nil
		},
		m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserInterestProfilesModel) Update(ctx context.Context, data *UserInterestProfiles) error {
	userInterestProfilesIdKey := fmt.Sprintf("%s%v", cacheUserInterestProfilesIdPrefix, data.Id)
	userInterestProfilesUserIdKey := fmt.Sprintf("%s%v", cacheUserInterestProfilesUserIdPrefix, data.UserId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set `user_id` = ?, `interest_json` = ?, `version` = ?, `calculated_at` = ? where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, data.UserId, data.InterestJson, data.Version, data.CalculatedAt, data.Id)
	}, userInterestProfilesIdKey, userInterestProfilesUserIdKey)
	return err
}

func (m *defaultUserInterestProfilesModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}
	userInterestProfilesIdKey := fmt.Sprintf("%s%v", cacheUserInterestProfilesIdPrefix, id)
	userInterestProfilesUserIdKey := fmt.Sprintf("%s%v", cacheUserInterestProfilesUserIdPrefix, data.UserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userInterestProfilesIdKey, userInterestProfilesUserIdKey)
	return err
}

func (m *defaultUserInterestProfilesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserInterestProfilesIdPrefix, primary)
}

func (m *defaultUserInterestProfilesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userInterestProfilesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserInterestProfilesModel) tableName() string {
	return m.table
}
