// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: comment.proto

package commentClient

import (
	"context"

	"github.com/sponge-dad/feed/app/comment/rpc/comment"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetCommentCountReq  = comment.BatchGetCommentCountReq
	BatchGetCommentCountResp = comment.BatchGetCommentCountResp
	CommentInfo              = comment.CommentInfo
	CommentWithReplies       = comment.CommentWithReplies
	CreateCommentReq         = comment.CreateCommentReq
	CreateCommentResp        = comment.CreateCommentResp
	DeleteCommentReq         = comment.DeleteCommentReq
	DeleteCommentResp        = comment.DeleteCommentResp
	GetCommentCountReq       = comment.GetCommentCountReq
	GetCommentCountResp      = comment.GetCommentCountResp
	GetHotCommentsReq        = comment.GetHotCommentsReq
	GetHotCommentsResp       = comment.GetHotCommentsResp
	ListCommentsReq          = comment.ListCommentsReq
	ListCommentsResp         = comment.ListCommentsResp
	ListRepliesReq           = comment.ListRepliesReq
	ListRepliesResp          = comment.ListRepliesResp
	PageInfo                 = comment.PageInfo

	Comment interface {
		// 发表评论 / 回复评论（楼中楼）
		CreateComment(ctx context.Context, in *CreateCommentReq, opts ...grpc.CallOption) (*CreateCommentResp, error)
		// 删除评论（软删除，仅作者可删，幂等）
		DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error)
		// 一级评论分页，每楼附前 N 条子回复预览
		ListComments(ctx context.Context, in *ListCommentsReq, opts ...grpc.CallOption) (*ListCommentsResp, error)
		// 某根评论下全部子回复分页（查看全部回复）
		ListReplies(ctx context.Context, in *ListRepliesReq, opts ...grpc.CallOption) (*ListRepliesResp, error)
		// 单帖评论总数
		GetCommentCount(ctx context.Context, in *GetCommentCountReq, opts ...grpc.CallOption) (*GetCommentCountResp, error)
		// 批量评论总数（供 Feed 列表聚合，避免 N+1）
		BatchGetCommentCount(ctx context.Context, in *BatchGetCommentCountReq, opts ...grpc.CallOption) (*BatchGetCommentCountResp, error)
		// 帖子热门评论，按 like_count 降序 Top-K（仅一级评论，来自 comment_hot）
		GetHotComments(ctx context.Context, in *GetHotCommentsReq, opts ...grpc.CallOption) (*GetHotCommentsResp, error)
	}

	defaultComment struct {
		cli zrpc.Client
	}
)

func NewComment(cli zrpc.Client) Comment {
	return &defaultComment{
		cli: cli,
	}
}

// 发表评论 / 回复评论（楼中楼）
func (m *defaultComment) CreateComment(ctx context.Context, in *CreateCommentReq, opts ...grpc.CallOption) (*CreateCommentResp, error) {
	client := comment.NewCommentClient(m.cli.Conn())
	return client.CreateComment(ctx, in, opts...)
}

// 删除评论（软删除，仅作者可删，幂等）
func (m *defaultComment) DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error) {
	client := comment.NewCommentClient(m.cli.Conn())
	return client.DeleteComment(ctx, in, opts...)
}

// 一级评论分页，每楼附前 N 条子回复预览
func (m *defaultComment) ListComments(ctx context.Context, in *ListCommentsReq, opts ...grpc.CallOption) (*ListCommentsResp, error) {
	client := comment.NewCommentClient(m.cli.Conn())
	return client.ListComments(ctx, in, opts...)
}

// 某根评论下全部子回复分页（查看全部回复）
func (m *defaultComment) ListReplies(ctx context.Context, in *ListRepliesReq, opts ...grpc.CallOption) (*ListRepliesResp, error) {
	client := comment.NewCommentClient(m.cli.Conn())
	return client.ListReplies(ctx, in, opts...)
}

// 单帖评论总数
func (m *defaultComment) GetCommentCount(ctx context.Context, in *GetCommentCountReq, opts ...grpc.CallOption) (*GetCommentCountResp, error) {
	client := comment.NewCommentClient(m.cli.Conn())
	return client.GetCommentCount(ctx, in, opts...)
}

// 批量评论总数（供 Feed 列表聚合，避免 N+1）
func (m *defaultComment) BatchGetCommentCount(ctx context.Context, in *BatchGetCommentCountReq, opts ...grpc.CallOption) (*BatchGetCommentCountResp, error) {
	client := comment.NewCommentClient(m.cli.Conn())
	return client.BatchGetCommentCount(ctx, in, opts...)
}

// 帖子热门评论，按 like_count 降序 Top-K（仅一级评论，来自 comment_hot）
func (m *defaultComment) GetHotComments(ctx context.Context, in *GetHotCommentsReq, opts ...grpc.CallOption) (*GetHotCommentsResp, error) {
	client := comment.NewCommentClient(m.cli.Conn())
	return client.GetHotComments(ctx, in, opts...)
}
