// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sponge-dad/feed/app/feed/rpc/feedclient (interfaces: Feed)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	feed "github.com/sponge-dad/feed/app/feed/rpc/feed"
	grpc "google.golang.org/grpc"
)

// MockFeed is a mock of Feed interface.
type MockFeed struct {
	ctrl     *gomock.Controller
	recorder *MockFeedMockRecorder
}

// MockFeedMockRecorder is the mock recorder for MockFeed.
type MockFeedMockRecorder struct {
	mock *MockFeed
}

// NewMockFeed creates a new mock instance.
func NewMockFeed(ctrl *gomock.Controller) *MockFeed {
	mock := &MockFeed{ctrl: ctrl}
	mock.recorder = &MockFeedMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeed) EXPECT() *MockFeedMockRecorder {
	return m.recorder
}

// BatchGetFeeds mocks base method.
func (m *MockFeed) BatchGetFeeds(arg0 context.Context, arg1 *feed.BatchGetFeedsReq, arg2 ...grpc.CallOption) (*feed.BatchGetFeedsResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchGetFeeds", varargs...)
	ret0, _ := ret[0].(*feed.BatchGetFeedsResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetFeeds indicates an expected call of BatchGetFeeds.
func (mr *MockFeedMockRecorder) BatchGetFeeds(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetFeeds", reflect.TypeOf((*MockFeed)(nil).BatchGetFeeds), varargs...)
}

// CreateFeed mocks base method.
func (m *MockFeed) CreateFeed(arg0 context.Context, arg1 *feed.CreateFeedReq, arg2 ...grpc.CallOption) (*feed.CreateFeedResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateFeed", varargs...)
	ret0, _ := ret[0].(*feed.CreateFeedResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFeed indicates an expected call of CreateFeed.
func (mr *MockFeedMockRecorder) CreateFeed(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFeed", reflect.TypeOf((*MockFeed)(nil).CreateFeed), varargs...)
}

// DeleteFeed mocks base method.
func (m *MockFeed) DeleteFeed(arg0 context.Context, arg1 *feed.DeleteFeedReq, arg2 ...grpc.CallOption) (*feed.DeleteFeedResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteFeed", varargs...)
	ret0, _ := ret[0].(*feed.DeleteFeedResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFeed indicates an expected call of DeleteFeed.
func (mr *MockFeedMockRecorder) DeleteFeed(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFeed", reflect.TypeOf((*MockFeed)(nil).DeleteFeed), varargs...)
}

// GetCityTimeline mocks base method.
func (m *MockFeed) GetCityTimeline(arg0 context.Context, arg1 *feed.GetCityTimelineReq, arg2 ...grpc.CallOption) (*feed.GetCityTimelineResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCityTimeline", varargs...)
	ret0, _ := ret[0].(*feed.GetCityTimelineResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCityTimeline indicates an expected call of GetCityTimeline.
func (mr *MockFeedMockRecorder) GetCityTimeline(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCityTimeline", reflect.TypeOf((*MockFeed)(nil).GetCityTimeline), varargs...)
}

// GetFeed mocks base method.
func (m *MockFeed) GetFeed(arg0 context.Context, arg1 *feed.GetFeedReq, arg2 ...grpc.CallOption) (*feed.GetFeedResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFeed", varargs...)
	ret0, _ := ret[0].(*feed.GetFeedResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeed indicates an expected call of GetFeed.
func (mr *MockFeedMockRecorder) GetFeed(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeed", reflect.TypeOf((*MockFeed)(nil).GetFeed), varargs...)
}

// GetFollowTimeline mocks base method.
func (m *MockFeed) GetFollowTimeline(arg0 context.Context, arg1 *feed.GetFollowTimelineReq, arg2 ...grpc.CallOption) (*feed.GetFollowTimelineResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFollowTimeline", varargs...)
	ret0, _ := ret[0].(*feed.GetFollowTimelineResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowTimeline indicates an expected call of GetFollowTimeline.
func (mr *MockFeedMockRecorder) GetFollowTimeline(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowTimeline", reflect.TypeOf((*MockFeed)(nil).GetFollowTimeline), varargs...)
}

// GetRecommendTimeline mocks base method.
func (m *MockFeed) GetRecommendTimeline(arg0 context.Context, arg1 *feed.GetRecommendTimelineReq, arg2 ...grpc.CallOption) (*feed.GetRecommendTimelineResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetRecommendTimeline", varargs...)
	ret0, _ := ret[0].(*feed.GetRecommendTimelineResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecommendTimeline indicates an expected call of GetRecommendTimeline.
func (mr *MockFeedMockRecorder) GetRecommendTimeline(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecommendTimeline", reflect.TypeOf((*MockFeed)(nil).GetRecommendTimeline), varargs...)
}

// GetUserFeeds mocks base method.
func (m *MockFeed) GetUserFeeds(arg0 context.Context, arg1 *feed.GetUserFeedsReq, arg2 ...grpc.CallOption) (*feed.GetUserFeedsResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserFeeds", varargs...)
	ret0, _ := ret[0].(*feed.GetUserFeedsResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserFeeds indicates an expected call of GetUserFeeds.
func (mr *MockFeedMockRecorder) GetUserFeeds(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserFeeds", reflect.TypeOf((*MockFeed)(nil).GetUserFeeds), varargs...)
}

// GetFeedSource mocks base method.
func (m *MockFeed) GetFeedSource(arg0 context.Context, arg1 *feed.GetFeedSourceReq, arg2 ...grpc.CallOption) (*feed.GetFeedSourceResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFeedSource", varargs...)
	ret0, _ := ret[0].(*feed.GetFeedSourceResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeedSource indicates an expected call of GetFeedSource.
func (mr *MockFeedMockRecorder) GetFeedSource(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeedSource", reflect.TypeOf((*MockFeed)(nil).GetFeedSource), varargs...)
}

// GetFeedRequestTrace mocks base method.
func (m *MockFeed) GetFeedRequestTrace(arg0 context.Context, arg1 *feed.GetFeedRequestTraceReq, arg2 ...grpc.CallOption) (*feed.GetFeedRequestTraceResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFeedRequestTrace", varargs...)
	ret0, _ := ret[0].(*feed.GetFeedRequestTraceResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeedRequestTrace indicates an expected call of GetFeedRequestTrace.
func (mr *MockFeedMockRecorder) GetFeedRequestTrace(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeedRequestTrace", reflect.TypeOf((*MockFeed)(nil).GetFeedRequestTrace), varargs...)
}
