// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sponge-dad/feed/app/interaction/rpc/interactionClient (interfaces: Interaction)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	interaction "github.com/sponge-dad/feed/app/interaction/rpc/interaction"
	grpc "google.golang.org/grpc"
)

// MockInteraction is a mock of Interaction interface.
type MockInteraction struct {
	ctrl     *gomock.Controller
	recorder *MockInteractionMockRecorder
}

// MockInteractionMockRecorder is the mock recorder for MockInteraction.
type MockInteractionMockRecorder struct {
	mock *MockInteraction
}

// NewMockInteraction creates a new mock instance.
func NewMockInteraction(ctrl *gomock.Controller) *MockInteraction {
	mock := &MockInteraction{ctrl: ctrl}
	mock.recorder = &MockInteractionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInteraction) EXPECT() *MockInteractionMockRecorder {
	return m.recorder
}

// BatchGetFeedStats mocks base method.
func (m *MockInteraction) BatchGetFeedStats(arg0 context.Context, arg1 *interaction.BatchGetFeedStatsReq, arg2 ...grpc.CallOption) (*interaction.BatchGetFeedStatsResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchGetFeedStats", varargs...)
	ret0, _ := ret[0].(*interaction.BatchGetFeedStatsResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetFeedStats indicates an expected call of BatchGetFeedStats.
func (mr *MockInteractionMockRecorder) BatchGetFeedStats(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetFeedStats", reflect.TypeOf((*MockInteraction)(nil).BatchGetFeedStats), varargs...)
}

// BatchGetUserInteractionStatus mocks base method.
func (m *MockInteraction) BatchGetUserInteractionStatus(arg0 context.Context, arg1 *interaction.BatchGetUserInteractionStatusReq, arg2 ...grpc.CallOption) (*interaction.BatchGetUserInteractionStatusResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchGetUserInteractionStatus", varargs...)
	ret0, _ := ret[0].(*interaction.BatchGetUserInteractionStatusResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetUserInteractionStatus indicates an expected call of BatchGetUserInteractionStatus.
func (mr *MockInteractionMockRecorder) BatchGetUserInteractionStatus(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetUserInteractionStatus", reflect.TypeOf((*MockInteraction)(nil).BatchGetUserInteractionStatus), varargs...)
}

// CollectFeed mocks base method.
func (m *MockInteraction) CollectFeed(arg0 context.Context, arg1 *interaction.CollectFeedReq, arg2 ...grpc.CallOption) (*interaction.CollectFeedResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CollectFeed", varargs...)
	ret0, _ := ret[0].(*interaction.CollectFeedResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CollectFeed indicates an expected call of CollectFeed.
func (mr *MockInteractionMockRecorder) CollectFeed(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectFeed", reflect.TypeOf((*MockInteraction)(nil).CollectFeed), varargs...)
}

// GetFeedStats mocks base method.
func (m *MockInteraction) GetFeedStats(arg0 context.Context, arg1 *interaction.GetFeedStatsReq, arg2 ...grpc.CallOption) (*interaction.GetFeedStatsResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFeedStats", varargs...)
	ret0, _ := ret[0].(*interaction.GetFeedStatsResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeedStats indicates an expected call of GetFeedStats.
func (mr *MockInteractionMockRecorder) GetFeedStats(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeedStats", reflect.TypeOf((*MockInteraction)(nil).GetFeedStats), varargs...)
}

// GetUserCollectedFeeds mocks base method.
func (m *MockInteraction) GetUserCollectedFeeds(arg0 context.Context, arg1 *interaction.GetUserCollectedFeedsReq, arg2 ...grpc.CallOption) (*interaction.GetUserCollectedFeedsResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserCollectedFeeds", varargs...)
	ret0, _ := ret[0].(*interaction.GetUserCollectedFeedsResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCollectedFeeds indicates an expected call of GetUserCollectedFeeds.
func (mr *MockInteractionMockRecorder) GetUserCollectedFeeds(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCollectedFeeds", reflect.TypeOf((*MockInteraction)(nil).GetUserCollectedFeeds), varargs...)
}

// GetUserInteractionStatus mocks base method.
func (m *MockInteraction) GetUserInteractionStatus(arg0 context.Context, arg1 *interaction.GetUserInteractionStatusReq, arg2 ...grpc.CallOption) (*interaction.GetUserInteractionStatusResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserInteractionStatus", varargs...)
	ret0, _ := ret[0].(*interaction.GetUserInteractionStatusResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInteractionStatus indicates an expected call of GetUserInteractionStatus.
func (mr *MockInteractionMockRecorder) GetUserInteractionStatus(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInteractionStatus", reflect.TypeOf((*MockInteraction)(nil).GetUserInteractionStatus), varargs...)
}

// GetUserLikedFeeds mocks base method.
func (m *MockInteraction) GetUserLikedFeeds(arg0 context.Context, arg1 *interaction.GetUserLikedFeedsReq, arg2 ...grpc.CallOption) (*interaction.GetUserLikedFeedsResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserLikedFeeds", varargs...)
	ret0, _ := ret[0].(*interaction.GetUserLikedFeedsResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserLikedFeeds indicates an expected call of GetUserLikedFeeds.
func (mr *MockInteractionMockRecorder) GetUserLikedFeeds(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserLikedFeeds", reflect.TypeOf((*MockInteraction)(nil).GetUserLikedFeeds), varargs...)
}

// LikeFeed mocks base method.
func (m *MockInteraction) LikeFeed(arg0 context.Context, arg1 *interaction.LikeFeedReq, arg2 ...grpc.CallOption) (*interaction.LikeFeedResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LikeFeed", varargs...)
	ret0, _ := ret[0].(*interaction.LikeFeedResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LikeFeed indicates an expected call of LikeFeed.
func (mr *MockInteractionMockRecorder) LikeFeed(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LikeFeed", reflect.TypeOf((*MockInteraction)(nil).LikeFeed), varargs...)
}

// UncollectFeed mocks base method.
func (m *MockInteraction) UncollectFeed(arg0 context.Context, arg1 *interaction.UncollectFeedReq, arg2 ...grpc.CallOption) (*interaction.UncollectFeedResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UncollectFeed", varargs...)
	ret0, _ := ret[0].(*interaction.UncollectFeedResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UncollectFeed indicates an expected call of UncollectFeed.
func (mr *MockInteractionMockRecorder) UncollectFeed(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UncollectFeed", reflect.TypeOf((*MockInteraction)(nil).UncollectFeed), varargs...)
}

// UnlikeFeed mocks base method.
func (m *MockInteraction) UnlikeFeed(arg0 context.Context, arg1 *interaction.UnlikeFeedReq, arg2 ...grpc.CallOption) (*interaction.UnlikeFeedResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UnlikeFeed", varargs...)
	ret0, _ := ret[0].(*interaction.UnlikeFeedResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnlikeFeed indicates an expected call of UnlikeFeed.
func (mr *MockInteractionMockRecorder) UnlikeFeed(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlikeFeed", reflect.TypeOf((*MockInteraction)(nil).UnlikeFeed), varargs...)
}

// GetFeedMetrics mocks base method.
func (m *MockInteraction) GetFeedMetrics(arg0 context.Context, arg1 *interaction.GetFeedMetricsReq, arg2 ...grpc.CallOption) (*interaction.GetFeedMetricsResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFeedMetrics", varargs...)
	ret0, _ := ret[0].(*interaction.GetFeedMetricsResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeedMetrics indicates an expected call of GetFeedMetrics.
func (mr *MockInteractionMockRecorder) GetFeedMetrics(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeedMetrics", reflect.TypeOf((*MockInteraction)(nil).GetFeedMetrics), varargs...)
}

// BatchGetFeedMetrics mocks base method.
func (m *MockInteraction) BatchGetFeedMetrics(arg0 context.Context, arg1 *interaction.BatchGetFeedMetricsReq, arg2 ...grpc.CallOption) (*interaction.BatchGetFeedMetricsResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchGetFeedMetrics", varargs...)
	ret0, _ := ret[0].(*interaction.BatchGetFeedMetricsResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetFeedMetrics indicates an expected call of BatchGetFeedMetrics.
func (mr *MockInteractionMockRecorder) BatchGetFeedMetrics(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetFeedMetrics", reflect.TypeOf((*MockInteraction)(nil).BatchGetFeedMetrics), varargs...)
}

// GetCreatorMetrics mocks base method.
func (m *MockInteraction) GetCreatorMetrics(arg0 context.Context, arg1 *interaction.GetCreatorMetricsReq, arg2 ...grpc.CallOption) (*interaction.GetCreatorMetricsResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCreatorMetrics", varargs...)
	ret0, _ := ret[0].(*interaction.GetCreatorMetricsResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCreatorMetrics indicates an expected call of GetCreatorMetrics.
func (mr *MockInteractionMockRecorder) GetCreatorMetrics(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCreatorMetrics", reflect.TypeOf((*MockInteraction)(nil).GetCreatorMetrics), varargs...)
}

// GetPeerAverageMetrics mocks base method.
func (m *MockInteraction) GetPeerAverageMetrics(arg0 context.Context, arg1 *interaction.GetPeerAverageMetricsReq, arg2 ...grpc.CallOption) (*interaction.GetPeerAverageMetricsResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPeerAverageMetrics", varargs...)
	ret0, _ := ret[0].(*interaction.GetPeerAverageMetricsResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPeerAverageMetrics indicates an expected call of GetPeerAverageMetrics.
func (mr *MockInteractionMockRecorder) GetPeerAverageMetrics(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPeerAverageMetrics", reflect.TypeOf((*MockInteraction)(nil).GetPeerAverageMetrics), varargs...)
}

// GetUserInterestProfile mocks base method.
func (m *MockInteraction) GetUserInterestProfile(arg0 context.Context, arg1 *interaction.GetUserInterestProfileReq, arg2 ...grpc.CallOption) (*interaction.GetUserInterestProfileResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserInterestProfile", varargs...)
	ret0, _ := ret[0].(*interaction.GetUserInterestProfileResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInterestProfile indicates an expected call of GetUserInterestProfile.
func (mr *MockInteractionMockRecorder) GetUserInterestProfile(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInterestProfile", reflect.TypeOf((*MockInteraction)(nil).GetUserInterestProfile), varargs...)
}
