// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sponge-dad/feed/app/comment/rpc/commentClient (interfaces: Comment)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	comment "github.com/sponge-dad/feed/app/comment/rpc/comment"
	grpc "google.golang.org/grpc"
)

// MockComment is a mock of Comment interface.
type MockComment struct {
	ctrl     *gomock.Controller
	recorder *MockCommentMockRecorder
}

// MockCommentMockRecorder is the mock recorder for MockComment.
type MockCommentMockRecorder struct {
	mock *MockComment
}

// NewMockComment creates a new mock instance.
func NewMockComment(ctrl *gomock.Controller) *MockComment {
	mock := &MockComment{ctrl: ctrl}
	mock.recorder = &MockCommentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComment) EXPECT() *MockCommentMockRecorder {
	return m.recorder
}

// BatchGetCommentCount mocks base method.
func (m *MockComment) BatchGetCommentCount(arg0 context.Context, arg1 *comment.BatchGetCommentCountReq, arg2 ...grpc.CallOption) (*comment.BatchGetCommentCountResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchGetCommentCount", varargs...)
	ret0, _ := ret[0].(*comment.BatchGetCommentCountResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetCommentCount indicates an expected call of BatchGetCommentCount.
func (mr *MockCommentMockRecorder) BatchGetCommentCount(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetCommentCount", reflect.TypeOf((*MockComment)(nil).BatchGetCommentCount), varargs...)
}

// CreateComment mocks base method.
func (m *MockComment) CreateComment(arg0 context.Context, arg1 *comment.CreateCommentReq, arg2 ...grpc.CallOption) (*comment.CreateCommentResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateComment", varargs...)
	ret0, _ := ret[0].(*comment.CreateCommentResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockCommentMockRecorder) CreateComment(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockComment)(nil).CreateComment), varargs...)
}

// DeleteComment mocks base method.
func (m *MockComment) DeleteComment(arg0 context.Context, arg1 *comment.DeleteCommentReq, arg2 ...grpc.CallOption) (*comment.DeleteCommentResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteComment", varargs...)
	ret0, _ := ret[0].(*comment.DeleteCommentResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteComment indicates an expected call of DeleteComment.
func (mr *MockCommentMockRecorder) DeleteComment(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComment", reflect.TypeOf((*MockComment)(nil).DeleteComment), varargs...)
}

// GetCommentCount mocks base method.
func (m *MockComment) GetCommentCount(arg0 context.Context, arg1 *comment.GetCommentCountReq, arg2 ...grpc.CallOption) (*comment.GetCommentCountResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCommentCount", varargs...)
	ret0, _ := ret[0].(*comment.GetCommentCountResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommentCount indicates an expected call of GetCommentCount.
func (mr *MockCommentMockRecorder) GetCommentCount(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentCount", reflect.TypeOf((*MockComment)(nil).GetCommentCount), varargs...)
}

// GetHotComments mocks base method.
func (m *MockComment) GetHotComments(arg0 context.Context, arg1 *comment.GetHotCommentsReq, arg2 ...grpc.CallOption) (*comment.GetHotCommentsResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetHotComments", varargs...)
	ret0, _ := ret[0].(*comment.GetHotCommentsResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHotComments indicates an expected call of GetHotComments.
func (mr *MockCommentMockRecorder) GetHotComments(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHotComments", reflect.TypeOf((*MockComment)(nil).GetHotComments), varargs...)
}

// ListComments mocks base method.
func (m *MockComment) ListComments(arg0 context.Context, arg1 *comment.ListCommentsReq, arg2 ...grpc.CallOption) (*comment.ListCommentsResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListComments", varargs...)
	ret0, _ := ret[0].(*comment.ListCommentsResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListComments indicates an expected call of ListComments.
func (mr *MockCommentMockRecorder) ListComments(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListComments", reflect.TypeOf((*MockComment)(nil).ListComments), varargs...)
}

// ListReplies mocks base method.
func (m *MockComment) ListReplies(arg0 context.Context, arg1 *comment.ListRepliesReq, arg2 ...grpc.CallOption) (*comment.ListRepliesResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListReplies", varargs...)
	ret0, _ := ret[0].(*comment.ListRepliesResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReplies indicates an expected call of ListReplies.
func (mr *MockCommentMockRecorder) ListReplies(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReplies", reflect.TypeOf((*MockComment)(nil).ListReplies), varargs...)
}
