// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: interaction.proto

package interactionClient

import (
	"context"

	"github.com/sponge-dad/feed/app/interaction/rpc/interaction"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetFeedMetricsReq            = interaction.BatchGetFeedMetricsReq
	BatchGetFeedMetricsResp           = interaction.BatchGetFeedMetricsResp
	BatchGetFeedStatsReq              = interaction.BatchGetFeedStatsReq
	BatchGetFeedStatsResp             = interaction.BatchGetFeedStatsResp
	BatchGetUserInteractionStatusReq  = interaction.BatchGetUserInteractionStatusReq
	BatchGetUserInteractionStatusResp = interaction.BatchGetUserInteractionStatusResp
	CollectFeedReq                    = interaction.CollectFeedReq
	CollectFeedResp                   = interaction.CollectFeedResp
	FeedMetrics                       = interaction.FeedMetrics
	FeedMetricsRate                   = interaction.FeedMetricsRate
	FeedMetricsRaw                    = interaction.FeedMetricsRaw
	FeedStats                         = interaction.FeedStats
	GetCreatorMetricsReq              = interaction.GetCreatorMetricsReq
	GetCreatorMetricsResp             = interaction.GetCreatorMetricsResp
	GetFeedMetricsReq                 = interaction.GetFeedMetricsReq
	GetFeedMetricsResp                = interaction.GetFeedMetricsResp
	GetFeedStatsReq                   = interaction.GetFeedStatsReq
	GetFeedStatsResp                  = interaction.GetFeedStatsResp
	GetPeerAverageMetricsReq          = interaction.GetPeerAverageMetricsReq
	GetPeerAverageMetricsResp         = interaction.GetPeerAverageMetricsResp
	GetUserCollectedFeedsReq          = interaction.GetUserCollectedFeedsReq
	GetUserCollectedFeedsResp         = interaction.GetUserCollectedFeedsResp
	GetUserInteractionStatusReq       = interaction.GetUserInteractionStatusReq
	GetUserInteractionStatusResp      = interaction.GetUserInteractionStatusResp
	GetUserInterestProfileReq         = interaction.GetUserInterestProfileReq
	GetUserInterestProfileResp        = interaction.GetUserInterestProfileResp
	GetUserLikedFeedsReq              = interaction.GetUserLikedFeedsReq
	GetUserLikedFeedsResp             = interaction.GetUserLikedFeedsResp
	InterestItem                      = interaction.InterestItem
	LikeFeedReq                       = interaction.LikeFeedReq
	LikeFeedResp                      = interaction.LikeFeedResp
	PeerRateDistribution              = interaction.PeerRateDistribution
	Percentile                        = interaction.Percentile
	UncollectFeedReq                  = interaction.UncollectFeedReq
	UncollectFeedResp                 = interaction.UncollectFeedResp
	UnlikeFeedReq                     = interaction.UnlikeFeedReq
	UnlikeFeedResp                    = interaction.UnlikeFeedResp
	UserInteractionStatus             = interaction.UserInteractionStatus

	Interaction interface {
		// 动作类
		LikeFeed(ctx context.Context, in *LikeFeedReq, opts ...grpc.CallOption) (*LikeFeedResp, error)
		UnlikeFeed(ctx context.Context, in *UnlikeFeedReq, opts ...grpc.CallOption) (*UnlikeFeedResp, error)
		CollectFeed(ctx context.Context, in *CollectFeedReq, opts ...grpc.CallOption) (*CollectFeedResp, error)
		UncollectFeed(ctx context.Context, in *UncollectFeedReq, opts ...grpc.CallOption) (*UncollectFeedResp, error)
		// 查询类
		GetFeedStats(ctx context.Context, in *GetFeedStatsReq, opts ...grpc.CallOption) (*GetFeedStatsResp, error)
		BatchGetFeedStats(ctx context.Context, in *BatchGetFeedStatsReq, opts ...grpc.CallOption) (*BatchGetFeedStatsResp, error)
		GetUserInteractionStatus(ctx context.Context, in *GetUserInteractionStatusReq, opts ...grpc.CallOption) (*GetUserInteractionStatusResp, error)
		BatchGetUserInteractionStatus(ctx context.Context, in *BatchGetUserInteractionStatusReq, opts ...grpc.CallOption) (*BatchGetUserInteractionStatusResp, error)
		// 列表类
		GetUserLikedFeeds(ctx context.Context, in *GetUserLikedFeedsReq, opts ...grpc.CallOption) (*GetUserLikedFeedsResp, error)
		GetUserCollectedFeeds(ctx context.Context, in *GetUserCollectedFeedsReq, opts ...grpc.CallOption) (*GetUserCollectedFeedsResp, error)
		// 创作者数据（US5）
		GetFeedMetrics(ctx context.Context, in *GetFeedMetricsReq, opts ...grpc.CallOption) (*GetFeedMetricsResp, error)
		BatchGetFeedMetrics(ctx context.Context, in *BatchGetFeedMetricsReq, opts ...grpc.CallOption) (*BatchGetFeedMetricsResp, error)
		GetCreatorMetrics(ctx context.Context, in *GetCreatorMetricsReq, opts ...grpc.CallOption) (*GetCreatorMetricsResp, error)
		GetPeerAverageMetrics(ctx context.Context, in *GetPeerAverageMetricsReq, opts ...grpc.CallOption) (*GetPeerAverageMetricsResp, error)
		GetUserInterestProfile(ctx context.Context, in *GetUserInterestProfileReq, opts ...grpc.CallOption) (*GetUserInterestProfileResp, error)
	}

	defaultInteraction struct {
		cli zrpc.Client
	}
)

func NewInteraction(cli zrpc.Client) Interaction {
	return &defaultInteraction{
		cli: cli,
	}
}

// 动作类
func (m *defaultInteraction) LikeFeed(ctx context.Context, in *LikeFeedReq, opts ...grpc.CallOption) (*LikeFeedResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.LikeFeed(ctx, in, opts...)
}

func (m *defaultInteraction) UnlikeFeed(ctx context.Context, in *UnlikeFeedReq, opts ...grpc.CallOption) (*UnlikeFeedResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.UnlikeFeed(ctx, in, opts...)
}

func (m *defaultInteraction) CollectFeed(ctx context.Context, in *CollectFeedReq, opts ...grpc.CallOption) (*CollectFeedResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.CollectFeed(ctx, in, opts...)
}

func (m *defaultInteraction) UncollectFeed(ctx context.Context, in *UncollectFeedReq, opts ...grpc.CallOption) (*UncollectFeedResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.UncollectFeed(ctx, in, opts...)
}

// 查询类
func (m *defaultInteraction) GetFeedStats(ctx context.Context, in *GetFeedStatsReq, opts ...grpc.CallOption) (*GetFeedStatsResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.GetFeedStats(ctx, in, opts...)
}

func (m *defaultInteraction) BatchGetFeedStats(ctx context.Context, in *BatchGetFeedStatsReq, opts ...grpc.CallOption) (*BatchGetFeedStatsResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.BatchGetFeedStats(ctx, in, opts...)
}

func (m *defaultInteraction) GetUserInteractionStatus(ctx context.Context, in *GetUserInteractionStatusReq, opts ...grpc.CallOption) (*GetUserInteractionStatusResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.GetUserInteractionStatus(ctx, in, opts...)
}

func (m *defaultInteraction) BatchGetUserInteractionStatus(ctx context.Context, in *BatchGetUserInteractionStatusReq, opts ...grpc.CallOption) (*BatchGetUserInteractionStatusResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.BatchGetUserInteractionStatus(ctx, in, opts...)
}

// 列表类
func (m *defaultInteraction) GetUserLikedFeeds(ctx context.Context, in *GetUserLikedFeedsReq, opts ...grpc.CallOption) (*GetUserLikedFeedsResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.GetUserLikedFeeds(ctx, in, opts...)
}

func (m *defaultInteraction) GetUserCollectedFeeds(ctx context.Context, in *GetUserCollectedFeedsReq, opts ...grpc.CallOption) (*GetUserCollectedFeedsResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.GetUserCollectedFeeds(ctx, in, opts...)
}

// 创作者数据（US5）
func (m *defaultInteraction) GetFeedMetrics(ctx context.Context, in *GetFeedMetricsReq, opts ...grpc.CallOption) (*GetFeedMetricsResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.GetFeedMetrics(ctx, in, opts...)
}

func (m *defaultInteraction) BatchGetFeedMetrics(ctx context.Context, in *BatchGetFeedMetricsReq, opts ...grpc.CallOption) (*BatchGetFeedMetricsResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.BatchGetFeedMetrics(ctx, in, opts...)
}

func (m *defaultInteraction) GetCreatorMetrics(ctx context.Context, in *GetCreatorMetricsReq, opts ...grpc.CallOption) (*GetCreatorMetricsResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.GetCreatorMetrics(ctx, in, opts...)
}

func (m *defaultInteraction) GetPeerAverageMetrics(ctx context.Context, in *GetPeerAverageMetricsReq, opts ...grpc.CallOption) (*GetPeerAverageMetricsResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.GetPeerAverageMetrics(ctx, in, opts...)
}

func (m *defaultInteraction) GetUserInterestProfile(ctx context.Context, in *GetUserInterestProfileReq, opts ...grpc.CallOption) (*GetUserInterestProfileResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.GetUserInterestProfile(ctx, in, opts...)
}
