// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"github.com/sponge-dad/feed/app/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/users/login",
				Handler: loginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/register",
				Handler: registerHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/upload/token",
				Handler: uploadTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users/:userId",
				Handler: getUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users/me",
				Handler: getMeHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/users/me",
				Handler: updateMeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
