// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	feedsFieldNames          = builder.RawFieldNames(&Feeds{})
	feedsRows                = strings.Join(feedsFieldNames, ",")
	feedsRowsExpectAutoSet   = strings.Join(stringx.Remove(feedsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	feedsRowsWithPlaceHolder = strings.Join(stringx.Remove(feedsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheFeedsIdPrefix = "cache:feeds:id:"
)

type (
	feedsModel interface {
		Insert(ctx context.Context, data *Feeds) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Feeds, error)
		Update(ctx context.Context, data *Feeds) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultFeedsModel struct {
		sqlc.CachedConn
		table string
	}

	Feeds struct {
		Id           uint64         `db:"id"`            // Snowflake ID，应用层生成
		UserId       uint64         `db:"user_id"`       // 作者ID
		FeedType     int64          `db:"feed_type"`     // 动态类型，1：图文，2：视频
		Title        string         `db:"title"`         // 标题/主题
		Description  string         `db:"description"`   // 正文/描述
		MediaUrls    sql.NullString `db:"media_urls"`    // 媒体资源 ["url1","url2"]
		CoverUrl     string         `db:"cover_url"`     // 视频封面图
		CityCode     string         `db:"city_code"`     // 发布时IP城市编码
		CityName     string         `db:"city_name"`     // 发布时IP城市名
		IpLocation   string         `db:"ip_location"`   // IP属地，如"广东"
		Status       int64          `db:"status"`        // 1:正常 2:已删除 3:审核中
		IsVipFeed    int64          `db:"is_vip_feed"`   // 0:普通 1:大V发帖
		LikeCount    uint64         `db:"like_count"`    // 点赞数
		CommentCount uint64         `db:"comment_count"` // 评论数
		CollectCount uint64         `db:"collect_count"` // 收藏数
		CreatedAt    time.Time      `db:"created_at"`    // 发布时间
		UpdatedAt    time.Time      `db:"updated_at"`    // 最近更新时间
	}
)

func newFeedsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFeedsModel {
	return &defaultFeedsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`feeds`",
	}
}

func (m *defaultFeedsModel) Delete(ctx context.Context, id uint64) error {
	feedsIdKey := fmt.Sprintf("%s%v", cacheFeedsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, feedsIdKey)
	return err
}

func (m *defaultFeedsModel) FindOne(ctx context.Context, id uint64) (*Feeds, error) {
	feedsIdKey := fmt.Sprintf("%s%v", cacheFeedsIdPrefix, id)
	var resp Feeds
	err := m.QueryRowCtx(ctx, &resp, feedsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", feedsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFeedsModel) Insert(ctx context.Context, data *Feeds) (sql.Result, error) {
	feedsIdKey := fmt.Sprintf("%s%v", cacheFeedsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, feedsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.UserId, data.FeedType, data.Title, data.Description, data.MediaUrls, data.CoverUrl, data.CityCode, data.CityName, data.IpLocation, data.Status, data.IsVipFeed, data.LikeCount, data.CommentCount, data.CollectCount)
	}, feedsIdKey)
	return ret, err
}

func (m *defaultFeedsModel) Update(ctx context.Context, data *Feeds) error {
	feedsIdKey := fmt.Sprintf("%s%v", cacheFeedsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, feedsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.FeedType, data.Title, data.Description, data.MediaUrls, data.CoverUrl, data.CityCode, data.CityName, data.IpLocation, data.Status, data.IsVipFeed, data.LikeCount, data.CommentCount, data.CollectCount, data.Id)
	}, feedsIdKey)
	return err
}

func (m *defaultFeedsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheFeedsIdPrefix, primary)
}

func (m *defaultFeedsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", feedsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFeedsModel) tableName() string {
	return m.table
}
