// feed.proto
//
// 职责：Feed 服务内部 gRPC 接口定义。
// 服务范围：帖子发布、帖子查询、推荐/关注/同城三种流、批量查询、个人主页列表。
// 主要接口：CreateFeed, DeleteFeed, GetFeed, BatchGetFeeds,
//          GetRecommendTimeline, GetFollowTimeline, GetCityTimeline, GetUserFeeds。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: api/proto/feed/feed.proto

package feed

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FeedType 帖子类型
type FeedType int32

const (
	FeedType_FEED_TYPE_UNKNOWN FeedType = 0 // 未知，proto3 默认值
	FeedType_FEED_TYPE_IMAGE   FeedType = 1 // 图文
	FeedType_FEED_TYPE_VIDEO   FeedType = 2 // 视频
)

// Enum value maps for FeedType.
var (
	FeedType_name = map[int32]string{
		0: "FEED_TYPE_UNKNOWN",
		1: "FEED_TYPE_IMAGE",
		2: "FEED_TYPE_VIDEO",
	}
	FeedType_value = map[string]int32{
		"FEED_TYPE_UNKNOWN": 0,
		"FEED_TYPE_IMAGE":   1,
		"FEED_TYPE_VIDEO":   2,
	}
)

func (x FeedType) Enum() *FeedType {
	p := new(FeedType)
	*p = x
	return p
}

func (x FeedType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeedType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_feed_feed_proto_enumTypes[0].Descriptor()
}

func (FeedType) Type() protoreflect.EnumType {
	return &file_api_proto_feed_feed_proto_enumTypes[0]
}

func (x FeedType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeedType.Descriptor instead.
func (FeedType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_feed_feed_proto_rawDescGZIP(), []int{0}
}

// FeedStatus 帖子状态
type FeedStatus int32

const (
	FeedStatus_FEED_STATUS_UNKNOWN  FeedStatus = 0 // 未知
	FeedStatus_FEED_STATUS_NORMAL   FeedStatus = 1 // 正常
	FeedStatus_FEED_STATUS_DELETED  FeedStatus = 2 // 已删除（软删除）
	FeedStatus_FEED_STATUS_AUDITING FeedStatus = 3 // 审核中
)

// Enum value maps for FeedStatus.
var (
	FeedStatus_name = map[int32]string{
		0: "FEED_STATUS_UNKNOWN",
		1: "FEED_STATUS_NORMAL",
		2: "FEED_STATUS_DELETED",
		3: "FEED_STATUS_AUDITING",
	}
	FeedStatus_value = map[string]int32{
		"FEED_STATUS_UNKNOWN":  0,
		"FEED_STATUS_NORMAL":   1,
		"FEED_STATUS_DELETED":  2,
		"FEED_STATUS_AUDITING": 3,
	}
)

func (x FeedStatus) Enum() *FeedStatus {
	p := new(FeedStatus)
	*p = x
	return p
}

func (x FeedStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeedStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_feed_feed_proto_enumTypes[1].Descriptor()
}

func (FeedStatus) Type() protoreflect.EnumType {
	return &file_api_proto_feed_feed_proto_enumTypes[1]
}

func (x FeedStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeedStatus.Descriptor instead.
func (FeedStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_feed_feed_proto_rawDescGZIP(), []int{1}
}

// FeedInfo 帖子完整信息
type FeedInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedId        int64                  `protobuf:"varint,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`                    // 帖子 ID，Snowflake 全局唯一
	AuthorId      int64                  `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`              // 作者用户 ID
	FeedType      int32                  `protobuf:"varint,3,opt,name=feed_type,json=feedType,proto3" json:"feed_type,omitempty"`              // 帖子类型：1=图文，2=视频
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`                                     // 标题/话题
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`                         // 正文/描述
	MediaUrls     []string               `protobuf:"bytes,6,rep,name=media_urls,json=mediaUrls,proto3" json:"media_urls,omitempty"`            // 媒体资源 URL 列表
	CoverUrl      string                 `protobuf:"bytes,7,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`               // 封面图 URL，视频必填
	CityCode      string                 `protobuf:"bytes,8,opt,name=city_code,json=cityCode,proto3" json:"city_code,omitempty"`               // 发布城市代码，如 "440300"
	CityName      string                 `protobuf:"bytes,9,opt,name=city_name,json=cityName,proto3" json:"city_name,omitempty"`               // 发布城市名称，如 "深圳"
	IpLocation    string                 `protobuf:"bytes,10,opt,name=ip_location,json=ipLocation,proto3" json:"ip_location,omitempty"`        // IP 属地，如 "广东"
	Status        int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`                                 // 帖子状态：1=正常，2=已删除，3=审核中
	IsVipFeed     bool                   `protobuf:"varint,12,opt,name=is_vip_feed,json=isVipFeed,proto3" json:"is_vip_feed,omitempty"`        // 是否大V发帖
	LikeCount     int64                  `protobuf:"varint,13,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`          // 点赞数（Feed 表冗余，展示用）
	CommentCount  int64                  `protobuf:"varint,14,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"` // 评论数（Feed 表冗余，展示用）
	CollectCount  int64                  `protobuf:"varint,15,opt,name=collect_count,json=collectCount,proto3" json:"collect_count,omitempty"` // 收藏数（Feed 表冗余，展示用）
	CreatedAt     int64                  `protobuf:"varint,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`          // 发布时间，毫秒级 Unix 时间戳
	UpdatedAt     int64                  `protobuf:"varint,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`          // 更新时间，毫秒级 Unix 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedInfo) Reset() {
	*x = FeedInfo{}
	mi := &file_api_proto_feed_feed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedInfo) ProtoMessage() {}

func (x *FeedInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feed_feed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedInfo.ProtoReflect.Descriptor instead.
func (*FeedInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_feed_feed_proto_rawDescGZIP(), []int{0}
}

func (x *FeedInfo) GetFeedId() int64 {
	if x != nil {
		return x.FeedId
	}
	return 0
}

func (x *FeedInfo) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *FeedInfo) GetFeedType() int32 {
	if x != nil {
		return x.FeedType
	}
	return 0
}

func (x *FeedInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FeedInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FeedInfo) GetMediaUrls() []string {
	if x != nil {
		return x.MediaUrls
	}
	return nil
}

func (x *FeedInfo) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *FeedInfo) GetCityCode() string {
	if x != nil {
		return x.CityCode
	}
	return ""
}

func (x *FeedInfo) GetCityName() string {
	if x != nil {
		return x.CityName
	}
	return ""
}

func (x *FeedInfo) GetIpLocation() string {
	if x != nil {
		return x.IpLocation
	}
	return ""
}

func (x *FeedInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FeedInfo) GetIsVipFeed() bool {
	if x != nil {
		return x.IsVipFeed
	}
	return false
}

func (x *FeedInfo) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *FeedInfo) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *FeedInfo) GetCollectCount() int64 {
	if x != nil {
		return x.CollectCount
	}
	return 0
}

func (x *FeedInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FeedInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// FeedBrief 帖子卡片（列表用），字段比 FeedInfo 精简
type FeedBrief struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedId        int64                  `protobuf:"varint,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`                   // 帖子 ID
	AuthorId      int64                  `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`             // 作者用户 ID
	FeedType      int32                  `protobuf:"varint,3,opt,name=feed_type,json=feedType,proto3" json:"feed_type,omitempty"`             // 帖子类型
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`                                    // 标题
	CoverUrl      string                 `protobuf:"bytes,5,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`              // 封面图
	CityCode      string                 `protobuf:"bytes,6,opt,name=city_code,json=cityCode,proto3" json:"city_code,omitempty"`              // 城市代码
	LikeCount     int64                  `protobuf:"varint,7,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`          // 点赞数
	CommentCount  int64                  `protobuf:"varint,8,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"` // 评论数
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`          // 发布时间，毫秒级 Unix 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedBrief) Reset() {
	*x = FeedBrief{}
	mi := &file_api_proto_feed_feed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedBrief) ProtoMessage() {}

func (x *FeedBrief) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feed_feed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedBrief.ProtoReflect.Descriptor instead.
func (*FeedBrief) Descriptor() ([]byte, []int) {
	return file_api_proto_feed_feed_proto_rawDescGZIP(), []int{1}
}

func (x *FeedBrief) GetFeedId() int64 {
	if x != nil {
		return x.FeedId
	}
	return 0
}

func (x *FeedBrief) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *FeedBrief) GetFeedType() int32 {
	if x != nil {
		return x.FeedType
	}
	return 0
}

func (x *FeedBrief) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FeedBrief) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *FeedBrief) GetCityCode() string {
	if x != nil {
		return x.CityCode
	}
	return ""
}

func (x *FeedBrief) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *FeedBrief) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *FeedBrief) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// PageInfo 分页信息
type PageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 当前页码，从 1 开始
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页条数
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`                       // 总条数（-1 表示未统计）
	HasMore       bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`    // 是否还有更多
	Cursor        string                 `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`                      // 下一页游标，空字符串表示无下一页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_api_proto_feed_feed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feed_feed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_feed_feed_proto_rawDescGZIP(), []int{2}
}

func (x *PageInfo) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageInfo) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageInfo) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageInfo) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *PageInfo) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type CreateFeedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      int64                  `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`      // 作者用户 ID，从 RPC metadata / JWT 中提取
	FeedType      int32                  `protobuf:"varint,2,opt,name=feed_type,json=feedType,proto3" json:"feed_type,omitempty"`      // 帖子类型：1=图文，2=视频
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                             // 标题/话题，可选
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                 // 正文/描述
	MediaUrls     []string               `protobuf:"bytes,5,rep,name=media_urls,json=mediaUrls,proto3" json:"media_urls,omitempty"`    // 媒体资源 URL 列表，图文至少 1 张
	CoverUrl      string                 `protobuf:"bytes,6,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`       // 封面图 URL，视频必填
	CityCode      string                 `protobuf:"bytes,7,opt,name=city_code,json=cityCode,proto3" json:"city_code,omitempty"`       // 发布城市代码，网关根据 IP 定位后传入
	CityName      string                 `protobuf:"bytes,8,opt,name=city_name,json=cityName,proto3" json:"city_name,omitempty"`       // 发布城市名称
	IpLocation    string                 `protobuf:"bytes,9,opt,name=ip_location,json=ipLocation,proto3" json:"ip_location,omitempty"` // IP 属地
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFeedReq) Reset() {
	*x = CreateFeedReq{}
	mi := &file_api_proto_feed_feed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFeedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFeedReq) ProtoMessage() {}

func (x *CreateFeedReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feed_feed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFeedReq.ProtoReflect.Descriptor instead.
func (*CreateFeedReq) Descriptor() ([]byte, []int) {
	return file_api_proto_feed_feed_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFeedReq) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *CreateFeedReq) GetFeedType() int32 {
	if x != nil {
		return x.FeedType
	}
	return 0
}

func (x *CreateFeedReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateFeedReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateFeedReq) GetMediaUrls() []string {
	if x != nil {
		return x.MediaUrls
	}
	return nil
}

func (x *CreateFeedReq) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *CreateFeedReq) GetCityCode() string {
	if x != nil {
		return x.CityCode
	}
	return ""
}

func (x *CreateFeedReq) GetCityName() string {
	if x != nil {
		return x.CityName
	}
	return ""
}

func (x *CreateFeedReq) GetIpLocation() string {
	if x != nil {
		return x.IpLocation
	}
	return ""
}

type CreateFeedResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feed          *FeedInfo              `protobuf:"bytes,1,opt,name=feed,proto3" json:"feed,omitempty"` // 创建成功的帖子详情
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFeedResp) Reset() {
	*x = CreateFeedResp{}
	mi := &file_api_proto_feed_feed_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFeedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFeedResp) ProtoMessage() {}

func (x *CreateFeedResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feed_feed_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFeedResp.ProtoReflect.Descriptor instead.
func (*CreateFeedResp) Descriptor() ([]byte, []int) {
	return file_api_proto_feed_feed_proto_rawDescGZIP(), []int{4}
}

func (x *CreateFeedResp) GetFeed() *FeedInfo {
	if x != nil {
		return x.Feed
	}
	return nil
}

type DeleteFeedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedId        int64                  `protobuf:"varint,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"` // 要删除的帖子 ID
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 当前操作者 ID，用于权限校验
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFeedReq) Reset() {
	*x = DeleteFeedReq{}
	mi := &file_api_proto_feed_feed_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFeedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFeedReq) ProtoMessage() {}

func (x *DeleteFeedReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feed_feed_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFeedReq.ProtoReflect.Descriptor instead.
func (*DeleteFeedReq) Descriptor() ([]byte, []int) {
	return file_api_proto_feed_feed_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteFeedReq) GetFeedId() int64 {
	if x != nil {
		return x.FeedId
	}
	return 0
}

func (x *DeleteFeedReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteFeedResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否删除成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFeedResp) Reset() {
	*x = DeleteFeedResp{}
	mi := &file_api_proto_feed_feed_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFeedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFeedResp) ProtoMessage() {}

func (x *DeleteFeedResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feed_feed_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFeedResp.ProtoReflect.Descriptor instead.
func (*DeleteFeedResp) Descriptor() ([]byte, []int) {
	return file_api_proto_feed_feed_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteFeedResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetFeedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedId        int64                  `protobuf:"varint,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"` // 帖子 ID
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 当前查看者 ID，预留用于权限/状态判断
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedReq) Reset() {
	*x = GetFeedReq{}
	mi := &file_api_proto_feed_feed_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedReq) ProtoMessage() {}

func (x *GetFeedReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feed_feed_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedReq.ProtoReflect.Descriptor instead.
func (*GetFeedReq) Descriptor() ([]byte, []int) {
	return file_api_proto_feed_feed_proto_rawDescGZIP(), []int{7}
}

func (x *GetFeedReq) GetFeedId() int64 {
	if x != nil {
		return x.FeedId
	}
	return 0
}

func (x *GetFeedReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetFeedResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feed          *FeedInfo              `protobuf:"bytes,1,opt,name=feed,proto3" json:"feed,omitempty"` // 帖子详情
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedResp) Reset() {
	*x = GetFeedResp{}
	mi := &file_api_proto_feed_feed_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedResp) ProtoMessage() {}

func (x *GetFeedResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feed_feed_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedResp.ProtoReflect.Descriptor instead.
func (*GetFeedResp) Descriptor() ([]byte, []int) {
	return file_api_proto_feed_feed_proto_rawDescGZIP(), []int{8}
}

func (x *GetFeedResp) GetFeed() *FeedInfo {
	if x != nil {
		return x.Feed
	}
	return nil
}

type BatchGetFeedsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedIds       []int64                `protobuf:"varint,1,rep,packed,name=feed_ids,json=feedIds,proto3" json:"feed_ids,omitempty"` // 帖子 ID 列表，建议单次不超过 100 个
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`           // 当前查看者 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetFeedsReq) Reset() {
	*x = BatchGetFeedsReq{}
	mi := &file_api_proto_feed_feed_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetFeedsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetFeedsReq) ProtoMessage() {}

func (x *BatchGetFeedsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feed_feed_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetFeedsReq.ProtoReflect.Descriptor instead.
func (*BatchGetFeedsReq) Descriptor() ([]byte, []int) {
	return file_api_proto_feed_feed_proto_rawDescGZIP(), []int{9}
}

func (x *BatchGetFeedsReq) GetFeedIds() []int64 {
	if x != nil {
		return x.FeedIds
	}
	return nil
}

func (x *BatchGetFeedsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type BatchGetFeedsResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key: feed_id, value: 帖子详情；找不到的 feed_id 不包含在 map 中
	Feeds         map[int64]*FeedInfo `protobuf:"bytes,1,rep,name=feeds,proto3" json:"feeds,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetFeedsResp) Reset() {
	*x = BatchGetFeedsResp{}
	mi := &file_api_proto_feed_feed_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetFeedsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetFeedsResp) ProtoMessage() {}

func (x *BatchGetFeedsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feed_feed_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetFeedsResp.ProtoReflect.Descriptor instead.
func (*BatchGetFeedsResp) Descriptor() ([]byte, []int) {
	return file_api_proto_feed_feed_proto_rawDescGZIP(), []int{10}
}

func (x *BatchGetFeedsResp) GetFeeds() map[int64]*FeedInfo {
	if x != nil {
		return x.Feeds
	}
	return nil
}

type GetRecommendTimelineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 当前用户 ID，用于个性化过滤（V1 可只用于日志）
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                         // 页码，从 1 开始
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页条数，默认 10，最大 50
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendTimelineReq) Reset() {
	*x = GetRecommendTimelineReq{}
	mi := &file_api_proto_feed_feed_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendTimelineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendTimelineReq) ProtoMessage() {}

func (x *GetRecommendTimelineReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feed_feed_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendTimelineReq.ProtoReflect.Descriptor instead.
func (*GetRecommendTimelineReq) Descriptor() ([]byte, []int) {
	return file_api_proto_feed_feed_proto_rawDescGZIP(), []int{11}
}

func (x *GetRecommendTimelineReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetRecommendTimelineReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRecommendTimelineReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetRecommendTimelineResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feeds         []*FeedBrief           `protobuf:"bytes,1,rep,name=feeds,proto3" json:"feeds,omitempty"` // 推荐流帖子列表
	Page          *PageInfo              `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`   // 分页信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendTimelineResp) Reset() {
	*x = GetRecommendTimelineResp{}
	mi := &file_api_proto_feed_feed_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendTimelineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendTimelineResp) ProtoMessage() {}

func (x *GetRecommendTimelineResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feed_feed_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendTimelineResp.ProtoReflect.Descriptor instead.
func (*GetRecommendTimelineResp) Descriptor() ([]byte, []int) {
	return file_api_proto_feed_feed_proto_rawDescGZIP(), []int{12}
}

func (x *GetRecommendTimelineResp) GetFeeds() []*FeedBrief {
	if x != nil {
		return x.Feeds
	}
	return nil
}

func (x *GetRecommendTimelineResp) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetFollowTimelineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 当前用户 ID
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`                      // 游标，空字符串表示第一页
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页条数，默认 10，最大 50
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowTimelineReq) Reset() {
	*x = GetFollowTimelineReq{}
	mi := &file_api_proto_feed_feed_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowTimelineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowTimelineReq) ProtoMessage() {}

func (x *GetFollowTimelineReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feed_feed_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowTimelineReq.ProtoReflect.Descriptor instead.
func (*GetFollowTimelineReq) Descriptor() ([]byte, []int) {
	return file_api_proto_feed_feed_proto_rawDescGZIP(), []int{13}
}

func (x *GetFollowTimelineReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFollowTimelineReq) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *GetFollowTimelineReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetFollowTimelineResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feeds         []*FeedBrief           `protobuf:"bytes,1,rep,name=feeds,proto3" json:"feeds,omitempty"` // 关注流帖子列表
	Page          *PageInfo              `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`   // 分页信息，包含下一页 cursor
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowTimelineResp) Reset() {
	*x = GetFollowTimelineResp{}
	mi := &file_api_proto_feed_feed_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowTimelineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowTimelineResp) ProtoMessage() {}

func (x *GetFollowTimelineResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feed_feed_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowTimelineResp.ProtoReflect.Descriptor instead.
func (*GetFollowTimelineResp) Descriptor() ([]byte, []int) {
	return file_api_proto_feed_feed_proto_rawDescGZIP(), []int{14}
}

func (x *GetFollowTimelineResp) GetFeeds() []*FeedBrief {
	if x != nil {
		return x.Feeds
	}
	return nil
}

func (x *GetFollowTimelineResp) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetCityTimelineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 当前用户 ID
	CityCode      string                 `protobuf:"bytes,2,opt,name=city_code,json=cityCode,proto3" json:"city_code,omitempty"`  // 城市代码，为空时从 user_id 获取
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                         // 页码，从 1 开始
	PageSize      int64                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页条数，默认 10，最大 50
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCityTimelineReq) Reset() {
	*x = GetCityTimelineReq{}
	mi := &file_api_proto_feed_feed_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCityTimelineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCityTimelineReq) ProtoMessage() {}

func (x *GetCityTimelineReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feed_feed_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCityTimelineReq.ProtoReflect.Descriptor instead.
func (*GetCityTimelineReq) Descriptor() ([]byte, []int) {
	return file_api_proto_feed_feed_proto_rawDescGZIP(), []int{15}
}

func (x *GetCityTimelineReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetCityTimelineReq) GetCityCode() string {
	if x != nil {
		return x.CityCode
	}
	return ""
}

func (x *GetCityTimelineReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCityTimelineReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetCityTimelineResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feeds         []*FeedBrief           `protobuf:"bytes,1,rep,name=feeds,proto3" json:"feeds,omitempty"` // 同城流帖子列表
	Page          *PageInfo              `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`   // 分页信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCityTimelineResp) Reset() {
	*x = GetCityTimelineResp{}
	mi := &file_api_proto_feed_feed_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCityTimelineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCityTimelineResp) ProtoMessage() {}

func (x *GetCityTimelineResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feed_feed_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCityTimelineResp.ProtoReflect.Descriptor instead.
func (*GetCityTimelineResp) Descriptor() ([]byte, []int) {
	return file_api_proto_feed_feed_proto_rawDescGZIP(), []int{16}
}

func (x *GetCityTimelineResp) GetFeeds() []*FeedBrief {
	if x != nil {
		return x.Feeds
	}
	return nil
}

func (x *GetCityTimelineResp) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetUserFeedsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 要查询的用户 ID
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                         // 页码，从 1 开始
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页条数，默认 10，最大 50
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFeedsReq) Reset() {
	*x = GetUserFeedsReq{}
	mi := &file_api_proto_feed_feed_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFeedsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFeedsReq) ProtoMessage() {}

func (x *GetUserFeedsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feed_feed_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFeedsReq.ProtoReflect.Descriptor instead.
func (*GetUserFeedsReq) Descriptor() ([]byte, []int) {
	return file_api_proto_feed_feed_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserFeedsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserFeedsReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserFeedsReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetUserFeedsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feeds         []*FeedBrief           `protobuf:"bytes,1,rep,name=feeds,proto3" json:"feeds,omitempty"` // 该用户发布的帖子列表
	Page          *PageInfo              `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`   // 分页信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFeedsResp) Reset() {
	*x = GetUserFeedsResp{}
	mi := &file_api_proto_feed_feed_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFeedsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFeedsResp) ProtoMessage() {}

func (x *GetUserFeedsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feed_feed_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFeedsResp.ProtoReflect.Descriptor instead.
func (*GetUserFeedsResp) Descriptor() ([]byte, []int) {
	return file_api_proto_feed_feed_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserFeedsResp) GetFeeds() []*FeedBrief {
	if x != nil {
		return x.Feeds
	}
	return nil
}

func (x *GetUserFeedsResp) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_api_proto_feed_feed_proto protoreflect.FileDescriptor

const file_api_proto_feed_feed_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/feed/feed.proto\x12\x04feed\"\x8b\x04\n" +
	"\bFeedInfo\x12\x17\n" +
	"\afeed_id\x18\x01 \x01(\x03R\x06feedId\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\x03R\bauthorId\x12\x1b\n" +
	"\tfeed_type\x18\x03 \x01(\x05R\bfeedType\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"media_urls\x18\x06 \x03(\tR\tmediaUrls\x12\x1b\n" +
	"\tcover_url\x18\a \x01(\tR\bcoverUrl\x12\x1b\n" +
	"\tcity_code\x18\b \x01(\tR\bcityCode\x12\x1b\n" +
	"\tcity_name\x18\t \x01(\tR\bcityName\x12\x1f\n" +
	"\vip_location\x18\n" +
	" \x01(\tR\n" +
	"ipLocation\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\x12\x1e\n" +
	"\vis_vip_feed\x18\f \x01(\bR\tisVipFeed\x12\x1d\n" +
	"\n" +
	"like_count\x18\r \x01(\x03R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\x0e \x01(\x03R\fcommentCount\x12#\n" +
	"\rcollect_count\x18\x0f \x01(\x03R\fcollectCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\x03R\tupdatedAt\"\x91\x02\n" +
	"\tFeedBrief\x12\x17\n" +
	"\afeed_id\x18\x01 \x01(\x03R\x06feedId\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\x03R\bauthorId\x12\x1b\n" +
	"\tfeed_type\x18\x03 \x01(\x05R\bfeedType\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1b\n" +
	"\tcover_url\x18\x05 \x01(\tR\bcoverUrl\x12\x1b\n" +
	"\tcity_code\x18\x06 \x01(\tR\bcityCode\x12\x1d\n" +
	"\n" +
	"like_count\x18\a \x01(\x03R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\b \x01(\x03R\fcommentCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\"\x84\x01\n" +
	"\bPageInfo\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\x12\x16\n" +
	"\x06cursor\x18\x05 \x01(\tR\x06cursor\"\x98\x02\n" +
	"\rCreateFeedReq\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x03R\bauthorId\x12\x1b\n" +
	"\tfeed_type\x18\x02 \x01(\x05R\bfeedType\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"media_urls\x18\x05 \x03(\tR\tmediaUrls\x12\x1b\n" +
	"\tcover_url\x18\x06 \x01(\tR\bcoverUrl\x12\x1b\n" +
	"\tcity_code\x18\a \x01(\tR\bcityCode\x12\x1b\n" +
	"\tcity_name\x18\b \x01(\tR\bcityName\x12\x1f\n" +
	"\vip_location\x18\t \x01(\tR\n" +
	"ipLocation\"4\n" +
	"\x0eCreateFeedResp\x12\"\n" +
	"\x04feed\x18\x01 \x01(\v2\x0e.feed.FeedInfoR\x04feed\"A\n" +
	"\rDeleteFeedReq\x12\x17\n" +
	"\afeed_id\x18\x01 \x01(\x03R\x06feedId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"*\n" +
	"\x0eDeleteFeedResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\">\n" +
	"\n" +
	"GetFeedReq\x12\x17\n" +
	"\afeed_id\x18\x01 \x01(\x03R\x06feedId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"1\n" +
	"\vGetFeedResp\x12\"\n" +
	"\x04feed\x18\x01 \x01(\v2\x0e.feed.FeedInfoR\x04feed\"F\n" +
	"\x10BatchGetFeedsReq\x12\x19\n" +
	"\bfeed_ids\x18\x01 \x03(\x03R\afeedIds\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x97\x01\n" +
	"\x11BatchGetFeedsResp\x128\n" +
	"\x05feeds\x18\x01 \x03(\v2\".feed.BatchGetFeedsResp.FeedsEntryR\x05feeds\x1aH\n" +
	"\n" +
	"FeedsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.feed.FeedInfoR\x05value:\x028\x01\"c\n" +
	"\x17GetRecommendTimelineReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\"e\n" +
	"\x18GetRecommendTimelineResp\x12%\n" +
	"\x05feeds\x18\x01 \x03(\v2\x0f.feed.FeedBriefR\x05feeds\x12\"\n" +
	"\x04page\x18\x02 \x01(\v2\x0e.feed.PageInfoR\x04page\"d\n" +
	"\x14GetFollowTimelineReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\"b\n" +
	"\x15GetFollowTimelineResp\x12%\n" +
	"\x05feeds\x18\x01 \x03(\v2\x0f.feed.FeedBriefR\x05feeds\x12\"\n" +
	"\x04page\x18\x02 \x01(\v2\x0e.feed.PageInfoR\x04page\"{\n" +
	"\x12GetCityTimelineReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tcity_code\x18\x02 \x01(\tR\bcityCode\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x03R\bpageSize\"`\n" +
	"\x13GetCityTimelineResp\x12%\n" +
	"\x05feeds\x18\x01 \x03(\v2\x0f.feed.FeedBriefR\x05feeds\x12\"\n" +
	"\x04page\x18\x02 \x01(\v2\x0e.feed.PageInfoR\x04page\"[\n" +
	"\x0fGetUserFeedsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\"]\n" +
	"\x10GetUserFeedsResp\x12%\n" +
	"\x05feeds\x18\x01 \x03(\v2\x0f.feed.FeedBriefR\x05feeds\x12\"\n" +
	"\x04page\x18\x02 \x01(\v2\x0e.feed.PageInfoR\x04page*K\n" +
	"\bFeedType\x12\x15\n" +
	"\x11FEED_TYPE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fFEED_TYPE_IMAGE\x10\x01\x12\x13\n" +
	"\x0fFEED_TYPE_VIDEO\x10\x02*p\n" +
	"\n" +
	"FeedStatus\x12\x17\n" +
	"\x13FEED_STATUS_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12FEED_STATUS_NORMAL\x10\x01\x12\x17\n" +
	"\x13FEED_STATUS_DELETED\x10\x02\x12\x18\n" +
	"\x14FEED_STATUS_AUDITING\x10\x032\x96\x04\n" +
	"\x04Feed\x127\n" +
	"\n" +
	"CreateFeed\x12\x13.feed.CreateFeedReq\x1a\x14.feed.CreateFeedResp\x127\n" +
	"\n" +
	"DeleteFeed\x12\x13.feed.DeleteFeedReq\x1a\x14.feed.DeleteFeedResp\x12.\n" +
	"\aGetFeed\x12\x10.feed.GetFeedReq\x1a\x11.feed.GetFeedResp\x12@\n" +
	"\rBatchGetFeeds\x12\x16.feed.BatchGetFeedsReq\x1a\x17.feed.BatchGetFeedsResp\x12U\n" +
	"\x14GetRecommendTimeline\x12\x1d.feed.GetRecommendTimelineReq\x1a\x1e.feed.GetRecommendTimelineResp\x12L\n" +
	"\x11GetFollowTimeline\x12\x1a.feed.GetFollowTimelineReq\x1a\x1b.feed.GetFollowTimelineResp\x12F\n" +
	"\x0fGetCityTimeline\x12\x18.feed.GetCityTimelineReq\x1a\x19.feed.GetCityTimelineResp\x12=\n" +
	"\fGetUserFeeds\x12\x15.feed.GetUserFeedsReq\x1a\x16.feed.GetUserFeedsRespB\bZ\x06./feedb\x06proto3"

var (
	file_api_proto_feed_feed_proto_rawDescOnce sync.Once
	file_api_proto_feed_feed_proto_rawDescData []byte
)

func file_api_proto_feed_feed_proto_rawDescGZIP() []byte {
	file_api_proto_feed_feed_proto_rawDescOnce.Do(func() {
		file_api_proto_feed_feed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_feed_feed_proto_rawDesc), len(file_api_proto_feed_feed_proto_rawDesc)))
	})
	return file_api_proto_feed_feed_proto_rawDescData
}

var file_api_proto_feed_feed_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_feed_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_proto_feed_feed_proto_goTypes = []any{
	(FeedType)(0),                    // 0: feed.FeedType
	(FeedStatus)(0),                  // 1: feed.FeedStatus
	(*FeedInfo)(nil),                 // 2: feed.FeedInfo
	(*FeedBrief)(nil),                // 3: feed.FeedBrief
	(*PageInfo)(nil),                 // 4: feed.PageInfo
	(*CreateFeedReq)(nil),            // 5: feed.CreateFeedReq
	(*CreateFeedResp)(nil),           // 6: feed.CreateFeedResp
	(*DeleteFeedReq)(nil),            // 7: feed.DeleteFeedReq
	(*DeleteFeedResp)(nil),           // 8: feed.DeleteFeedResp
	(*GetFeedReq)(nil),               // 9: feed.GetFeedReq
	(*GetFeedResp)(nil),              // 10: feed.GetFeedResp
	(*BatchGetFeedsReq)(nil),         // 11: feed.BatchGetFeedsReq
	(*BatchGetFeedsResp)(nil),        // 12: feed.BatchGetFeedsResp
	(*GetRecommendTimelineReq)(nil),  // 13: feed.GetRecommendTimelineReq
	(*GetRecommendTimelineResp)(nil), // 14: feed.GetRecommendTimelineResp
	(*GetFollowTimelineReq)(nil),     // 15: feed.GetFollowTimelineReq
	(*GetFollowTimelineResp)(nil),    // 16: feed.GetFollowTimelineResp
	(*GetCityTimelineReq)(nil),       // 17: feed.GetCityTimelineReq
	(*GetCityTimelineResp)(nil),      // 18: feed.GetCityTimelineResp
	(*GetUserFeedsReq)(nil),          // 19: feed.GetUserFeedsReq
	(*GetUserFeedsResp)(nil),         // 20: feed.GetUserFeedsResp
	nil,                              // 21: feed.BatchGetFeedsResp.FeedsEntry
}
var file_api_proto_feed_feed_proto_depIdxs = []int32{
	2,  // 0: feed.CreateFeedResp.feed:type_name -> feed.FeedInfo
	2,  // 1: feed.GetFeedResp.feed:type_name -> feed.FeedInfo
	21, // 2: feed.BatchGetFeedsResp.feeds:type_name -> feed.BatchGetFeedsResp.FeedsEntry
	3,  // 3: feed.GetRecommendTimelineResp.feeds:type_name -> feed.FeedBrief
	4,  // 4: feed.GetRecommendTimelineResp.page:type_name -> feed.PageInfo
	3,  // 5: feed.GetFollowTimelineResp.feeds:type_name -> feed.FeedBrief
	4,  // 6: feed.GetFollowTimelineResp.page:type_name -> feed.PageInfo
	3,  // 7: feed.GetCityTimelineResp.feeds:type_name -> feed.FeedBrief
	4,  // 8: feed.GetCityTimelineResp.page:type_name -> feed.PageInfo
	3,  // 9: feed.GetUserFeedsResp.feeds:type_name -> feed.FeedBrief
	4,  // 10: feed.GetUserFeedsResp.page:type_name -> feed.PageInfo
	2,  // 11: feed.BatchGetFeedsResp.FeedsEntry.value:type_name -> feed.FeedInfo
	5,  // 12: feed.Feed.CreateFeed:input_type -> feed.CreateFeedReq
	7,  // 13: feed.Feed.DeleteFeed:input_type -> feed.DeleteFeedReq
	9,  // 14: feed.Feed.GetFeed:input_type -> feed.GetFeedReq
	11, // 15: feed.Feed.BatchGetFeeds:input_type -> feed.BatchGetFeedsReq
	13, // 16: feed.Feed.GetRecommendTimeline:input_type -> feed.GetRecommendTimelineReq
	15, // 17: feed.Feed.GetFollowTimeline:input_type -> feed.GetFollowTimelineReq
	17, // 18: feed.Feed.GetCityTimeline:input_type -> feed.GetCityTimelineReq
	19, // 19: feed.Feed.GetUserFeeds:input_type -> feed.GetUserFeedsReq
	6,  // 20: feed.Feed.CreateFeed:output_type -> feed.CreateFeedResp
	8,  // 21: feed.Feed.DeleteFeed:output_type -> feed.DeleteFeedResp
	10, // 22: feed.Feed.GetFeed:output_type -> feed.GetFeedResp
	12, // 23: feed.Feed.BatchGetFeeds:output_type -> feed.BatchGetFeedsResp
	14, // 24: feed.Feed.GetRecommendTimeline:output_type -> feed.GetRecommendTimelineResp
	16, // 25: feed.Feed.GetFollowTimeline:output_type -> feed.GetFollowTimelineResp
	18, // 26: feed.Feed.GetCityTimeline:output_type -> feed.GetCityTimelineResp
	20, // 27: feed.Feed.GetUserFeeds:output_type -> feed.GetUserFeedsResp
	20, // [20:28] is the sub-list for method output_type
	12, // [12:20] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_proto_feed_feed_proto_init() }
func file_api_proto_feed_feed_proto_init() {
	if File_api_proto_feed_feed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_feed_feed_proto_rawDesc), len(file_api_proto_feed_feed_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_feed_feed_proto_goTypes,
		DependencyIndexes: file_api_proto_feed_feed_proto_depIdxs,
		EnumInfos:         file_api_proto_feed_feed_proto_enumTypes,
		MessageInfos:      file_api_proto_feed_feed_proto_msgTypes,
	}.Build()
	File_api_proto_feed_feed_proto = out.File
	file_api_proto_feed_feed_proto_goTypes = nil
	file_api_proto_feed_feed_proto_depIdxs = nil
}
