// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: interaction.proto

package interactionClient

import (
	"context"

	"github.com/sponge-dad/feed/app/interaction/rpc/interaction"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetFeedStatsReq              = interaction.BatchGetFeedStatsReq
	BatchGetFeedStatsResp             = interaction.BatchGetFeedStatsResp
	BatchGetUserInteractionStatusReq  = interaction.BatchGetUserInteractionStatusReq
	BatchGetUserInteractionStatusResp = interaction.BatchGetUserInteractionStatusResp
	CollectFeedReq                    = interaction.CollectFeedReq
	CollectFeedResp                   = interaction.CollectFeedResp
	FeedStats                         = interaction.FeedStats
	GetFeedStatsReq                   = interaction.GetFeedStatsReq
	GetFeedStatsResp                  = interaction.GetFeedStatsResp
	GetUserCollectedFeedsReq          = interaction.GetUserCollectedFeedsReq
	GetUserCollectedFeedsResp         = interaction.GetUserCollectedFeedsResp
	GetUserInteractionStatusReq       = interaction.GetUserInteractionStatusReq
	GetUserInteractionStatusResp      = interaction.GetUserInteractionStatusResp
	GetUserLikedFeedsReq              = interaction.GetUserLikedFeedsReq
	GetUserLikedFeedsResp             = interaction.GetUserLikedFeedsResp
	LikeFeedReq                       = interaction.LikeFeedReq
	LikeFeedResp                      = interaction.LikeFeedResp
	UncollectFeedReq                  = interaction.UncollectFeedReq
	UncollectFeedResp                 = interaction.UncollectFeedResp
	UnlikeFeedReq                     = interaction.UnlikeFeedReq
	UnlikeFeedResp                    = interaction.UnlikeFeedResp
	UserInteractionStatus             = interaction.UserInteractionStatus

	Interaction interface {
		// 动作类
		LikeFeed(ctx context.Context, in *LikeFeedReq, opts ...grpc.CallOption) (*LikeFeedResp, error)
		UnlikeFeed(ctx context.Context, in *UnlikeFeedReq, opts ...grpc.CallOption) (*UnlikeFeedResp, error)
		CollectFeed(ctx context.Context, in *CollectFeedReq, opts ...grpc.CallOption) (*CollectFeedResp, error)
		UncollectFeed(ctx context.Context, in *UncollectFeedReq, opts ...grpc.CallOption) (*UncollectFeedResp, error)
		// 查询类
		GetFeedStats(ctx context.Context, in *GetFeedStatsReq, opts ...grpc.CallOption) (*GetFeedStatsResp, error)
		BatchGetFeedStats(ctx context.Context, in *BatchGetFeedStatsReq, opts ...grpc.CallOption) (*BatchGetFeedStatsResp, error)
		GetUserInteractionStatus(ctx context.Context, in *GetUserInteractionStatusReq, opts ...grpc.CallOption) (*GetUserInteractionStatusResp, error)
		BatchGetUserInteractionStatus(ctx context.Context, in *BatchGetUserInteractionStatusReq, opts ...grpc.CallOption) (*BatchGetUserInteractionStatusResp, error)
		// 列表类
		GetUserLikedFeeds(ctx context.Context, in *GetUserLikedFeedsReq, opts ...grpc.CallOption) (*GetUserLikedFeedsResp, error)
		GetUserCollectedFeeds(ctx context.Context, in *GetUserCollectedFeedsReq, opts ...grpc.CallOption) (*GetUserCollectedFeedsResp, error)
	}

	defaultInteraction struct {
		cli zrpc.Client
	}
)

func NewInteraction(cli zrpc.Client) Interaction {
	return &defaultInteraction{
		cli: cli,
	}
}

// 动作类
func (m *defaultInteraction) LikeFeed(ctx context.Context, in *LikeFeedReq, opts ...grpc.CallOption) (*LikeFeedResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.LikeFeed(ctx, in, opts...)
}

func (m *defaultInteraction) UnlikeFeed(ctx context.Context, in *UnlikeFeedReq, opts ...grpc.CallOption) (*UnlikeFeedResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.UnlikeFeed(ctx, in, opts...)
}

func (m *defaultInteraction) CollectFeed(ctx context.Context, in *CollectFeedReq, opts ...grpc.CallOption) (*CollectFeedResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.CollectFeed(ctx, in, opts...)
}

func (m *defaultInteraction) UncollectFeed(ctx context.Context, in *UncollectFeedReq, opts ...grpc.CallOption) (*UncollectFeedResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.UncollectFeed(ctx, in, opts...)
}

// 查询类
func (m *defaultInteraction) GetFeedStats(ctx context.Context, in *GetFeedStatsReq, opts ...grpc.CallOption) (*GetFeedStatsResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.GetFeedStats(ctx, in, opts...)
}

func (m *defaultInteraction) BatchGetFeedStats(ctx context.Context, in *BatchGetFeedStatsReq, opts ...grpc.CallOption) (*BatchGetFeedStatsResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.BatchGetFeedStats(ctx, in, opts...)
}

func (m *defaultInteraction) GetUserInteractionStatus(ctx context.Context, in *GetUserInteractionStatusReq, opts ...grpc.CallOption) (*GetUserInteractionStatusResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.GetUserInteractionStatus(ctx, in, opts...)
}

func (m *defaultInteraction) BatchGetUserInteractionStatus(ctx context.Context, in *BatchGetUserInteractionStatusReq, opts ...grpc.CallOption) (*BatchGetUserInteractionStatusResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.BatchGetUserInteractionStatus(ctx, in, opts...)
}

// 列表类
func (m *defaultInteraction) GetUserLikedFeeds(ctx context.Context, in *GetUserLikedFeedsReq, opts ...grpc.CallOption) (*GetUserLikedFeedsResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.GetUserLikedFeeds(ctx, in, opts...)
}

func (m *defaultInteraction) GetUserCollectedFeeds(ctx context.Context, in *GetUserCollectedFeedsReq, opts ...grpc.CallOption) (*GetUserCollectedFeedsResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.GetUserCollectedFeeds(ctx, in, opts...)
}
