// feed.proto
//
// 职责：Feed 服务内部 gRPC 接口定义。
// 服务范围：帖子发布、帖子查询、推荐/关注/同城三种流、批量查询、个人主页列表。
// 主要接口：CreateFeed, DeleteFeed, GetFeed, BatchGetFeeds,
//          GetRecommendTimeline, GetFollowTimeline, GetCityTimeline, GetUserFeeds。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: api/proto/feed/feed.proto

package feed

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Feed_CreateFeed_FullMethodName           = "/feed.Feed/CreateFeed"
	Feed_DeleteFeed_FullMethodName           = "/feed.Feed/DeleteFeed"
	Feed_GetFeed_FullMethodName              = "/feed.Feed/GetFeed"
	Feed_BatchGetFeeds_FullMethodName        = "/feed.Feed/BatchGetFeeds"
	Feed_GetRecommendTimeline_FullMethodName = "/feed.Feed/GetRecommendTimeline"
	Feed_GetFollowTimeline_FullMethodName    = "/feed.Feed/GetFollowTimeline"
	Feed_GetCityTimeline_FullMethodName      = "/feed.Feed/GetCityTimeline"
	Feed_GetUserFeeds_FullMethodName         = "/feed.Feed/GetUserFeeds"
)

// FeedClient is the client API for Feed service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeedClient interface {
	// 创建帖子
	CreateFeed(ctx context.Context, in *CreateFeedReq, opts ...grpc.CallOption) (*CreateFeedResp, error)
	// 删除帖子（软删除）
	DeleteFeed(ctx context.Context, in *DeleteFeedReq, opts ...grpc.CallOption) (*DeleteFeedResp, error)
	// 获取帖子详情
	GetFeed(ctx context.Context, in *GetFeedReq, opts ...grpc.CallOption) (*GetFeedResp, error)
	// 批量获取帖子详情
	BatchGetFeeds(ctx context.Context, in *BatchGetFeedsReq, opts ...grpc.CallOption) (*BatchGetFeedsResp, error)
	// 推荐流
	GetRecommendTimeline(ctx context.Context, in *GetRecommendTimelineReq, opts ...grpc.CallOption) (*GetRecommendTimelineResp, error)
	// 关注流
	GetFollowTimeline(ctx context.Context, in *GetFollowTimelineReq, opts ...grpc.CallOption) (*GetFollowTimelineResp, error)
	// 同城流
	GetCityTimeline(ctx context.Context, in *GetCityTimelineReq, opts ...grpc.CallOption) (*GetCityTimelineResp, error)
	// 个人主页帖子列表
	GetUserFeeds(ctx context.Context, in *GetUserFeedsReq, opts ...grpc.CallOption) (*GetUserFeedsResp, error)
}

type feedClient struct {
	cc grpc.ClientConnInterface
}

func NewFeedClient(cc grpc.ClientConnInterface) FeedClient {
	return &feedClient{cc}
}

func (c *feedClient) CreateFeed(ctx context.Context, in *CreateFeedReq, opts ...grpc.CallOption) (*CreateFeedResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFeedResp)
	err := c.cc.Invoke(ctx, Feed_CreateFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) DeleteFeed(ctx context.Context, in *DeleteFeedReq, opts ...grpc.CallOption) (*DeleteFeedResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFeedResp)
	err := c.cc.Invoke(ctx, Feed_DeleteFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) GetFeed(ctx context.Context, in *GetFeedReq, opts ...grpc.CallOption) (*GetFeedResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFeedResp)
	err := c.cc.Invoke(ctx, Feed_GetFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) BatchGetFeeds(ctx context.Context, in *BatchGetFeedsReq, opts ...grpc.CallOption) (*BatchGetFeedsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetFeedsResp)
	err := c.cc.Invoke(ctx, Feed_BatchGetFeeds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) GetRecommendTimeline(ctx context.Context, in *GetRecommendTimelineReq, opts ...grpc.CallOption) (*GetRecommendTimelineResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecommendTimelineResp)
	err := c.cc.Invoke(ctx, Feed_GetRecommendTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) GetFollowTimeline(ctx context.Context, in *GetFollowTimelineReq, opts ...grpc.CallOption) (*GetFollowTimelineResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowTimelineResp)
	err := c.cc.Invoke(ctx, Feed_GetFollowTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) GetCityTimeline(ctx context.Context, in *GetCityTimelineReq, opts ...grpc.CallOption) (*GetCityTimelineResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCityTimelineResp)
	err := c.cc.Invoke(ctx, Feed_GetCityTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) GetUserFeeds(ctx context.Context, in *GetUserFeedsReq, opts ...grpc.CallOption) (*GetUserFeedsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserFeedsResp)
	err := c.cc.Invoke(ctx, Feed_GetUserFeeds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeedServer is the server API for Feed service.
// All implementations must embed UnimplementedFeedServer
// for forward compatibility.
type FeedServer interface {
	// 创建帖子
	CreateFeed(context.Context, *CreateFeedReq) (*CreateFeedResp, error)
	// 删除帖子（软删除）
	DeleteFeed(context.Context, *DeleteFeedReq) (*DeleteFeedResp, error)
	// 获取帖子详情
	GetFeed(context.Context, *GetFeedReq) (*GetFeedResp, error)
	// 批量获取帖子详情
	BatchGetFeeds(context.Context, *BatchGetFeedsReq) (*BatchGetFeedsResp, error)
	// 推荐流
	GetRecommendTimeline(context.Context, *GetRecommendTimelineReq) (*GetRecommendTimelineResp, error)
	// 关注流
	GetFollowTimeline(context.Context, *GetFollowTimelineReq) (*GetFollowTimelineResp, error)
	// 同城流
	GetCityTimeline(context.Context, *GetCityTimelineReq) (*GetCityTimelineResp, error)
	// 个人主页帖子列表
	GetUserFeeds(context.Context, *GetUserFeedsReq) (*GetUserFeedsResp, error)
	mustEmbedUnimplementedFeedServer()
}

// UnimplementedFeedServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFeedServer struct{}

func (UnimplementedFeedServer) CreateFeed(context.Context, *CreateFeedReq) (*CreateFeedResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFeed not implemented")
}
func (UnimplementedFeedServer) DeleteFeed(context.Context, *DeleteFeedReq) (*DeleteFeedResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFeed not implemented")
}
func (UnimplementedFeedServer) GetFeed(context.Context, *GetFeedReq) (*GetFeedResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeed not implemented")
}
func (UnimplementedFeedServer) BatchGetFeeds(context.Context, *BatchGetFeedsReq) (*BatchGetFeedsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetFeeds not implemented")
}
func (UnimplementedFeedServer) GetRecommendTimeline(context.Context, *GetRecommendTimelineReq) (*GetRecommendTimelineResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecommendTimeline not implemented")
}
func (UnimplementedFeedServer) GetFollowTimeline(context.Context, *GetFollowTimelineReq) (*GetFollowTimelineResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFollowTimeline not implemented")
}
func (UnimplementedFeedServer) GetCityTimeline(context.Context, *GetCityTimelineReq) (*GetCityTimelineResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCityTimeline not implemented")
}
func (UnimplementedFeedServer) GetUserFeeds(context.Context, *GetUserFeedsReq) (*GetUserFeedsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserFeeds not implemented")
}
func (UnimplementedFeedServer) mustEmbedUnimplementedFeedServer() {}
func (UnimplementedFeedServer) testEmbeddedByValue()              {}

// UnsafeFeedServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeedServer will
// result in compilation errors.
type UnsafeFeedServer interface {
	mustEmbedUnimplementedFeedServer()
}

func RegisterFeedServer(s grpc.ServiceRegistrar, srv FeedServer) {
	// If the following call panics, it indicates UnimplementedFeedServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Feed_ServiceDesc, srv)
}

func _Feed_CreateFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFeedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).CreateFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Feed_CreateFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).CreateFeed(ctx, req.(*CreateFeedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_DeleteFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFeedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).DeleteFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Feed_DeleteFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).DeleteFeed(ctx, req.(*DeleteFeedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_GetFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).GetFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Feed_GetFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).GetFeed(ctx, req.(*GetFeedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_BatchGetFeeds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetFeedsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).BatchGetFeeds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Feed_BatchGetFeeds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).BatchGetFeeds(ctx, req.(*BatchGetFeedsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_GetRecommendTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecommendTimelineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).GetRecommendTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Feed_GetRecommendTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).GetRecommendTimeline(ctx, req.(*GetRecommendTimelineReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_GetFollowTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowTimelineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).GetFollowTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Feed_GetFollowTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).GetFollowTimeline(ctx, req.(*GetFollowTimelineReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_GetCityTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCityTimelineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).GetCityTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Feed_GetCityTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).GetCityTimeline(ctx, req.(*GetCityTimelineReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_GetUserFeeds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserFeedsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).GetUserFeeds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Feed_GetUserFeeds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).GetUserFeeds(ctx, req.(*GetUserFeedsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Feed_ServiceDesc is the grpc.ServiceDesc for Feed service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Feed_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "feed.Feed",
	HandlerType: (*FeedServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFeed",
			Handler:    _Feed_CreateFeed_Handler,
		},
		{
			MethodName: "DeleteFeed",
			Handler:    _Feed_DeleteFeed_Handler,
		},
		{
			MethodName: "GetFeed",
			Handler:    _Feed_GetFeed_Handler,
		},
		{
			MethodName: "BatchGetFeeds",
			Handler:    _Feed_BatchGetFeeds_Handler,
		},
		{
			MethodName: "GetRecommendTimeline",
			Handler:    _Feed_GetRecommendTimeline_Handler,
		},
		{
			MethodName: "GetFollowTimeline",
			Handler:    _Feed_GetFollowTimeline_Handler,
		},
		{
			MethodName: "GetCityTimeline",
			Handler:    _Feed_GetCityTimeline_Handler,
		},
		{
			MethodName: "GetUserFeeds",
			Handler:    _Feed_GetUserFeeds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/feed/feed.proto",
}
