// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	feedContentProfilesFieldNames          = builder.RawFieldNames(&FeedContentProfiles{})
	feedContentProfilesRows                = strings.Join(feedContentProfilesFieldNames, ",")
	feedContentProfilesRowsExpectAutoSet   = strings.Join(stringx.Remove(feedContentProfilesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	feedContentProfilesRowsWithPlaceHolder = strings.Join(stringx.Remove(feedContentProfilesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheFeedContentProfilesIdPrefix     = "cache:feedContentProfiles:id:"
	cacheFeedContentProfilesFeedIdPrefix = "cache:feedContentProfiles:feedId:"
)

type (
	feedContentProfilesModel interface {
		Insert(ctx context.Context, data *FeedContentProfiles) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*FeedContentProfiles, error)
		FindOneByFeedId(ctx context.Context, feedId int64) (*FeedContentProfiles, error)
		Update(ctx context.Context, data *FeedContentProfiles) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultFeedContentProfilesModel struct {
		sqlc.CachedConn
		table string
	}

	FeedContentProfiles struct {
		Id                 uint64         `db:"id"`
		FeedId             int64          `db:"feed_id"`             // 关联 feeds.id（Snowflake）
		AuthorId           int64          `db:"author_id"`           // 作者ID（冗余，权限校验用）
		MediaHash          string         `db:"media_hash"`          // 媒体指纹（ETag/CRC64/SHA-256），幂等依据
		Category           string         `db:"category"`            // 内容类别（白名单类目）
		Summary            sql.NullString `db:"summary"`             // 内容摘要
		Topics             sql.NullString `db:"topics"`              // 主题标签 ["露营"]
		Objects            sql.NullString `db:"objects"`             // 画面实体
		Scenes             sql.NullString `db:"scenes"`              // 场景标签
		Styles             sql.NullString `db:"styles"`              // 内容形式标签
		Transcript         sql.NullString `db:"transcript"`          // 语音字幕全文
		TranscriptSegments sql.NullString `db:"transcript_segments"` // 分段字幕 [{start_ms,end_ms,text}]
		OcrText            sql.NullString `db:"ocr_text"`            // 关键帧文字（JSON 数组）
		Language           string         `db:"language"`            // 语言（如 zh-CN）
		MediaDurationMs    int64          `db:"media_duration_ms"`   // ffprobe 探测的真实时长(ms)
		KeyFrameCount      int64          `db:"key_frame_count"`     // 关键帧数量
		AnalysisStatus     string         `db:"analysis_status"`     // PENDING/DOWNLOADING/EXTRACTING/ASR_RUNNING/OCR_RUNNING/VISION_RUNNING/INDEXING/COMPLETED/FAILED/DISABLED
		Degraded           int64          `db:"degraded"`            // 1=部分阶段失败但结果可用
		RetryCount         int64          `db:"retry_count"`         // 任务级重试次数
		ModelVersion       string         `db:"model_version"`       // 生成该画像的模型版本
		ErrorMessage       string         `db:"error_message"`       // 已脱敏，禁止含签名地址
		AnalyzedAt         sql.NullTime   `db:"analyzed_at"`         // 分析完成时间
		CreatedAt          time.Time      `db:"created_at"`
		UpdatedAt          time.Time      `db:"updated_at"`
	}
)

func newFeedContentProfilesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFeedContentProfilesModel {
	return &defaultFeedContentProfilesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`feed_content_profiles`",
	}
}

func (m *defaultFeedContentProfilesModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	feedContentProfilesFeedIdKey := fmt.Sprintf("%s%v", cacheFeedContentProfilesFeedIdPrefix, data.FeedId)
	feedContentProfilesIdKey := fmt.Sprintf("%s%v", cacheFeedContentProfilesIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, feedContentProfilesFeedIdKey, feedContentProfilesIdKey)
	return err
}

func (m *defaultFeedContentProfilesModel) FindOne(ctx context.Context, id uint64) (*FeedContentProfiles, error) {
	feedContentProfilesIdKey := fmt.Sprintf("%s%v", cacheFeedContentProfilesIdPrefix, id)
	var resp FeedContentProfiles
	err := m.QueryRowCtx(ctx, &resp, feedContentProfilesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", feedContentProfilesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFeedContentProfilesModel) FindOneByFeedId(ctx context.Context, feedId int64) (*FeedContentProfiles, error) {
	feedContentProfilesFeedIdKey := fmt.Sprintf("%s%v", cacheFeedContentProfilesFeedIdPrefix, feedId)
	var resp FeedContentProfiles
	err := m.QueryRowIndexCtx(ctx, &resp, feedContentProfilesFeedIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `feed_id` = ? limit 1", feedContentProfilesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, feedId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFeedContentProfilesModel) Insert(ctx context.Context, data *FeedContentProfiles) (sql.Result, error) {
	feedContentProfilesFeedIdKey := fmt.Sprintf("%s%v", cacheFeedContentProfilesFeedIdPrefix, data.FeedId)
	feedContentProfilesIdKey := fmt.Sprintf("%s%v", cacheFeedContentProfilesIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, feedContentProfilesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.FeedId, data.AuthorId, data.MediaHash, data.Category, data.Summary, data.Topics, data.Objects, data.Scenes, data.Styles, data.Transcript, data.TranscriptSegments, data.OcrText, data.Language, data.MediaDurationMs, data.KeyFrameCount, data.AnalysisStatus, data.Degraded, data.RetryCount, data.ModelVersion, data.ErrorMessage, data.AnalyzedAt)
	}, feedContentProfilesFeedIdKey, feedContentProfilesIdKey)
	return ret, err
}

func (m *defaultFeedContentProfilesModel) Update(ctx context.Context, newData *FeedContentProfiles) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	feedContentProfilesFeedIdKey := fmt.Sprintf("%s%v", cacheFeedContentProfilesFeedIdPrefix, data.FeedId)
	feedContentProfilesIdKey := fmt.Sprintf("%s%v", cacheFeedContentProfilesIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, feedContentProfilesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.FeedId, newData.AuthorId, newData.MediaHash, newData.Category, newData.Summary, newData.Topics, newData.Objects, newData.Scenes, newData.Styles, newData.Transcript, newData.TranscriptSegments, newData.OcrText, newData.Language, newData.MediaDurationMs, newData.KeyFrameCount, newData.AnalysisStatus, newData.Degraded, newData.RetryCount, newData.ModelVersion, newData.ErrorMessage, newData.AnalyzedAt, newData.Id)
	}, feedContentProfilesFeedIdKey, feedContentProfilesIdKey)
	return err
}

func (m *defaultFeedContentProfilesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheFeedContentProfilesIdPrefix, primary)
}

func (m *defaultFeedContentProfilesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", feedContentProfilesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFeedContentProfilesModel) tableName() string {
	return m.table
}
