// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type GetUserReq struct {
	UserID int64 `path:"userId"`
}

type LoginReq struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required"`
}

type LoginResp struct {
	User  User   `json:"user"`
	Token string `json:"token"`
}

type RegisterReq struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required"`
	Nickname string `json:"nickname" validate:"required"`
}

type RegisterResp struct {
	User  User   `json:"user"`
	Token string `json:"token"`
}

type UpdateUserReq struct {
	Nickname string `json:"nickname,optional"`
	Avatar   string `json:"avatar,optional"`
	Bio      string `json:"bio,optional"`
	CityCode string `json:"city_code,optional"`
	CityName string `json:"city_name,optional"`
}

type UpdateUserResp struct {
	User User `json:"user"`
}

type UploadCredentials struct {
	TmpSecretID  string `json:"tmp_secret_id"`
	TmpSecretKey string `json:"tmp_secret_key"`
	SessionToken string `json:"session_token"`
	ExpiredTime  int64  `json:"expired_time"`
}

type UploadTokenReq struct {
	FileType string `json:"file_type" validate:"required"`
	FileExt  string `json:"file_ext" validate:"required"`
}

type UploadTokenResp struct {
	UploadURL   string            `json:"upload_url"`
	Credentials UploadCredentials `json:"credentials"`
	FileKey     string            `json:"file_key"`
	FileURL     string            `json:"file_url"`
}

type User struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Bio      string `json:"bio"`
	CityName string `json:"city_name"`
}

type UserDetail struct {
	ID             int64  `json:"id"`
	Username       string `json:"username"`
	Nickname       string `json:"nickname"`
	Avatar         string `json:"avatar"`
	Bio            string `json:"bio"`
	CityName       string `json:"city_name"`
	FollowingCount int64  `json:"following_count"`
	FollowerCount  int64  `json:"follower_count"`
	FeedCount      int64  `json:"feed_count"`
	IsFollowing    bool   `json:"is_following"`
}
